function Top($lesson,$title){@"
<div style="font-family: Arial, Helvetica, sans-serif; font-size: 18px; line-height: 1.75; color: #ffffff; max-width: 980px; margin: 0 auto 18px auto; display: flex; justify-content: space-between; align-items: center; gap: 16px; background: #111827; border-radius: 12px; padding: 14px 18px; box-shadow: 0 4px 14px rgba(17,24,39,0.18);"><div style="font-size: 0.95rem; font-weight: 700; letter-spacing: 0.02em;">ALG2 | Unit 03 | Lesson $lesson</div></div>
<div style="font-family: Arial, Helvetica, sans-serif; font-size: 18px; line-height: 1.75; color: #1f2933; max-width: 980px; margin: 0 auto 22px auto; background: #e8f4ff; border-left: 8px solid #2563eb; border-radius: 10px; padding: 24px;"><h1 style="font-size: 30px; margin-top: 0; margin-bottom: 12px;">$title</h1></div>
"@}
function Card($bg,$border,$title,$body){@"
<div style="font-family: Arial, Helvetica, sans-serif; font-size: 18px; line-height: 1.75; color: #1f2933; max-width: 980px; margin: 0 auto 22px auto; border: 1px solid #d1d5db; border-radius: 10px; padding: 22px; background: $bg; border-left: 6px solid $border;"><h2 style="font-size: 24px; margin-top: 0; margin-bottom: 10px;">$title</h2>
$body
</div>
"@}
function WritePage($dir,$file,$content){Set-Content -LiteralPath (Join-Path $dir $file) -Value $content -Encoding UTF8}
function Item($id,$std,$prompt,$correct,$cfb,$wrongs,$pos){
  $choices=New-Object System.Collections.Generic.List[object]
  for($i=0;$i -lt $wrongs.Count;$i+=2){$choices.Add([pscustomobject]@{C=$false;A=$wrongs[$i];F=$wrongs[$i+1]})}
  $choices.Insert($pos,[pscustomobject]@{C=$true;A=$correct;F=("Correct. "+$cfb)})
  [pscustomobject]@{Id=$id;Std=$std;Prompt=$prompt;Choices=$choices}
}
function Make($prefix,$std,$specs,$gp){
  $items=New-Object System.Collections.Generic.List[object]
  for($i=0;$i -lt $specs.Count;$i++){
    $id=if($gp){"{0}{1:D2}" -f $prefix,($i+1)}else{"{0}_Q{1:D2}" -f $prefix,($i+1)}
    $s=$specs[$i]; $items.Add((Item $id $std $s[0] $s[1] $s[2] $s[3] ($i%4)))
  }
  $items
}
function Gift($path,$items){
  $out=New-Object System.Collections.Generic.List[string]
  foreach($it in $items){
    $out.Add("::$($it.Id)::")
    $out.Add("Question ID:<br>$($it.Id)<br><br>MLA Standard:<br>$($it.Std)<br><br>Question:<br>$($it.Prompt) {")
    foreach($ch in $it.Choices){$out.Add(($(if($ch.C){"="}else{"~"})+" $($ch.A)#$($ch.F)"))}
    $out.Add("}");$out.Add("")
  }
  Set-Content -LiteralPath $path -Value ($out -join "`n") -Encoding UTF8
}
function JsonLesson($dir,$lesson,$title,$std,$desc,$bench,$gp,$quiz,$bank,$per){
  $pages=@("P01","P02","P03","P04","P05","P06","P07"|ForEach-Object{@{title=$_;id=$_;file="$_.html"}})
  @{course="ALG2";assessment="Quiz";guidedPractice=@{questionCount=5;graded=$false;file=$gp;feedback="immediate"};masteryThreshold=80;primaryStandards=@(@{code=$std;description=$desc;floridaBenchmark=$bench});pages=$pages;lesson=$lesson;title=$title;unit="Unit 03";quiz=@{attemptPolicy="one_attempt_then_TOR_intervention_if_below_80";randomizedRetakeRequired=$true;questionBank=$true;questionsPerAttempt=$per;bankSize=$bank;file=$quiz}}|ConvertTo-Json -Depth 8|Set-Content -LiteralPath (Join-Path $dir "lesson.json") -Encoding UTF8
}
function JsonQuiz($dir,$lesson,$title,$std,$desc,$bench,$file,$bank,$per,$dist){
  @{course="ALG2";unit="Unit 03";lesson=$lesson;title=$title;primaryStandard=@{code=$std;description=$desc;floridaBenchmark=$bench};format="GIFT";giftFile=$file;questionBankSize=$bank;questionsPerAttempt=$per;masteryThreshold=80;attemptPolicy=@{studentAttemptsBeforeIntervention=1;belowMasteryAction="Teacher of Record intervention and release of another randomized attempt.";questionReuseRule="Questions must not repeat exactly across attempts."};correctAnswerDistribution=$dist}|ConvertTo-Json -Depth 8|Set-Content -LiteralPath (Join-Path $dir "quiz.json") -Encoding UTF8
}

$root="Refined Courses/ALG2/Units/Unit 03";$l7=Join-Path $root "Lesson 07";$l8=Join-Path $root "Lesson 08"
New-Item -ItemType Directory -Force -Path $l7,$l8|Out-Null
$std7="MLA.A2.RR.5; MLA.A2.RR.6";$bench7="MA.912.AR.8.2; MA.912.AR.8.3"
$std8="Unit 3 standards synthesis; no new primary MLA standard";$bench8="Unit 3 benchmarks synthesis; no new primary benchmark"

$pages7=@{
P01=(Top "07" "P01 Lesson Overview")+(Card "#fffbeb" "#f59e0b" "Lesson Title" '<p style="margin-bottom: 14px;"><strong>Lesson 7: Rational Functions and Applications</strong></p><p style="margin-bottom: 14px;">Analyze rational function behavior and model contexts involving rational relationships.</p>')+(Card "#f8fafc" "#64748b" "Standards Covered in This Lesson" '<p style="margin-bottom: 14px;"><strong>MLA.A2.RR.5; MLA.A2.RR.6</strong></p><p style="margin-bottom: 14px;"><strong>Florida B.E.S.T. Benchmark:</strong> MA.912.AR.8.2; MA.912.AR.8.3</p><p style="margin-bottom: 14px;">Analyze rational function graphs, restrictions, asymptotes, and contextual meaning.</p>')+(Card "#ecfdf5" "#059669" "What You Will Learn" '<ul style="padding-left: 26px; margin-bottom: 16px;"><li style="margin-bottom: 8px;">Identify domain restrictions and vertical asymptotes of rational functions.</li><li style="margin-bottom: 8px;">Interpret horizontal asymptotes and end behavior.</li><li style="margin-bottom: 8px;">Connect rational function features to real-world contexts.</li><li style="margin-bottom: 8px;">Use graph features to describe rational relationships.</li></ul>')+(Card "#fff7ed" "#ea580c" "What You Will Do" '<ul style="padding-left: 26px; margin-bottom: 16px;"><li style="margin-bottom: 8px;">Take notes on rational function features.</li><li style="margin-bottom: 8px;">Study worked examples with asymptotes, intercepts, and context restrictions.</li><li style="margin-bottom: 8px;">Complete guided practice, independent work, checkpoint, notebook evidence, and a lesson quiz.</li></ul>')+(Card "#fef2f2" "#dc2626" "How You Will Show Mastery" '<ul style="padding-left: 26px; margin-bottom: 16px;"><li style="margin-bottom: 8px;">Identify rational function domain restrictions.</li><li style="margin-bottom: 8px;">Describe asymptotes and graph behavior accurately.</li><li style="margin-bottom: 8px;">Interpret rational model features in context.</li></ul>')+(Card "#f5f3ff" "#7c3aed" "Student-Friendly Standard Connection" '<p style="margin-bottom: 14px;"><strong>MLA.A2.RR.5; MLA.A2.RR.6:</strong> Analyze rational functions and applications.</p><p style="margin-bottom: 14px;">In student language: <strong>I can read a rational function graph or model and explain its restrictions, asymptotes, and meaning.</strong></p>')
P02=(Top "07" "P02 Notebook Task Part 1")+(Card "#fffbeb" "#f59e0b" "Notebook Setup" '<p style="margin-bottom: 14px;">Title your notes: <strong>Lesson 7: Rational Functions and Applications</strong>.</p><p style="margin-bottom: 14px;">Write the standard: <strong>MLA.A2.RR.5; MLA.A2.RR.6</strong>.</p>')+(Card "#f8fafc" "#64748b" "Key Vocabulary" '<ul style="padding-left: 26px; margin-bottom: 16px;"><li style="margin-bottom: 8px;">Vertical asymptote: a vertical line the graph approaches near a restricted input.</li><li style="margin-bottom: 8px;">Horizontal asymptote: a horizontal line the graph approaches as x becomes very large or very small.</li><li style="margin-bottom: 8px;">Hole: a removable discontinuity caused by a canceled factor.</li><li style="margin-bottom: 8px;">Rational model: a context modeled by a ratio of expressions.</li></ul>')+(Card "#ecfdf5" "#059669" "Correct Example" '<div style="background: #dcfce7; border: 2px solid #16a34a; border-radius: 10px; padding: 16px;"><strong>Correct:</strong> f(x) = 1/(x - 3) has vertical asymptote x = 3 because the denominator is zero there.</div>')+(Card "#fef2f2" "#dc2626" "Incorrect Example" '<div style="background: #fee2e2; border: 2px solid #dc2626; border-radius: 10px; padding: 16px;"><strong>Incorrect:</strong> Saying f(x) = 1/(x - 3) has vertical asymptote x = -3 is incorrect because x - 3 = 0 gives x = 3.</div>')
P03=(Top "07" "P03 Notebook Task Part 2")+(Card "#fffbeb" "#f59e0b" "Notebook Task" '<ol style="padding-left: 26px; margin-bottom: 16px;"><li style="margin-bottom: 8px;">List denominator restrictions for each rational function.</li><li style="margin-bottom: 8px;">Label vertical and horizontal asymptotes.</li><li style="margin-bottom: 8px;">Explain what a restriction means in a real-world context.</li></ol>')+(Card "#ecfdf5" "#059669" "Correct Reasoning" '<div style="background: #dcfce7; border: 2px solid #16a34a; border-radius: 10px; padding: 16px;"><strong>Correct:</strong> For f(x) = 2/(x + 4), the vertical asymptote is x = -4, not x = 4.</div>')+(Card "#fef2f2" "#dc2626" "Common Mistake" '<div style="background: #fee2e2; border: 2px solid #dc2626; border-radius: 10px; padding: 16px;"><strong>Incorrect:</strong> Treating a restricted input as a normal output point is incorrect because the function is undefined there.</div>')
P04=(Top "07" "P04 Concept Instruction / Worked Examples")+(Card "#f8fafc" "#64748b" "Concept Instruction" '<p style="margin-bottom: 14px;">Rational functions often have restrictions and asymptotes. The denominator identifies values that are not allowed. A non-canceled denominator factor usually creates a vertical asymptote. Horizontal asymptotes describe long-run behavior.</p>')+(Card "#ecfdf5" "#059669" "Worked Examples" '<p style="margin-bottom: 14px;"><strong>Example 1:</strong> f(x) = 3/(x - 2) has domain x &ne; 2 and vertical asymptote x = 2.</p><p style="margin-bottom: 14px;"><strong>Example 2:</strong> f(x) = (2x + 1)/(x - 4) has vertical asymptote x = 4 and horizontal asymptote y = 2 because the leading coefficient ratio is 2/1.</p><p style="margin-bottom: 14px;"><strong>Example 3:</strong> If T(n) = 120/n gives time per worker for a fixed job, n = 0 is not allowed because zero workers cannot complete the job.</p>')+(Card "#ecfdf5" "#059669" "Correct Reasoning Check" '<div style="background: #dcfce7; border: 2px solid #16a34a; border-radius: 10px; padding: 16px;"><strong>Correct:</strong> In a model, restrictions must make sense algebraically and contextually.</div>')+(Card "#fef2f2" "#dc2626" "Common Mistake" '<div style="background: #fee2e2; border: 2px solid #dc2626; border-radius: 10px; padding: 16px;"><strong>Incorrect:</strong> Using x = 0 in f(x) = 5/x is incorrect because division by zero is undefined.</div>')
P05=(Top "07" "P05 Guided Practice")+(Card "#fffbeb" "#f59e0b" "Guided Practice" '<p style="margin-bottom: 14px;">Complete the guided practice in Moodle. Identify restrictions and asymptotes before interpreting the graph or context.</p>')+(Card "#ecfdf5" "#059669" "Before You Submit" '<ul style="padding-left: 26px; margin-bottom: 16px;"><li style="margin-bottom: 8px;">Set denominator factors equal to zero to find restrictions.</li><li style="margin-bottom: 8px;">Use leading terms to identify horizontal asymptotes when appropriate.</li><li style="margin-bottom: 8px;">Check whether the context allows the input value.</li></ul>')
P06=(Top "07" "P06 Independent Work + Checkpoint Submission + Notebook Evidence Submission")+(Card "#f8fafc" "#64748b" "Independent Work" '<ol style="padding-left: 26px; margin-bottom: 16px;"><li style="margin-bottom: 8px;">Find the domain and vertical asymptote of f(x) = 4/(x - 5).</li><li style="margin-bottom: 8px;">Find the horizontal asymptote of g(x) = (3x + 2)/(x - 1).</li><li style="margin-bottom: 8px;">Explain why x = 0 is not allowed in h(x) = 10/x.</li><li style="margin-bottom: 8px;">Interpret T(n) = 60/n for n workers.</li><li style="margin-bottom: 8px;">Describe one difference between a vertical asymptote and a horizontal asymptote.</li></ol>')+(Card "#fff7ed" "#ea580c" "Checkpoint Submission" '<p style="margin-bottom: 14px;">Submit one rational function analysis that includes domain restrictions, vertical asymptote, horizontal behavior, and one context interpretation.</p>')+(Card "#f5f3ff" "#7c3aed" "Notebook Evidence Submission" '<p style="margin-bottom: 14px;">Submit notebook evidence showing vocabulary, worked examples, corrected mistakes, independent work, and checkpoint reasoning.</p>')
P07=(Top "07" "P07 Lesson Quiz")+(Card "#fffbeb" "#f59e0b" "Lesson Quiz" '<p style="margin-bottom: 14px;">Complete the lesson quiz in Moodle after finishing notebook work, guided practice, independent work, and checkpoint submission.</p><p style="margin-bottom: 14px;">Use restrictions, asymptotes, and context meaning carefully.</p>')+(Card "#ecfdf5" "#059669" "Quiz Expectations" '<ul style="padding-left: 26px; margin-bottom: 16px;"><li style="margin-bottom: 8px;">Identify restricted inputs.</li><li style="margin-bottom: 8px;">Interpret vertical and horizontal asymptotes.</li><li style="margin-bottom: 8px;">Connect rational model features to context.</li><li style="margin-bottom: 8px;">Demonstrate at least 80% mastery or complete Teacher of Record intervention before another randomized attempt is released.</li></ul>')
}

$pages8=@{
P01=(Top "08" "P01 Putting It All Together Overview")+(Card "#fffbeb" "#f59e0b" "Lesson Title" '<p style="margin-bottom: 14px;"><strong>Lesson 8: Putting It All Together</strong></p><p style="margin-bottom: 14px;">Synthesize radical and rational expression, equation, function, and modeling skills.</p>')+(Card "#f8fafc" "#64748b" "Standards Covered in This Lesson" '<p style="margin-bottom: 14px;"><strong>Unit 3 standards synthesis; no new primary MLA standard</strong></p><p style="margin-bottom: 14px;"><strong>Florida B.E.S.T. Benchmark:</strong> Unit 3 benchmarks synthesis; no new primary benchmark</p><p style="margin-bottom: 14px;">Review and apply all Unit 3 radical and rational relationship standards.</p>')+(Card "#ecfdf5" "#059669" "What You Will Learn" '<ul style="padding-left: 26px; margin-bottom: 16px;"><li style="margin-bottom: 8px;">Connect radical expressions, functions, equations, and applications.</li><li style="margin-bottom: 8px;">Connect rational expressions, equations, functions, and applications.</li><li style="margin-bottom: 8px;">Choose appropriate solving, simplifying, or graph-analysis strategies.</li></ul>')+(Card "#fff7ed" "#ea580c" "What You Will Do" '<ul style="padding-left: 26px; margin-bottom: 16px;"><li style="margin-bottom: 8px;">Review Unit 3 vocabulary and worked examples.</li><li style="margin-bottom: 8px;">Complete cumulative guided practice and independent work.</li><li style="margin-bottom: 8px;">Complete the Unit 3 Assessment in Moodle.</li></ul>')+(Card "#fef2f2" "#dc2626" "How You Will Show Mastery" '<ul style="padding-left: 26px; margin-bottom: 16px;"><li style="margin-bottom: 8px;">Apply Unit 3 standards across mixed problem types.</li><li style="margin-bottom: 8px;">Check restrictions, extraneous solutions, and context validity.</li><li style="margin-bottom: 8px;">Demonstrate readiness for exponential and logarithmic functions.</li></ul>')+(Card "#f5f3ff" "#7c3aed" "Student-Friendly Standard Connection" '<p style="margin-bottom: 14px;"><strong>Unit 3 synthesis:</strong> Radical and rational relationships.</p><p style="margin-bottom: 14px;">In student language: <strong>I can decide which Unit 3 strategy is needed and explain why my answer is valid.</strong></p>')
P02=(Top "08" "P02 Notebook Task Part 1")+(Card "#fffbeb" "#f59e0b" "Notebook Setup" '<p style="margin-bottom: 14px;">Title your notes: <strong>Lesson 8: Putting It All Together</strong>.</p><p style="margin-bottom: 14px;">Write the standard: <strong>Unit 3 standards synthesis</strong>.</p>')+(Card "#f8fafc" "#64748b" "Key Vocabulary Review" '<ul style="padding-left: 26px; margin-bottom: 16px;"><li style="margin-bottom: 8px;">Radical expression, radical function, radical equation, and extraneous solution.</li><li style="margin-bottom: 8px;">Rational expression, restriction, rational equation, vertical asymptote, and horizontal asymptote.</li><li style="margin-bottom: 8px;">Context validity: whether a solution makes sense in a real situation.</li></ul>')+(Card "#ecfdf5" "#059669" "Correct Example" '<div style="background: #dcfce7; border: 2px solid #16a34a; border-radius: 10px; padding: 16px;"><strong>Correct:</strong> For &radic;(x + 4) = 6, x = 32 because x + 4 = 36 and the check works.</div>')+(Card "#fef2f2" "#dc2626" "Incorrect Example" '<div style="background: #fee2e2; border: 2px solid #dc2626; border-radius: 10px; padding: 16px;"><strong>Incorrect:</strong> Reporting x = 0 for a rational equation with denominator x is invalid because x = 0 is restricted.</div>')
P03=(Top "08" "P03 Notebook Task Part 2")+(Card "#fffbeb" "#f59e0b" "Notebook Task" '<ol style="padding-left: 26px; margin-bottom: 16px;"><li style="margin-bottom: 8px;">Create a two-column review chart: radical strategies and rational strategies.</li><li style="margin-bottom: 8px;">Include one example that requires checking for extraneous solutions.</li><li style="margin-bottom: 8px;">Include one example that requires restrictions from a denominator.</li></ol>')+(Card "#ecfdf5" "#059669" "Correct Reasoning" '<div style="background: #dcfce7; border: 2px solid #16a34a; border-radius: 10px; padding: 16px;"><strong>Correct:</strong> Radical equations require checking after squaring; rational equations require restrictions before clearing denominators.</div>')+(Card "#fef2f2" "#dc2626" "Common Mistake" '<div style="background: #fee2e2; border: 2px solid #dc2626; border-radius: 10px; padding: 16px;"><strong>Incorrect:</strong> Treating every algebraic candidate as valid is incorrect because Unit 3 problems often include restrictions.</div>')
P04=(Top "08" "P04 Concept Review / Worked Examples")+(Card "#f8fafc" "#64748b" "Concept Review" '<p style="margin-bottom: 14px;">Unit 3 connects equivalent forms, functions, equations, and context. Match the problem type to the strategy: simplify expressions, analyze graphs, solve equations, or interpret models.</p>')+(Card "#ecfdf5" "#059669" "Worked Examples" '<p style="margin-bottom: 14px;"><strong>Example 1:</strong> 81<sup>3/4</sup> = 27 because the fourth root of 81 is 3 and 3<sup>3</sup> = 27.</p><p style="margin-bottom: 14px;"><strong>Example 2:</strong> &radic;(x - 1) = 4 gives x = 17 and checks.</p><p style="margin-bottom: 14px;"><strong>Example 3:</strong> (x<sup>2</sup> - 9)/(x - 3) = x + 3, with x &ne; 3.</p><p style="margin-bottom: 14px;"><strong>Example 4:</strong> f(x) = 2/(x + 5) has vertical asymptote x = -5.</p>')+(Card "#ecfdf5" "#059669" "Correct Reasoning Check" '<div style="background: #dcfce7; border: 2px solid #16a34a; border-radius: 10px; padding: 16px;"><strong>Correct:</strong> A final answer is complete only when restrictions and context validity have been checked.</div>')+(Card "#fef2f2" "#dc2626" "Common Mistake" '<div style="background: #fee2e2; border: 2px solid #dc2626; border-radius: 10px; padding: 16px;"><strong>Incorrect:</strong> Canceling terms instead of factors in a rational expression leads to non-equivalent expressions.</div>')
P05=(Top "08" "P05 Guided Practice")+(Card "#fffbeb" "#f59e0b" "Guided Practice" '<p style="margin-bottom: 14px;">Complete the cumulative guided practice in Moodle. Decide whether each item is asking for simplification, graph analysis, equation solving, or context interpretation.</p>')+(Card "#ecfdf5" "#059669" "Before You Submit" '<ul style="padding-left: 26px; margin-bottom: 16px;"><li style="margin-bottom: 8px;">Check radical equation candidates in the original equation.</li><li style="margin-bottom: 8px;">List rational restrictions from original denominators.</li><li style="margin-bottom: 8px;">Use function features to interpret graphs and models.</li></ul>')
P06=(Top "08" "P06 Independent Work + Checkpoint Submission + Notebook Evidence Submission")+(Card "#f8fafc" "#64748b" "Independent Work" '<ol style="padding-left: 26px; margin-bottom: 16px;"><li style="margin-bottom: 8px;">Simplify &radic;72.</li><li style="margin-bottom: 8px;">Find the domain of f(x) = &radic;(x - 6).</li><li style="margin-bottom: 8px;">Solve &radic;(x + 3) = 5.</li><li style="margin-bottom: 8px;">Simplify (x<sup>2</sup> - 16)/(x - 4) and state the restriction.</li><li style="margin-bottom: 8px;">Find the vertical asymptote of f(x) = 7/(x + 2).</li></ol>')+(Card "#fff7ed" "#ea580c" "Checkpoint Submission" '<p style="margin-bottom: 14px;">Submit a mixed Unit 3 review problem showing the strategy used, restrictions or checks, and final answer.</p>')+(Card "#f5f3ff" "#7c3aed" "Notebook Evidence Submission" '<p style="margin-bottom: 14px;">Submit notebook evidence showing Unit 3 vocabulary, worked examples, corrected mistakes, independent work, and checkpoint reasoning.</p>')
P07=(Top "08" "P07 Unit Assessment")+(Card "#fffbeb" "#f59e0b" "Unit Assessment" '<p style="margin-bottom: 14px;">Complete the Unit 3 Assessment in Moodle. This replaces a Lesson 8 quiz and covers radical and rational relationships from the full unit.</p><p style="margin-bottom: 14px;">Use your notebook review before starting the assessment.</p>')+(Card "#ecfdf5" "#059669" "Assessment Expectations" '<ul style="padding-left: 26px; margin-bottom: 16px;"><li style="margin-bottom: 8px;">Apply all Unit 3 standards.</li><li style="margin-bottom: 8px;">Use exact notation for radicals, restrictions, domains, and asymptotes.</li><li style="margin-bottom: 8px;">Check all candidates that may be extraneous.</li><li style="margin-bottom: 8px;">Demonstrate at least 80% mastery or complete Teacher of Record intervention if needed.</li></ul>')
}

foreach($k in $pages7.Keys){WritePage $l7 "$k.html" $pages7[$k]}
foreach($k in $pages8.Keys){WritePage $l8 "$k.html" $pages8[$k]}

