$base = "Refined Courses\STATISTICS\Units\Unit 01"
function WriteFile($path,$content){$dir=Split-Path $path -Parent; if(!(Test-Path $dir)){New-Item -ItemType Directory -Force -Path $dir|Out-Null}; Set-Content -LiteralPath $path -Value $content -Encoding UTF8}
function HeaderBlock($lesson,$page){ "<div style='font-family: Arial, Helvetica, sans-serif; font-size: 18px; line-height: 1.75; color: #ffffff; max-width: 980px; margin: 0 auto 18px auto; background: #111827; border-radius: 12px; padding: 14px 18px;'><strong>STATISTICS | Unit 01 | Lesson $lesson</strong></div><div style='font-family: Arial, Helvetica, sans-serif; font-size: 18px; line-height: 1.75; color: #1f2933; max-width: 980px; margin: 0 auto 22px auto; background: #e8f4ff; border-left: 8px solid #2563eb; border-radius: 10px; padding: 24px;'><h1 style='font-size: 30px; margin-top: 0; margin-bottom: 12px;'>$page</h1></div>"}
function CardBlock($color,$title,$body){$map=@{gray='#f8fafc|#64748b';green='#ecfdf5|#059669';orange='#fff7ed|#ea580c';red='#fef2f2|#dc2626';purple='#f5f3ff|#7c3aed';blue='#e8f4ff|#2563eb'}; $a=$map[$color].Split('|'); "<div style='font-family: Arial, Helvetica, sans-serif; font-size: 18px; line-height: 1.75; color: #1f2933; max-width: 980px; margin: 0 auto 22px auto; border: 1px solid #d1d5db; border-radius: 10px; padding: 22px; background: $($a[0]); border-left: 6px solid $($a[1]);'><h2 style='font-size: 24px; margin-top: 0; margin-bottom: 10px;'>$title</h2>$body</div>"}
function GiftItem($id,$std,$q,$correct,$wrong,$letter){
  $choices=@{}; $i=0
  foreach($L in 'A','B','C','D'){ if($L -eq $letter){$choices[$L]=$correct}else{$choices[$L]=$wrong[$i];$i++} }
  $lines=@("::$id::","Question ID: $id","MLA Standard: $std","Question:",$q,"{")
  foreach($L in 'A','B','C','D'){ $prefix=if($L -eq $letter){'='}else{'~'}; $lines += "$prefix$L. $($choices[$L])" }
  $lines += "}"
  $lines -join "`r`n"
}
function WriteGift($path,$items){WriteFile $path (($items -join "`r`n`r`n")+"`r`n")}
function BuildGift($path,$lesson,$standard,$questions,$letters,$prefix){
  $items=@()
  for($i=1;$i -le $questions.Count;$i++){ $items += GiftItem "$prefix$('{0:D2}' -f $i)" $standard $questions[$i-1].q $questions[$i-1].c $questions[$i-1].w $letters[$i-1] }
  WriteGift $path $items
}

$pages=@(@{id='P01';title='Lesson Overview';file='P01.html'},@{id='P02';title='Notebook Task Part 1';file='P02.html'},@{id='P03';title='Notebook Task Part 2';file='P03.html'},@{id='P04';title='Guided Practice / Worked Example';file='P04.html'},@{id='P05';title='Independent Work & Checkpoint';file='P05.html'},@{id='P06';title='Notebook Evidence Submission';file='P06.html'},@{id='P07';title='Checkpoint Submission';file='P07.html'})
$letters25=@('A','B','C','D','A','B','C','D','A','B','C','D','A','B','C','D','A','B','C','D','A','B','C','D','A')
$letters5=@('A','B','C','D','A')

$std5Html="<ul style='padding-left: 26px;'><li><strong>MLA.STAT.STQ.2</strong> - I can interpret a data display by explaining the variables, data type, quantities, context, and what can reasonably be concluded.</li></ul>"
$std6Html="<ul style='padding-left: 26px;'><li><strong>MLA.STAT.DVD.3</strong> - I can construct and interpret segmented bar graphs from relative frequency tables.</li></ul>"
$std5Obj=@(@{code='MLA.STAT.STQ.2';description='I can interpret a data display by explaining the variables, data type, quantities, context, and what can reasonably be concluded.';benchmark='MA.912.DP.1.2'})
$std6Obj=@(@{code='MLA.STAT.DVD.3';description='I can construct and interpret segmented bar graphs from relative frequency tables.';benchmark='MA.912.DP.3.4'})

$l5="$base\Lesson 05"
WriteFile "$l5\P01.html" ((HeaderBlock "05" "P01 Lesson Overview")+(CardBlock orange "Lesson Title" "<p><strong>Lesson 5: Interpreting Components and Quantities in Data Displays</strong></p><p>Learn how to read the title, labels, scales, categories, quantities, and context in a data display before making conclusions.</p>")+(CardBlock gray "Standards Covered in This Lesson" $std5Html)+(CardBlock green "What You Will Learn" "<ul><li>Identify variables, units, labels, categories, and scales in displays.</li><li>Interpret frequencies, relative frequencies, percentages, intervals, and data values.</li><li>State whether a display shows numerical or categorical data.</li><li>Explain what conclusions are reasonable from a display.</li></ul>")+(CardBlock orange "What You Will Do" "<ul><li>Read data displays closely.</li><li>Explain what each graph component represents.</li><li>Connect quantities back to context.</li><li>Separate supported conclusions from unsupported claims.</li></ul>")+(CardBlock red "How You Will Show Mastery" "<ul><li>Complete notebook tasks.</li><li>Submit a checkpoint interpreting a display in context.</li><li>Demonstrate at least 80% mastery on the lesson quiz.</li></ul>")+(CardBlock purple "Student-Friendly Standard Connection" "<p><strong>MLA.STAT.STQ.2:</strong> I can explain what a data display shows, what each quantity means, and what conclusions the display supports.</p>"))
WriteFile "$l5\P02.html" ((HeaderBlock "05" "P02 Notebook Task Part 1")+(CardBlock green "Notebook Task Part 1" "<p>Create a checklist titled <strong>How to Interpret a Data Display</strong>.</p><ul><li>Read the title to identify the context.</li><li>Identify the variable or variables.</li><li>Decide whether the data are numerical or categorical.</li><li>Read axis labels, category labels, units, and scale.</li><li>Identify what quantities represent: counts, percentages, intervals, or data values.</li><li>State only conclusions supported by the display.</li></ul>")+(CardBlock gray "Key Idea" "<p>A display is not just a picture. Each label, scale, and quantity tells what the data mean.</p>"))
WriteFile "$l5\P03.html" ((HeaderBlock "05" "P03 Notebook Task Part 2")+(CardBlock blue "Notebook Task Part 2" "<p>For each display description, write what the quantities represent and one reasonable conclusion.</p><ol><li>A bar chart titled Favorite Study Location with categories home, library, classroom, and cafe.</li><li>A histogram titled Daily Screen Time with intervals in hours.</li><li>A scatterplot titled Practice Time and Free-Throw Percentage.</li><li>A pie chart titled Transportation Method to School.</li></ol>")+(CardBlock orange "Common Mistakes" "<ul><li>Reading category labels as numerical measurements.</li><li>Ignoring units or scale.</li><li>Making cause-and-effect claims from displays that only show patterns.</li><li>Confusing frequency with relative frequency.</li></ul>"))
WriteFile "$l5\P04.html" ((HeaderBlock "05" "P04 Guided Practice / Worked Example")+(CardBlock green "Worked Example" "<p><strong>Display:</strong> A bar chart shows favorite after-school activity. The tallest bar is sports with 18 students.</p><p><strong>Variable:</strong> favorite after-school activity.</p><p><strong>Data type:</strong> categorical.</p><p><strong>Quantity:</strong> 18 is the frequency for the sports category.</p><p><strong>Reasonable conclusion:</strong> Sports was chosen by more students than any other activity shown.</p>")+(CardBlock gray "Guided Practice" "<p>Complete the Moodle Guided Practice bank: <strong>STAT_U01_L05_GuidedPractice.gift</strong>. Use feedback to strengthen your interpretation of graph components and quantities.</p>"))
WriteFile "$l5\P05.html" ((HeaderBlock "05" "P05 Independent Work & Checkpoint")+(CardBlock orange "Independent Work" "<p>Choose four data displays from class materials or a teacher-provided set. For each display, identify the title, variable or variables, data type, quantities, and one supported conclusion.</p>")+(CardBlock red "Checkpoint Prompt" "<p>A histogram shows daily homework time in intervals of 0-15, 16-30, 31-45, and 46-60 minutes. Explain what the intervals and bar heights represent, identify the data type, and state one conclusion the display can support.</p>"))
WriteFile "$l5\P06.html" ((HeaderBlock "05" "P06 Notebook Evidence Submission")+(CardBlock green "Notebook Evidence Submission" "<p>Submit your interpretation checklist, Notebook Task Part 2 responses, and independent work. Include evidence that you can explain graph components and supported conclusions.</p>"))
WriteFile "$l5\P07.html" ((HeaderBlock "05" "P07 Checkpoint Submission")+(CardBlock red "Checkpoint Submission" "<p>Submit your checkpoint response. Identify the display components, explain the quantities, classify the data, and state a supported conclusion.</p>")+(CardBlock gray "Before the Quiz" "<p>Review the difference between what a display shows and what it does not prove.</p>"))
WriteFile "$l5\lesson.json" (@{course='STATISTICS';unit='Unit 01';lesson='Lesson 05';title='Interpreting Components and Quantities in Data Displays';primaryStandards=$std5Obj;assessment='Quiz';masteryThreshold=80;pages=$pages;guidedPractice=@{file='STAT_U01_L05_GuidedPractice.gift';questionCount=5;graded=$false;feedback='immediate'};quiz=@{file='STAT_U01_L05_Quiz.gift';questionBankSize=25;questionsPerAttempt=5;masteryThreshold=80}} | ConvertTo-Json -Depth 8)
WriteFile "$l5\quiz.json" (@{course='STATISTICS';unit='Unit 01';lesson='Lesson 05';title='Quiz: Interpreting Components and Quantities in Data Displays';format='GIFT';giftFile='STAT_U01_L05_Quiz.gift';guidedPracticeFile='STAT_U01_L05_GuidedPractice.gift';questionBankSize=25;questionsPerAttempt=5;masteryThreshold=80;correctAnswerDistribution=@{A=7;B=6;C=6;D=6}} | ConvertTo-Json -Depth 5)

$l6="$base\Lesson 06"
WriteFile "$l6\P01.html" ((HeaderBlock "06" "P01 Lesson Overview")+(CardBlock orange "Lesson Title" "<p><strong>Lesson 6: Relative Frequency Tables and Segmented Bar Graphs</strong></p><p>Learn how to use relative frequency tables to construct and interpret segmented bar graphs for categorical data.</p>")+(CardBlock gray "Standards Covered in This Lesson" $std6Html)+(CardBlock green "What You Will Learn" "<ul><li>Read relative frequency tables using proportions and percentages.</li><li>Construct segmented bar graphs from relative frequencies.</li><li>Interpret category segments within each bar.</li><li>Compare groups using relative frequency instead of raw counts when group sizes differ.</li></ul>")+(CardBlock orange "What You Will Do" "<ul><li>Convert category information into relative frequencies.</li><li>Build segmented bars that total 100% for each group.</li><li>Compare segment sizes across groups.</li><li>Explain conclusions in context.</li></ul>")+(CardBlock red "How You Will Show Mastery" "<ul><li>Complete notebook tasks.</li><li>Submit a checkpoint constructing and interpreting a segmented bar graph.</li><li>Demonstrate at least 80% mastery on the lesson quiz.</li></ul>")+(CardBlock purple "Student-Friendly Standard Connection" "<p><strong>MLA.STAT.DVD.3:</strong> I can turn a relative frequency table into a segmented bar graph and explain what the segments mean.</p>"))
WriteFile "$l6\P02.html" ((HeaderBlock "06" "P02 Notebook Task Part 1")+(CardBlock green "Notebook Task Part 1" "<p>Create a reference page titled <strong>Relative Frequency and Segmented Bars</strong>.</p><ul><li><strong>Frequency:</strong> a count.</li><li><strong>Relative frequency:</strong> a fraction, decimal, or percent of a total.</li><li><strong>Segmented bar graph:</strong> a bar split into sections that show parts of a whole.</li><li>Each segmented bar should total 100% when using percentages.</li></ul>")+(CardBlock gray "Key Idea" "<p>Relative frequencies help compare groups fairly when the groups have different total sizes.</p>"))
WriteFile "$l6\P03.html" ((HeaderBlock "06" "P03 Notebook Task Part 2")+(CardBlock blue "Notebook Task Part 2" "<p>Use this table to plan a segmented bar graph.</p><table style='border-collapse: collapse; width: 100%;'><tr><th style='border:1px solid #d1d5db; padding:8px;'>Group</th><th style='border:1px solid #d1d5db; padding:8px;'>Walk</th><th style='border:1px solid #d1d5db; padding:8px;'>Bus</th><th style='border:1px solid #d1d5db; padding:8px;'>Car</th></tr><tr><td style='border:1px solid #d1d5db; padding:8px;'>Grade 9</td><td style='border:1px solid #d1d5db; padding:8px;'>25%</td><td style='border:1px solid #d1d5db; padding:8px;'>45%</td><td style='border:1px solid #d1d5db; padding:8px;'>30%</td></tr><tr><td style='border:1px solid #d1d5db; padding:8px;'>Grade 10</td><td style='border:1px solid #d1d5db; padding:8px;'>20%</td><td style='border:1px solid #d1d5db; padding:8px;'>35%</td><td style='border:1px solid #d1d5db; padding:8px;'>45%</td></tr></table><p>Write the order and length of segments for each grade-level bar.</p>")+(CardBlock orange "Common Mistakes" "<ul><li>Forgetting each segmented bar should total 100%.</li><li>Comparing raw counts when relative frequencies are needed.</li><li>Switching category order between bars.</li><li>Interpreting a larger segment as a larger total group instead of a larger proportion.</li></ul>"))
WriteFile "$l6\P04.html" ((HeaderBlock "06" "P04 Guided Practice / Worked Example")+(CardBlock green "Worked Example" "<p><strong>Relative frequency table:</strong> Group A has 40% yes and 60% no. Group B has 55% yes and 45% no.</p><p><strong>Segmented bar graph:</strong> Draw two equal-length bars. Split Group A at 40% and 100%. Split Group B at 55% and 100%.</p><p><strong>Interpretation:</strong> Group B has the larger yes segment, so a greater proportion of Group B answered yes.</p>")+(CardBlock gray "Guided Practice" "<p>Complete the Moodle Guided Practice bank: <strong>STAT_U01_L06_GuidedPractice.gift</strong>. Use feedback to check segment totals and interpretations.</p>"))
WriteFile "$l6\P05.html" ((HeaderBlock "06" "P05 Independent Work & Checkpoint")+(CardBlock orange "Independent Work" "<p>Create a relative frequency table for two groups and three categories. Then describe how the segmented bar graph should be constructed and write two comparison statements.</p>")+(CardBlock red "Checkpoint Prompt" "<p>A table shows Grade 9: 30% walk, 50% bus, 20% car and Grade 10: 15% walk, 45% bus, 40% car. Explain how to construct the segmented bars and identify one comparison supported by the graph.</p>"))
WriteFile "$l6\P06.html" ((HeaderBlock "06" "P06 Notebook Evidence Submission")+(CardBlock green "Notebook Evidence Submission" "<p>Submit your reference notes, Notebook Task Part 2 work, and independent work. Include segment totals and comparison statements.</p>"))
WriteFile "$l6\P07.html" ((HeaderBlock "06" "P07 Checkpoint Submission")+(CardBlock red "Checkpoint Submission" "<p>Submit your checkpoint response. Explain the segment lengths, confirm each bar totals 100%, and state a supported comparison.</p>")+(CardBlock gray "Before the Quiz" "<p>Review why segmented bar graphs compare proportions within groups, not just raw counts.</p>"))
WriteFile "$l6\lesson.json" (@{course='STATISTICS';unit='Unit 01';lesson='Lesson 06';title='Relative Frequency Tables and Segmented Bar Graphs';primaryStandards=$std6Obj;assessment='Quiz';masteryThreshold=80;pages=$pages;guidedPractice=@{file='STAT_U01_L06_GuidedPractice.gift';questionCount=5;graded=$false;feedback='immediate'};quiz=@{file='STAT_U01_L06_Quiz.gift';questionBankSize=25;questionsPerAttempt=5;masteryThreshold=80}} | ConvertTo-Json -Depth 8)
WriteFile "$l6\quiz.json" (@{course='STATISTICS';unit='Unit 01';lesson='Lesson 06';title='Quiz: Relative Frequency Tables and Segmented Bar Graphs';format='GIFT';giftFile='STAT_U01_L06_Quiz.gift';guidedPracticeFile='STAT_U01_L06_GuidedPractice.gift';questionBankSize=25;questionsPerAttempt=5;masteryThreshold=80;correctAnswerDistribution=@{A=7;B=6;C=6;D=6}} | ConvertTo-Json -Depth 5)

$l5gp=@(
@{q='In a bar chart of favorite apps, the vertical axis is labeled Number of Students. What do the bar heights represent?';c='Counts of students in each app category#Correct. The axis label shows that each bar height is a frequency count.';w=@('Average screen time for each app#The axis says number of students, not time.','The order in which apps were listed#Bar height represents quantity, not list order.','A relationship between two numerical variables#A bar chart of categories does not show paired numerical data.')},
@{q='A histogram has intervals 0-10, 11-20, and 21-30 minutes. What do the intervals represent?';c='Ranges of a numerical variable#Correct. Histogram intervals group numerical values into ranges.';w=@('Separate category names#The intervals are numerical ranges, not category labels.','Individual students#Each interval may contain several students.','Percentages that must total 100#Intervals are bins; the bar heights may be counts or relative frequencies depending on the label.')},
@{q='A scatterplot shows hours practiced and quiz score. What should each point represent?';c='One person or case with two numerical values#Correct. Each point is a pair of values from the same case.';w=@('One category and its count#That describes a bar chart.','A percent of a whole#That describes a pie chart or relative frequency display.','A five-number summary#That describes a box plot.')},
@{q='A graph shows an upward pattern between study time and score. What conclusion is reasonable?';c='Higher study time is associated with higher scores in the data shown#Correct. The display supports an association, not automatic causation.';w=@('Study time definitely causes higher scores#A display alone does not prove cause.','Scores are categorical data#Scores are numerical.','The graph shows only one variable#A scatterplot pattern uses two variables.')},
@{q='A pie chart shows 35% bus, 45% car, and 20% walk. What does 45% mean?';c='45% of the group uses car transportation#Correct. The slice represents that category share of the whole.';w=@('45 students always use cars#A percent is not a count unless the total is known.','Cars are 45 units faster than buses#The chart shows category share, not speed.','Car is the median category#Categories do not have a median in a pie chart.')}
)
BuildGift "$l5\STAT_U01_L05_GuidedPractice.gift" 5 'MLA.STAT.STQ.2' $l5gp $letters5 'STAT_U01_L05_GP_Q'

$l6gp=@(
@{q='A relative frequency table shows Group A: yes 40%, no 60%. How long should the yes segment be in a 100% segmented bar?';c='40% of the bar#Correct. Segment length matches the relative frequency for that category.';w=@('60% of the bar#60% represents the no category.','100% of the bar#The whole bar represents all responses, not one category.','20% of the bar#20% is not listed in the table.')},
@{q='Why are relative frequencies useful when comparing two groups of different sizes?';c='They compare proportions instead of raw counts#Correct. Proportions make comparisons fair when totals differ.';w=@('They remove the need for categories#Categories are still compared.','They make every group have the same raw count#Relative frequency changes the form of comparison, not the actual counts.','They prove one category caused another#Relative frequencies do not establish causation.')},
@{q='In a segmented bar graph, what should the total length of each bar represent?';c='100% of that group#Correct. Each segmented bar represents the whole group split into category parts.';w=@('The largest category only#The largest category is one segment, not the whole bar.','The raw count in the smallest group#The bar is scaled to the group total, usually 100%.','The number of categories squared#The number of categories does not determine total bar length.')},
@{q='A table shows Grade 9: walk 30%, bus 50%, car 20%. Which segment should be longest?';c='Bus#Correct. Bus has the largest relative frequency at 50%.';w=@('Walk#Walk is 30%, smaller than bus.','Car#Car is 20%, the smallest of the three.','All segments are equal#The percentages are not equal.')},
@{q='A segmented bar graph uses the same category order in every bar. Why is this important?';c='It makes comparisons across groups clearer#Correct. Consistent category order prevents misreading segment positions.';w=@('It changes the relative frequencies#Order does not change the data values.','It makes every segment equal#Segment size still depends on percentage.','It removes the need for labels#Labels are still needed to identify categories.')}
)
BuildGift "$l6\STAT_U01_L06_GuidedPractice.gift" 6 'MLA.STAT.DVD.3' $l6gp $letters5 'STAT_U01_L06_GP_Q'

$l5q=@(
@{q='A bar chart title is Favorite Weekend Activity. What does the title identify?';c='The context of the data display#Correct. The title tells what the display is about.';w=@('The exact value of every data point#A title gives context, not every value.','The cause of the pattern#A title does not prove cause.','The scale interval#Scale intervals are found on an axis, not in the title.')},
@{q='A vertical axis says Frequency. What does frequency mean in the display?';c='Count#Correct. Frequency is the number of cases in a category or interval.';w=@('Percent always#Percent is relative frequency, not frequency.','The category name#Categories are labels, not counts.','The graph title#Frequency is a quantity, not the title.')},
@{q='A histogram bar over 20-29 has height 8. What does that mean?';c='Eight values fall in the interval from 20 to 29#Correct. Histogram bar height shows how many values are in that interval.';w=@('The average is 8#The bar height is frequency, not average.','The interval length is 8#The interval length is determined by endpoints.','There are exactly 20 values#20 is part of the interval label, not the frequency.')},
@{q='In a scatterplot, what do the horizontal and vertical axes usually show?';c='Two numerical variables#Correct. Scatterplot axes show paired numerical measurements.';w=@('Two category names only#Category-only variables do not fit a standard scatterplot.','One frequency table#A frequency table is not shown by two scatterplot axes.','Parts of a whole#Parts of a whole are shown by pie or segmented bar displays.')},
@{q='A pie chart slice is labeled 25%. What does that quantity represent?';c='One category is one-fourth of the whole#Correct. 25% means one part out of the whole group.';w=@('There are exactly 25 people#A percent is not a count unless the total is known.','The category has rank 25#Percent is a share, not rank.','The category causes the whole#A pie chart does not show causation.')},
@{q='Which conclusion is reasonable from a bar chart showing counts by favorite subject?';c='The tallest bar represents the subject with the most responses#Correct. In a count bar chart, taller means more responses.';w=@('The tallest bar caused students to choose the subject#Counts do not prove cause.','The average subject is the tallest bar#Category labels cannot be averaged.','Every student likes only that subject#Other bars may also have responses.')},
@{q='A display has no units on a numerical axis. What problem can this create?';c='The quantities may be hard to interpret correctly#Correct. Units explain what the numerical values measure.';w=@('The graph automatically becomes categorical#Missing units do not change the data type.','The graph proves no pattern exists#Labels do not determine whether a pattern exists.','All answer choices become correct#Assessment choices are unrelated to graph labels.')},
@{q='A relative frequency table gives values 0.20, 0.35, and 0.45. What do these values represent?';c='Proportions of the total#Correct. Relative frequencies are parts of the total.';w=@('Raw category names#The values are numerical proportions.','Axis labels only#They are quantities, not labels.','Exact causes of outcomes#Relative frequencies summarize data; they do not prove causes.')},
@{q='A box plot has a long right whisker. What component is being interpreted?';c='Spread on the high-value side of the distribution#Correct. A longer whisker shows more spread in that direction.';w=@('Category count#Box plots summarize numerical data.','Part of a whole#That describes pie charts or segmented bars.','Two-variable association#That describes scatterplots.')},
@{q='Which statement avoids overclaiming from a data display?';c='The display shows an association in this data set#Correct. This describes what is shown without claiming cause.';w=@('The display proves one variable caused the other#Most displays alone do not prove causation.','The display explains every student behavior#Displays summarize data and have limits.','The display makes labels unnecessary#Labels are needed for interpretation.')},
@{q='A bar chart category has height 12. What additional information is needed to convert that count to a percent?';c='The total number of responses#Correct. Percent equals category count divided by total responses.';w=@('The color of the bar#Color does not determine percent.','The category name length#Name length is irrelevant.','The title font size#Font size is formatting, not data.')},
@{q='Which display component tells what each axis measures?';c='Axis label#Correct. Axis labels identify variables and units.';w=@('Background color#Color is formatting.','Border thickness#Borders do not identify variables.','Answer letter#Answer letters are not graph components.')},
@{q='A graph shows bus: 30 students and car: 20 students. What quantity is 30?';c='Frequency for the bus category#Correct. The number is a count for that category.';w=@('Relative frequency for all categories#A count is not a relative frequency unless divided by total.','A numerical interval#Bus is a category, not an interval.','A causal effect#The count does not show cause.')},
@{q='A student says the largest pie slice means that group caused the result. What is the error?';c='A largest slice shows largest share, not cause#Correct. Pie charts show proportions, not causation.';w=@('Pie charts cannot have large slices#Pie slices can vary in size.','Categories cannot be counted#Categories can be counted.','Percentages cannot be shown visually#Pie charts can show percentages visually.')},
@{q='Which interpretation fits a scatterplot point at (3, 80) for hours studied and test score?';c='One student studied 3 hours and scored 80#Correct. A point represents paired values for one case.';w=@('Three students scored 80 total#The point is a pair, not a count of students.','80 students studied 3 hours#The coordinates are variable values, not necessarily counts.','The average score is 3#The x-value is hours studied, not average score.')},
@{q='What does scale help determine on a graph?';c='How numerical distances and quantities are read#Correct. Scale controls how values are marked and interpreted.';w=@('Which data caused the result#Scale does not prove cause.','Whether categories are allowed#Categories can be displayed with or without numerical scale.','The course standard code#Standards are separate from graph scale.')},
@{q='Which is the best first step when interpreting a display?';c='Read the title and labels#Correct. Title and labels establish context, variables, and units.';w=@('Assume the tallest mark proves cause#Height shows quantity, not cause.','Ignore units to save time#Units are essential for accurate interpretation.','Average the category names#Category names cannot be averaged.')},
@{q='A segmented bar graph compares percentages by grade. What do segment lengths represent?';c='Relative frequencies within each grade#Correct. Segment lengths show proportions for categories within each group.';w=@('Raw counts only#Segmented bars usually compare proportions.','Median values#Median applies to numerical data.','Exact individual responses#The graph summarizes groups.')},
@{q='Which display component identifies categories in a bar chart?';c='Category labels#Correct. Category labels name the groups being compared.';w=@('Numerical intervals#Intervals belong to histograms.','Correlation coefficient#That measures strength of numerical association.','Five-number summary#That belongs to box plots.')},
@{q='A histogram has bars for intervals, but no title. What is missing?';c='Context for what the data values represent#Correct. Without a title, the viewer may not know what is being measured.';w=@('All numerical values#The bars may still show values by interval.','All category labels#Histograms use intervals, not category labels.','The correct answer letter#Graphs do not include quiz answer letters.')},
@{q='Which statement is supported by a display showing 60% prefer online review?';c='A majority of the group prefers online review#Correct. 60% is more than half.';w=@('Online review caused higher grades#Preference data alone does not prove grade effects.','Exactly 60 students prefer online review#Percent is not count unless total is known.','No one prefers other methods#If 60% prefer online, 40% prefer something else or are in other categories.')},
@{q='In a histogram, why are the bars usually adjacent?';c='The intervals represent connected ranges of numerical data#Correct. Adjacent bars show continuous or ordered numerical intervals.';w=@('The categories are unrelated labels#That describes bar charts, not histograms.','The bars prove causation#Bar placement does not prove cause.','The graph has two variables#Histograms show one numerical variable.')},
@{q='What should a supported conclusion include?';c='A statement tied to the variables and quantities shown#Correct. A good conclusion uses the display evidence and context.';w=@('A claim about causes not shown#Unsupported cause claims overreach.','A guess unrelated to the labels#Conclusions should connect to the display.','A replacement for the data source#A conclusion does not replace the data.')},
@{q='A two-way table shows counts by grade and transportation method. What kind of data is represented?';c='Two categorical variables#Correct. Grade and transportation method are categories.';w=@('One numerical variable#There are two categorical variables.','Two numerical variables#No measured quantities are paired as variables.','A numerical distribution only#The table organizes categorical counts.')},
@{q='Which question checks whether a conclusion is reasonable?';c='Does the display actually show evidence for the claim?#Correct. Conclusions must be supported by the displayed data.';w=@('Is the graph colorful enough?#Color does not determine statistical support.','Can the title be ignored?#The title provides context.','Can labels be replaced with guesses?#Labels should not be guessed or ignored.')}
)
BuildGift "$l5\STAT_U01_L05_Quiz.gift" 5 'MLA.STAT.STQ.2' $l5q $letters25 'STAT_U01_L05_Q'

$l6q=@(
@{q='A relative frequency of 0.25 is equal to what percent?';c='25%#Correct. Multiply 0.25 by 100 to convert to percent.';w=@('2.5%#This moves the decimal one place too few.','250%#This moves the decimal too far.','75%#75% is the complement of 25%, not the conversion.')},
@{q='In a segmented bar graph, each complete bar usually represents what?';c='100% of one group#Correct. Each bar is split into category segments that total the whole group.';w=@('One category only#A complete bar contains all categories for a group.','The largest raw count#The bar length is standardized, usually to 100%.','The number of survey questions#The bar represents a group total, not question count.')},
@{q='A table shows 60% yes and 40% no. Which segment should be longer?';c='Yes#Correct. 60% is larger than 40%, so the yes segment is longer.';w=@('No#No is only 40%.','Both equal#The percentages are not equal.','Neither, because percentages cannot be graphed#Percentages can be shown in segmented bars.')},
@{q='Why should the same category order be used in each segmented bar?';c='To make comparisons across groups easier#Correct. Consistent order helps viewers compare matching categories.';w=@('To change counts into decimals#Order does not perform conversion.','To make all segments equal#Segment sizes still depend on relative frequencies.','To hide the smallest category#Displays should communicate clearly, not hide categories.')},
@{q='A group has 12 yes responses out of 30 total. What is the relative frequency for yes?';c='40%#Correct. 12 divided by 30 equals 0.40, or 40%.';w=@('12%#The count is 12, but the percent uses 12 divided by 30.','30%#The total is 30, not the percent yes.','60%#60% would represent 18 out of 30.')},
@{q='When are relative frequencies better than raw counts?';c='When group sizes are different#Correct. Relative frequencies compare proportions fairly across unequal totals.';w=@('When all data are numerical measurements#Relative frequency tables are often used for categorical data.','When no categories exist#Categories are needed for these comparisons.','When the display has no labels#Labels are still required.')},
@{q='Grade 9 has 30% walk and Grade 10 has 15% walk. What comparison is supported?';c='Grade 9 has a greater proportion of walkers#Correct. 30% is greater than 15%.';w=@('Grade 9 has exactly twice as many walkers#Percentages compare proportions, not raw counts.','Grade 10 has more walkers#15% is a smaller proportion than 30%.','Both grades have equal walking proportions#The percentages are different.')},
@{q='What should the segments in one bar add to when using percentages?';c='100%#Correct. The segments represent all categories within that group.';w=@('50%#A complete group should total 100%, not 50%.','The largest category only#The whole bar includes all categories.','The number of categories#Percent totals are based on the whole, not category count.')},
@{q='A segmented bar has 20%, 30%, and 50% segments. Which is the largest segment?';c='50%#Correct. 50% is the greatest relative frequency.';w=@('20%#20% is the smallest of the listed values.','30%#30% is less than 50%.','All are equal#The percentages are different.')},
@{q='What does a segmented bar graph display from a relative frequency table?';c='How category proportions make up each group#Correct. Segment lengths represent category shares within each group.';w=@('Only individual data values#The graph summarizes groups.','Only medians and quartiles#That is a box plot purpose.','Only paired numerical points#That is a scatterplot purpose.')},
@{q='A relative frequency table lists 0.10, 0.30, and 0.60. What should these become on a percent bar?';c='10%, 30%, and 60%#Correct. Each decimal is multiplied by 100.';w=@('1%, 3%, and 6%#This conversion is too small by a factor of 10.','100%, 300%, and 600%#This conversion is too large.','90%, 70%, and 40%#These are complements, not conversions.')},
@{q='A segmented bar shows Group A has a larger music segment than Group B. What does that mean?';c='A greater proportion of Group A chose music#Correct. Segment size compares proportions within each group.';w=@('Group A must have more total people#The bars are standardized, so total size may differ.','Music caused Group A membership#The graph does not show causation.','Group B has no music responses#A smaller segment may still be greater than zero.')},
@{q='What is the first step when constructing a segmented bar graph from percentages?';c='Check that each group totals 100%#Correct. Each bar should represent the whole group.';w=@('Draw bars with different total lengths#Segmented percent bars should have equal total length.','Ignore category labels#Labels are needed to identify segments.','Convert every percent to a raw count#Raw counts are not needed if relative frequencies are already given.')},
@{q='A group has 8 car riders out of 20 students. What percent ride by car?';c='40%#Correct. 8 divided by 20 equals 0.40, or 40%.';w=@('8%#The count is 8, not the percent.','20%#20 is the total count, not the percent.','60%#60% would be 12 out of 20.')},
@{q='Why can raw counts be misleading when groups have unequal totals?';c='A larger count may come from a larger group, not a larger proportion#Correct. Relative frequency controls for group size.';w=@('Counts can never be used in statistics#Counts are useful but may not be best for unequal groups.','Percentages remove categories#Categories remain part of the display.','Unequal groups cannot be compared at all#They can be compared with relative frequencies.')},
@{q='Which table can be used directly to construct a segmented bar graph?';c='A table of percentages by group and category#Correct. Percentages give segment lengths directly.';w=@('A list of unrelated numerical measurements#Segmented bars summarize categorical proportions.','A table with no categories#Segments need categories.','A scatterplot coordinate table#Scatterplots use paired numerical values.')},
@{q='In Grade 9, bus is 50%; in Grade 10, bus is 45%. What is true?';c='Grade 9 has a slightly greater bus proportion#Correct. 50% is greater than 45%.';w=@('Grade 10 has a greater bus proportion#45% is less than 50%.','Both bus proportions are equal#The values differ by 5 percentage points.','Bus is impossible to compare#The same category can be compared across groups.')},
@{q='What does relative frequency mean?';c='A part of a total, often written as a decimal or percent#Correct. Relative frequency compares a category to its group total.';w=@('A count with no total#That is frequency, not relative frequency.','A category name#Category names identify groups, not proportions.','A cause-and-effect conclusion#Relative frequency is descriptive.')},
@{q='A segmented bar graph has unlabeled segments. What problem occurs?';c='The viewer cannot tell which category each segment represents#Correct. Labels or a legend are needed to interpret segments.';w=@('The percentages automatically become wrong#Missing labels do not change the values, but they make interpretation unclear.','The graph becomes a scatterplot#Labels do not change the graph type.','The bars no longer total 100%#Total length is separate from labeling.')},
@{q='A table shows 25%, 25%, 25%, and 25% for one group. How should the segments look?';c='Four equal segments#Correct. Equal percentages produce equal segment lengths.';w=@('One segment should take the whole bar#Each category has only 25%.','The first segment should be longest#All percentages are equal.','No graph can be drawn#A segmented bar can be drawn with equal segments.')},
@{q='What comparison should be made from segmented bars?';c='Category proportions across groups#Correct. Segmented bars compare relative frequencies.';w=@('Exact individual scores#The display summarizes categories.','Median and range#Those are numerical summary measures.','Slope and intercept#Those belong to linear models.')},
@{q='A category has relative frequency 0.05. What percent of the bar is that?';c='5%#Correct. 0.05 equals 5%.';w=@('50%#0.50 equals 50%, not 0.05.','0.5%#0.005 equals 0.5%.','95%#95% is the complement of 5%.')},
@{q='Which conclusion is supported if Group B has the largest car segment?';c='Group B has the greatest proportion choosing car#Correct. Largest segment means largest relative frequency for that category.';w=@('Group B has the greatest total number of people#Segmented bars compare proportions, not necessarily totals.','Car choice caused membership in Group B#The graph does not prove cause.','No other group has car riders#Other groups may have smaller car segments.')},
@{q='Which mistake would make a segmented bar graph misleading?';c='Using bars with different total lengths for percentage comparisons#Correct. Equal total bar lengths are needed when each bar represents 100%.';w=@('Keeping category order consistent#That improves clarity.','Labeling each segment#Labels support interpretation.','Checking that each bar totals 100%#That is necessary.')},
@{q='A relative frequency table has rows for two grades and columns for transportation categories. What does one row represent?';c='The distribution of transportation categories within one grade#Correct. Each row shows category proportions for that group.';w=@('A single numerical measurement#The row summarizes categorical proportions.','A five-number summary#That belongs to numerical data.','A cause-and-effect explanation#The row describes data; it does not explain causes.')}
)
BuildGift "$l6\STAT_U01_L06_Quiz.gift" 6 'MLA.STAT.DVD.3' $l6q $letters25 'STAT_U01_L06_Q'

Write-Output "Statistics Unit 1 Lessons 5-6 built"
