from pathlib import Path

root = Path("Refined Courses/ALG2/Units/Unit 02")


def q(qid, std, prompt, correct, cfb, wrongs, pos):
    choices = [(True, correct, "Correct. " + cfb)]
    choices += [(False, wrongs[i], wrongs[i + 1]) for i in range(0, len(wrongs), 2)]
    correct_choice = choices[0]
    arranged = choices[1:]
    arranged.insert(pos, correct_choice)
    return {
        "id": qid,
        "std": std,
        "prompt": prompt,
        "choices": arranged,
    }


def write(path, items):
    out = []
    for item in items:
        out.append(f"::{item['id']}::")
        out.append(
            f"Question ID:<br>{item['id']}<br><br>MLA Standard:<br>{item['std']}<br><br>Question:<br>{item['prompt']} {{"
        )
        for correct, ans, fb in item["choices"]:
            out.append(("=" if correct else "~") + f"{ans} #{fb}")
        out.append("}")
        out.append("")
    path.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")


def make(prefix, std, specs):
    return [
        q(f"{prefix}_Q{i:02d}", std, prompt, correct, cfb, wrongs, (i - 1) % 4)
        for i, (prompt, correct, cfb, wrongs) in enumerate(specs, 1)
    ]


std3 = "MLA.A2.PF.8"
support = "Support-only review; no new primary MLA standard"
application = "Support-only application; no new primary MLA standard"
std7 = "MLA.A2.PF.2; MLA.A2.PF.5; MLA.A2.PF.6"

l3 = [
("What is the end behavior of f(x) = 2x<sup>4</sup> - 1?", "both ends rise", "The leading term 2x<sup>4</sup> has even degree and positive coefficient.", ["both ends fall", "That would require an even degree with a negative leading coefficient.", "left falls, right rises", "That is odd positive behavior.", "left rises, right falls", "That is odd negative behavior."]),
("What is the end behavior of f(x) = -3x<sup>5</sup> + x?", "left rises, right falls", "Odd degree with a negative leading coefficient rises left and falls right.", ["both ends rise", "Odd-degree functions have opposite end behavior.", "left falls, right rises", "That would match a positive leading coefficient.", "both ends fall", "Both ends falling is even negative behavior."]),
("Which term controls end behavior of 4x<sup>6</sup> - 9x<sup>2</sup> + 3?", "4x<sup>6</sup>", "The highest-degree term dominates for very large positive or negative x-values.", ["-9x<sup>2</sup>", "This is not the highest-degree term.", "3", "A constant does not determine long-run behavior.", "all terms equally", "The leading term dominates the lower-degree terms."]),
("What is the degree of f(x) = -7x<sup>3</sup> + 2x<sup>2</sup> - 1?", "3", "The greatest exponent in the polynomial is 3.", ["2", "The polynomial includes a cubic term.", "-7", "This is the leading coefficient.", "1", "The constant term does not make the polynomial degree 1."]),
("What is the leading coefficient of f(x) = -7x<sup>3</sup> + 2x<sup>2</sup> - 1?", "-7", "The coefficient on the highest-degree term is -7.", ["3", "This is the degree.", "2", "This coefficient belongs to a lower-degree term.", "-1", "This is the constant term."]),
("Which end behavior matches g(x) = -5x<sup>4</sup> + 8x?", "both ends fall", "The leading term is even degree and negative.", ["both ends rise", "A negative leading coefficient on an even degree makes both ends fall.", "left falls, right rises", "That is odd positive behavior.", "left rises, right falls", "That is odd negative behavior."]),
("For h(x) = x<sup>7</sup> - 4x<sup>2</sup>, what happens as x increases without bound?", "h(x) increases without bound", "The leading term x<sup>7</sup> controls the right end and is positive.", ["h(x) decreases without bound", "A positive odd-degree leading term rises to the right.", "h(x) approaches 0", "This polynomial does not approach 0 on the right.", "h(x) stays constant", "The output grows without bound."]),
("For p(x) = -2x<sup>6</sup> + 11, what happens as x decreases without bound?", "p(x) decreases without bound", "Even degree with a negative leading coefficient falls on both ends.", ["p(x) increases without bound", "A negative even-degree leading term falls on the left.", "p(x) approaches 11", "The constant does not control far-left behavior.", "p(x) approaches 0", "The leading term grows in magnitude."]),
("Which polynomial has left end down and right end up?", "3x<sup>5</sup> - x", "Odd degree with a positive leading coefficient falls left and rises right.", ["-x<sup>4</sup> + 2", "Even degree gives the same direction on both ends.", "x<sup>4</sup> - 2x", "Even degree with positive leading coefficient rises on both ends.", "-3x<sup>5</sup> + x", "Odd degree with a negative coefficient rises left and falls right."]),
("Which polynomial has both ends falling?", "-2x<sup>8</sup> + x", "Even degree with a negative leading coefficient falls on both ends.", ["4x<sup>2</sup> - 9", "Even degree with positive leading coefficient rises on both ends.", "5x<sup>3</sup> - 1", "Odd degree has opposite end behavior.", "-x<sup>5</sup> + 6", "Odd degree has opposite end behavior."]),
("What is the leading term of f(x) = 6 - 3x + 9x<sup>4</sup>?", "9x<sup>4</sup>", "The highest-degree term is 9x<sup>4</sup>.", ["6", "This is the constant term.", "-3x", "This is a lower-degree term.", "x<sup>4</sup>", "This omits the coefficient."]),
("Which statement is true for f(x) = -x<sup>9</sup> + 2x<sup>3</sup> - 4?", "The graph rises left and falls right.", "The leading term is odd degree with a negative coefficient.", ["The graph falls left and rises right.", "That would require a positive leading coefficient.", "Both ends rise.", "That requires even degree with positive leading coefficient.", "Both ends fall.", "That requires even degree with negative leading coefficient."]),
("Which term determines the end behavior of 12x - x<sup>5</sup> + 4x<sup>2</sup>?", "-x<sup>5</sup>", "The fifth-degree term controls end behavior.", ["12x", "This is not the highest-degree term.", "4x<sup>2</sup>", "This term is lower degree.", "12x + 4x<sup>2</sup>", "End behavior is controlled by the highest-degree term."]),
("What is the degree of f(x) = 10 - 4x<sup>8</sup> + x<sup>3</sup>?", "8", "The greatest exponent is 8.", ["10", "This is the constant term.", "4", "The coefficient is not the degree.", "3", "There is an eighth-degree term."]),
("What is the leading coefficient of q(x) = 2x<sup>2</sup> - 9x<sup>6</sup> + 5?", "-9", "The leading term is -9x<sup>6</sup>.", ["2", "This coefficient is on a lower-degree term.", "6", "This is the degree.", "5", "This is the constant term."]),
("A polynomial falls left and rises right. What must be true about its leading term?", "It has odd degree and positive coefficient.", "Positive odd-degree leading terms fall left and rise right.", ["It has odd degree and negative coefficient.", "That would rise left and fall right.", "It has even degree and positive coefficient.", "That would rise on both ends.", "It has even degree and negative coefficient.", "That would fall on both ends."]),
("A polynomial rises on both ends. Which leading term could it have?", "7x<sup>8</sup>", "Positive even-degree leading terms rise on both ends.", ["-4x<sup>6</sup>", "Negative even-degree leading terms fall on both ends.", "3x<sup>5</sup>", "Odd degree gives opposite end behavior.", "-x<sup>7</sup>", "Odd degree gives opposite end behavior."]),
("Which describes f(x) = 0.5x<sup>3</sup> - 2x<sup>2</sup> + 1?", "left falls, right rises", "The leading term is odd degree with a positive coefficient.", ["both ends rise", "A cubic has opposite end behavior.", "both ends fall", "A cubic has opposite end behavior.", "left rises, right falls", "That would require a negative leading coefficient."]),
("What is the end behavior of f(x) = -6x<sup>2</sup> + 3x - 4?", "both ends fall", "The leading term has even degree and a negative coefficient.", ["both ends rise", "A negative quadratic falls on both ends.", "left falls, right rises", "That describes positive odd-degree behavior.", "left rises, right falls", "That describes negative odd-degree behavior."]),
("Which polynomial has the same end behavior as f(x) = -x<sup>4</sup> + 7?", "-3x<sup>6</sup> + 2", "Both have even degree and negative leading coefficient.", ["3x<sup>6</sup> - 2", "This rises on both ends.", "-3x<sup>5</sup> + 2", "Odd degree has opposite end behavior.", "3x<sup>5</sup> - 2", "Odd degree has opposite end behavior."]),
("For f(x) = 8x<sup>10</sup> - x<sup>9</sup>, which part matters most for end behavior?", "8x<sup>10</sup>, because it has the greatest degree", "Degree 10 is greater than degree 9.", ["-x<sup>9</sup>, because it is negative", "Sign matters after identifying the highest degree.", "both terms equally", "The highest-degree term dominates.", "the constant term", "There is no constant term controlling end behavior."]),
("A graph rises left and falls right. Which function could match?", "f(x) = -x<sup>3</sup> + 1", "A negative cubic rises left and falls right.", ["f(x) = x<sup>4</sup> - 1", "This rises on both ends.", "f(x) = -x<sup>4</sup> + 1", "This falls on both ends.", "f(x) = x<sup>3</sup> - 1", "This falls left and rises right."]),
("Which expression is the leading term of r(x) = -2 + 5x<sup>2</sup> - 3x<sup>7</sup>?", "-3x<sup>7</sup>", "It has the greatest exponent.", ["5x<sup>2</sup>", "This is a lower-degree term.", "-2", "This is the constant term.", "7", "This is the degree, not a term."]),
("If f(x) has leading term -0.25x<sup>12</sup>, what happens to both ends?", "both ends fall", "Even degree and negative leading coefficient means both ends fall.", ["both ends rise", "The coefficient is negative.", "left falls, right rises", "Odd positive behavior does not apply.", "left rises, right falls", "Odd negative behavior does not apply."]),
("If a polynomial has odd degree and positive leading coefficient, which statement is true?", "The left end falls and the right end rises.", "Positive odd degree falls left and rises right.", ["Both ends rise.", "That describes positive even degree.", "Both ends fall.", "That describes negative even degree.", "The left end rises and the right end falls.", "That describes negative odd degree."]),
]

write(root / "Lesson 03" / "ALG2_U02_L03_Quiz.gift", make("ALG2_U02_L03", std3, l3))

l4_prompts = [
("What are the zeros of f(x) = (x - 2)(x + 7)?", "x = 2 and x = -7", "Set each factor equal to zero: x - 2 = 0 and x + 7 = 0.", ["x = -2 and x = 7", "These reverse the signs from the factors.", "x = 2 and x = 7", "The second zero should be negative.", "x = -2 and x = -7", "The first zero should be positive."]),
("What is the multiplicity of x = -4 in f(x) = (x + 4)<sup>3</sup>(x - 1)?", "3", "The exponent on x + 4 shows multiplicity 3.", ["-4", "This is the zero, not its multiplicity.", "1", "This is the multiplicity of x = 1.", "4", "The exponent gives multiplicity."]),
("A zero with even multiplicity usually does what at the x-axis?", "touches and turns", "Even multiplicity means the sign often does not change at the zero.", ["crosses straight through", "Crossing is typical of odd multiplicity.", "creates a vertical asymptote", "Polynomial functions do not have vertical asymptotes.", "disappears from the graph", "Zeros remain visible as intercepts or touch points."]),
("A zero with odd multiplicity usually does what at the x-axis?", "crosses the x-axis", "Odd multiplicity means the function usually changes sign at the zero.", ["touches and turns", "That is typical of even multiplicity.", "creates a hole", "Polynomial graphs are continuous.", "has no x-intercept", "A real zero is an x-intercept or contact point."]),
("Which zero comes from the factor x + 6?", "x = -6", "Solving x + 6 = 0 gives x = -6.", ["x = 6", "This reverses the sign.", "x = 0", "The factor equals zero at -6.", "x = -1", "The coefficient of x is not the zero."]),
("For f(x) = (x - 5)<sup>2</sup>(x + 3), which zero has multiplicity 2?", "x = 5", "The repeated factor gives zero x = 5 with multiplicity 2.", ["x = -5", "The sign is reversed.", "x = -3", "This zero has multiplicity 1.", "x = 3", "This is sign-reversed."]),
("What is the zero of f(x) = 4(x + 9)(x - 2) that comes from x - 2?", "x = 2", "Set x - 2 equal to 0.", ["x = -2", "This reverses the sign.", "x = 4", "The outside coefficient does not create a zero.", "x = -9", "That zero comes from the other factor."]),
("For f(x) = (x + 1)<sup>4</sup>, what is true about x = -1?", "It is a zero with even multiplicity.", "The exponent 4 is even.", ["It is not a zero.", "Substituting -1 makes the factor zero.", "It has odd multiplicity.", "The multiplicity is 4, which is even.", "It is the y-intercept.", "A zero describes an x-intercept."]),
("If a graph crosses the x-axis at x = 8, what multiplicity is most likely?", "odd multiplicity", "Crossing usually indicates odd multiplicity.", ["even multiplicity", "Even multiplicity usually touches and turns.", "no real zero", "Crossing means there is a real zero.", "undefined multiplicity", "Polynomial zeros have multiplicities."]),
("If f(x) = (x - 3)(x + 2)<sup>2</sup>, which zero usually touches and turns?", "x = -2", "The zero from (x + 2)<sup>2</sup> has even multiplicity.", ["x = 3", "This zero has multiplicity 1.", "x = 2", "This reverses the sign.", "x = -3", "This reverses the sign."]),
("How many real zeros are shown by f(x) = (x - 1)(x + 4)(x - 6)?", "3", "Each distinct linear factor gives one real zero.", ["1", "There are three distinct factors.", "2", "There are three linear factors.", "6", "The number 6 is one zero, not the count."]),
("Which factor would produce the zero x = -10?", "x + 10", "A factor x + 10 equals zero when x = -10.", ["x - 10", "This produces x = 10.", "10x", "This produces x = 0.", "x - 1", "This produces x = 1."]),
("For f(x) = (x - 2)<sup>3</sup>, what does the graph usually do at x = 2?", "crosses, possibly flattening", "Odd multiplicity 3 crosses and can appear flatter near the zero.", ["touches and turns sharply", "Even multiplicity usually touches and turns.", "has no x-intercept", "x = 2 is a real zero.", "has a vertical asymptote", "Polynomial functions do not have vertical asymptotes."]),
("Which zero has multiplicity 1 in f(x) = (x + 5)(x - 4)<sup>2</sup>?", "x = -5", "The factor x + 5 has exponent 1.", ["x = 4", "This zero has multiplicity 2.", "x = 5", "This reverses the sign.", "x = -4", "This reverses the sign."]),
("What does a repeated factor tell you about a polynomial graph?", "the multiplicity of a zero", "The exponent on the factor tells how many times the zero repeats.", ["the y-intercept only", "The y-intercept comes from f(0).", "the axis of symmetry always", "Higher-degree polynomials do not always have one axis.", "the slope of a line", "A polynomial factor is not line slope."]),
("Which expression has a zero at x = 0?", "f(x) = x(x - 3)", "The factor x equals zero when x = 0.", ["f(x) = (x + 3)(x - 1)", "The zeros are -3 and 1.", "f(x) = (x - 2)<sup>2</sup>", "The zero is 2.", "f(x) = x + 5", "The zero is -5."]),
("For f(x) = (x + 2)<sup>2</sup>(x - 7)<sup>3</sup>, which zero has odd multiplicity?", "x = 7", "The exponent 3 is odd.", ["x = -2", "This zero has even multiplicity.", "x = 2", "This reverses the sign.", "x = -7", "This reverses the sign."]),
("If f(x) = (x - 9)<sup>2</sup>, what is the x-intercept?", "(9, 0)", "The zero is x = 9, so the x-intercept is (9, 0).", ["(-9, 0)", "The sign is reversed.", "(0, 9)", "This is not an x-intercept form.", "(2, 0)", "The exponent is multiplicity."]),
("Which statement about f(x) = (x + 4)<sup>2</sup>(x - 1)<sup>2</sup> is true?", "Both zeros have even multiplicity.", "Both factors have exponent 2.", ["Both zeros have odd multiplicity.", "The exponents are even.", "Only x = 1 is even multiplicity.", "x = -4 also has exponent 2.", "There are no real zeros.", "Both factors give real zeros."]),
("A graph only touches the x-axis at x = -6. Which factor is most consistent?", "(x + 6)<sup>2</sup>", "Touching suggests even multiplicity, and x + 6 gives zero -6.", ["(x - 6)", "This gives zero 6 and odd multiplicity.", "(x + 6)", "This gives zero -6 but usually crosses.", "(x - 6)<sup>2</sup>", "This gives zero 6."]),
("Which factorization shows zeros x = -1 and x = 5?", "(x + 1)(x - 5)", "Each factor has the opposite sign of its zero.", ["(x - 1)(x + 5)", "This gives zeros 1 and -5.", "(x - 1)(x - 5)", "This gives zeros 1 and 5.", "(x + 1)(x + 5)", "This gives zeros -1 and -5."]),
("What is the multiplicity of x = 0 in f(x) = x<sup>5</sup>(x - 2)?", "5", "The factor x is raised to the fifth power.", ["0", "Zero is the root value.", "1", "The factor x - 2 has multiplicity 1.", "2", "This is another zero, not x = 0 multiplicity."]),
("Which zero would the graph usually cross at for f(x) = (x - 4)<sup>2</sup>(x + 8)?", "x = -8", "The factor x + 8 has multiplicity 1, which is odd.", ["x = 4", "This zero has even multiplicity.", "x = 8", "This reverses the sign.", "x = -4", "This reverses the sign."]),
("Which zero would the graph usually touch at for f(x) = (x + 3)<sup>4</sup>(x - 5)?", "x = -3", "The factor x + 3 has even multiplicity 4.", ["x = 5", "This zero has multiplicity 1.", "x = 3", "This reverses the sign.", "x = -5", "This reverses the sign."]),
("Why is x = 2 a zero of f(x) = (x - 2)(x + 1)?", "It makes one factor equal 0.", "Substituting x = 2 makes x - 2 equal 0, so the product is 0.", ["It makes both factors equal 0.", "Only x - 2 equals 0 at x = 2.", "It is the y-intercept.", "A zero is an x-value where output is 0.", "It is the leading coefficient.", "The leading coefficient is not identified by the zero."]),
]
write(root / "Lesson 04" / "ALG2_U02_L04_Quiz.gift", make("ALG2_U02_L04", support, l4_prompts))

l5 = [
("Which features are enough to begin sketching f(x) = -2(x + 1)(x - 4)?", "zeros and end behavior", "Zeros anchor the graph on the x-axis, and end behavior shows where the arms go.", ["axis of symmetry only", "Higher-degree polynomials may not have one axis of symmetry.", "y-intercept only", "One point is not enough to sketch the graph.", "constant term only", "The constant term alone does not show zeros or end behavior."]),
("For f(x) = (x - 3)<sup>2</sup>(x + 2), what happens at x = 3?", "the graph touches and turns", "The zero x = 3 has even multiplicity 2.", ["the graph crosses", "Crossing is typical of odd multiplicity.", "the graph has no x-intercept", "x = 3 is a real zero.", "the graph has a vertical asymptote", "Polynomial graphs do not have vertical asymptotes."]),
("For f(x) = (x + 5)(x - 1)<sup>2</sup>, where does the graph usually cross the x-axis?", "x = -5", "The factor x + 5 has multiplicity 1, so the graph usually crosses there.", ["x = 1", "That zero has even multiplicity and usually touches.", "x = 5", "This reverses the sign.", "x = -1", "This reverses the sign."]),
("What is the end behavior of f(x) = -x<sup>4</sup> + 6x<sup>2</sup>?", "both ends fall", "The leading term has even degree and a negative coefficient.", ["both ends rise", "That would require a positive leading coefficient.", "left falls, right rises", "That is positive odd-degree behavior.", "left rises, right falls", "That is negative odd-degree behavior."]),
("What point does the y-intercept help place on a polynomial sketch?", "where the graph crosses the y-axis", "The y-intercept is f(0), the output when x = 0.", ["where the graph crosses the x-axis", "x-intercepts come from zeros.", "where both ends go", "End behavior comes from degree and leading coefficient.", "where the graph has a vertical asymptote", "Polynomial functions do not have vertical asymptotes."]),
("Which graph behavior matches a positive cubic with zeros -2, 1, and 4?", "falls left and rises right", "A positive cubic has left end down and right end up.", ["rises left and falls right", "That is negative cubic behavior.", "both ends rise", "That is positive even-degree behavior.", "both ends fall", "That is negative even-degree behavior."]),
("For f(x) = x(x - 2)(x + 3), which point is the y-intercept?", "(0, 0)", "Since one factor is x, f(0) = 0.", ["(2, 0)", "This is an x-intercept.", "(-3, 0)", "This is an x-intercept.", "(0, -6)", "Substituting x = 0 gives 0."]),
("Which zero should be marked as a touch point for f(x) = (x + 4)<sup>2</sup>(x - 6)?", "x = -4", "The factor x + 4 is squared, so its zero has even multiplicity.", ["x = 6", "This zero has multiplicity 1 and usually crosses.", "x = 4", "This reverses the sign.", "x = -6", "This reverses the sign."]),
("When sketching f(x) = 3(x - 1)(x + 2)(x - 5), what should happen at each zero?", "the graph crosses at each zero", "Each factor has multiplicity 1, which is odd.", ["the graph touches at each zero", "Touching would require even multiplicity.", "the graph avoids the x-axis", "Real zeros are x-axis contacts.", "the graph has holes at each zero", "Polynomial graphs are continuous."]),
("Which statement helps sketch f(x) = (x - 2)<sup>2</sup>(x + 1)<sup>2</sup>?", "both zeros are touch points", "Both factors have even multiplicity.", ["both zeros are crossing points", "Crossing is typical of odd multiplicity.", "there are no x-intercepts", "Both factors give real zeros.", "only x = -1 is a zero", "x = 2 is also a zero."]),
("For f(x) = x<sup>3</sup> - 4x, which zeros help sketch the graph?", "x = -2, 0, and 2", "Factoring gives x(x - 2)(x + 2).", ["x = -4 and 4", "Those come from the constant but are not zeros.", "x = 0 only", "Factoring shows three zeros.", "x = -1, 0, and 1", "Only x = 0 from this list is correct."]),
("Which feature determines whether the far-right side rises or falls?", "leading term", "The leading term controls end behavior.", ["middle term", "Lower-degree terms do not control far-right behavior.", "constant term", "The constant shifts values but does not control the far end.", "number of terms", "Term count does not determine end behavior."]),
("For f(x) = -2(x + 3)(x - 1)<sup>2</sup>, what is the right-end behavior?", "falls right", "The degree is 3 and the leading coefficient is negative.", ["rises right", "That would match a positive odd-degree leading term.", "stays flat", "A cubic end does not stay flat.", "approaches 0", "This polynomial does not approach 0 on the right."]),
("What should be plotted from f(0) when sketching a polynomial?", "the y-intercept", "f(0) gives the graph point where x = 0.", ["the leading coefficient", "The leading coefficient comes from the highest-degree term.", "all x-intercepts", "Zeros come from solving f(x) = 0.", "the axis of symmetry", "Not every polynomial has one axis."]),
("Which factor form indicates the graph touches at x = 7?", "(x - 7)<sup>2</sup>", "The zero is 7 and the even exponent indicates a touch point.", ["(x + 7)", "This gives zero -7 and multiplicity 1.", "(x - 7)", "This gives zero 7 but usually crosses.", "(x + 7)<sup>3</sup>", "This gives zero -7 and odd multiplicity."]),
("For f(x) = 2(x - 4)(x + 1), what is the y-intercept?", "(0, -8)", "f(0) = 2(-4)(1) = -8.", ["(4, 0)", "This is an x-intercept.", "(-1, 0)", "This is an x-intercept.", "(0, 8)", "The product at x = 0 is negative."]),
("Which sketching step should come after finding zeros and multiplicities?", "use end behavior to shape the arms", "End behavior tells how the far left and far right should look.", ["ignore the leading coefficient", "The leading coefficient is needed for end behavior.", "draw a line through all zeros", "Polynomial graphs are not generally straight lines.", "remove repeated zeros", "Repeated zeros affect touch/cross behavior."]),
("A polynomial has zeros -3 and 2, both with odd multiplicity, and positive leading coefficient. What should the graph do at both zeros?", "cross the x-axis", "Odd multiplicity zeros usually cross the x-axis.", ["touch and turn", "That is typical of even multiplicity.", "create vertical asymptotes", "Polynomial graphs do not have vertical asymptotes.", "avoid the x-axis", "Zeros are points where the graph meets the x-axis."]),
("What graph behavior matches f(x) = (x + 2)<sup>4</sup>?", "touches at x = -2", "The even multiplicity zero causes the graph to touch and turn.", ["crosses at x = -2", "Crossing is typical of odd multiplicity.", "touches at x = 2", "The zero from x + 2 is -2.", "has no x-intercept", "The factor gives a real zero."]),
("Which feature is missing if you know only the zeros of a polynomial?", "end behavior", "Zeros do not tell whether the graph rises or falls on the ends.", ["x-intercepts", "Zeros give x-intercepts.", "root values", "Zeros and roots are related values.", "where f(x) = 0", "Zeros are where f(x) = 0."]),
("For f(x) = -x(x - 5)<sup>2</sup>, what happens at x = 5?", "the graph touches and turns", "The zero x = 5 has even multiplicity 2.", ["the graph crosses", "Crossing is typical of odd multiplicity.", "the graph is undefined", "Polynomial functions are defined at x = 5.", "the graph has no contact with the x-axis", "x = 5 is a zero."]),
("Which polynomial would have both ends rising and touch at x = 1?", "(x - 1)<sup>2</sup>(x + 3)<sup>2</sup>", "This has even degree, positive leading coefficient, and even multiplicity at x = 1.", ["-(x - 1)<sup>2</sup>", "This falls on both ends.", "(x - 1)(x + 3)", "This has odd multiplicity at x = 1.", "-(x - 1)(x + 3)<sup>2</sup>", "This has odd degree and negative leading behavior."]),
("Which statement is most useful when sketching f(x) = x<sup>4</sup> - 16?", "It is even degree with positive leading coefficient.", "That tells both ends rise before using intercepts for the middle behavior.", ["It is odd degree with positive leading coefficient.", "The highest exponent is 4, which is even.", "It has no x-intercepts.", "x<sup>4</sup> - 16 = 0 has real solutions.", "Its leading coefficient is -16.", "The leading coefficient is 1."]),
("For f(x) = (x + 2)(x - 1)(x - 3), which x-values should be marked as intercepts?", "x = -2, 1, and 3", "Each linear factor gives an x-intercept by setting it equal to zero.", ["x = 2, -1, and -3", "These reverse all the signs.", "x = -2 only", "There are three linear factors.", "x = 0, 1, and 3", "x = 0 is not a zero of this form."]),
("What should a sketch do at a zero with multiplicity 4?", "touch and turn, often flatter", "Multiplicity 4 is even, so the graph touches, and higher multiplicity can flatten.", ["cross sharply", "Crossing is typical of odd multiplicity.", "create a hole", "Polynomial graphs are continuous.", "create a vertical asymptote", "Polynomials do not have vertical asymptotes."]),
]
write(root / "Lesson 05" / "ALG2_U02_L05_Quiz.gift", make("ALG2_U02_L05", support, l5))

l6 = [
("A polynomial height model has H(0) = 6. What does 6 represent?", "the initial height", "H(0) is the output at time 0, so it represents the starting height.", ["the landing time", "Landing time is usually a zero.", "the maximum height", "A maximum is a vertex or peak value.", "the degree", "Function output does not identify degree."]),
("If P(t) models profit and P(t) = 0, what does t represent?", "a break-even time", "Profit equal to zero means revenue and cost are equal.", ["maximum profit", "Maximum profit occurs at a peak.", "initial profit", "Initial profit is P(0).", "the degree of the model", "The input t does not identify degree."]),
("A ball height model has zeros at t = 0 and t = 5. What is a reasonable domain?", "0 <= t <= 5", "The model is physically meaningful from launch until landing.", ["all real numbers", "Negative time and time after landing may not fit.", "t < 0", "Negative time is not meaningful.", "t >= 5 only", "That begins at landing."]),
("A revenue model reaches a maximum at x = 40. What does x = 40 represent?", "the input that gives greatest revenue", "The x-coordinate of the maximum gives the input where the peak occurs.", ["the greatest revenue amount", "The y-coordinate gives the maximum revenue.", "a zero of the model", "A zero is where output is 0.", "the initial revenue", "Initial revenue is the output when x = 0."]),
("Why might a negative solution be rejected in a length model?", "lengths cannot be negative", "A physical length must be zero or positive.", ["negative numbers are never solutions", "Negative numbers can solve equations.", "all models use positive coefficients", "Coefficient signs do not decide valid context values.", "it must be the y-intercept", "A rejected solution is not necessarily an intercept."]),
("If C(x) models cost, what does C(0) usually represent?", "fixed or starting cost", "The output at x = 0 describes the cost before any units are produced.", ["number of units sold", "Units are usually the input x.", "profit at break-even", "Break-even involves profit or revenue equaling cost.", "the largest possible cost", "C(0) is not necessarily a maximum."]),
("A polynomial model has an x-intercept at 12 months. What could that mean?", "the modeled quantity is 0 at 12 months", "An x-intercept occurs where the output equals 0.", ["the initial amount is 12", "Initial amount is the output at input 0.", "the maximum amount is 12", "A maximum is a peak output.", "the degree is 12", "An intercept location does not identify degree."]),
("Which value should be used to interpret the starting amount in A(t)?", "A(0)", "The starting amount is the output when the input time is 0.", ["A(1)", "This is the amount after one time unit.", "t = 0 only", "The full output A(0) gives the amount.", "the leading coefficient only", "The leading coefficient does not directly give the starting amount."]),
("A model for water volume has V(3) = 0. What does this likely mean?", "the container is empty at time 3", "A zero output means the modeled volume is 0.", ["the container starts with 3 units", "Starting volume would be V(0).", "the maximum volume is 3", "A maximum would be a peak output.", "the model has degree 3", "The input value does not identify degree."]),
("If a model output is negative for a population, how should it be treated in context?", "as not meaningful for population", "A real population count cannot be negative.", ["as the exact population", "Negative population is not physically meaningful.", "as the degree of the polynomial", "Output sign does not identify degree.", "as a required maximum", "Negative output is not automatically a maximum."]),
("What does the y-intercept of a polynomial model often represent?", "initial value", "The y-intercept occurs when the input is 0.", ["final value always", "Final value depends on the context and domain.", "a horizontal asymptote", "Polynomial functions do not have horizontal asymptotes here.", "the largest zero", "The y-intercept is an output, not an x-zero."]),
("A polynomial area model gives A(x) = 0 at x = 4. What does x = 4 likely represent?", "a boundary value where area becomes zero", "Zeros can mark endpoints or nonphysical boundaries in context.", ["the maximum area", "A zero is not a maximum area.", "the starting area", "Starting area is A(0).", "the leading coefficient", "The input x = 4 is not a coefficient."]),
("Why is context important when solving polynomial models?", "some algebraic solutions may not make sense physically", "Context determines which roots or intervals are meaningful.", ["it changes the rules of factoring", "Factoring rules stay the same.", "it removes the need to check units", "Units are part of contextual interpretation.", "it makes every solution positive", "Context may reject solutions, but not force all positive."]),
("If a height model opens downward, what key feature often gives maximum height?", "the vertex", "The peak of a downward-opening model occurs at the vertex.", ["the smallest zero", "A zero gives ground contact, not maximum height.", "the y-intercept always", "Initial height is not always the maximum.", "the leading coefficient alone", "It indicates direction, not exact maximum."]),
("A polynomial model is valid only for 0 <= t <= 10. Which input should be rejected?", "t = 12", "This input is outside the stated domain.", ["t = 0", "The domain includes 0.", "t = 5", "The domain includes values between 0 and 10.", "t = 10", "The domain includes 10."]),
("If R(x) - C(x) = 0 in a business model, what does that represent?", "break-even", "Revenue minus cost equal to 0 means profit is 0.", ["maximum loss", "A zero difference is not a maximum loss.", "initial cost", "Initial cost is C(0).", "domain restriction", "The equation describes equality, not domain."]),
("What does an increasing interval tell you in a model?", "where the output is rising", "An increasing interval shows input values where the modeled quantity grows.", ["where the output equals 0", "Zeros describe where output is 0.", "where input is not allowed", "Domain restrictions describe allowed inputs.", "where the model must be linear", "A polynomial can increase without being linear."]),
("A polynomial temperature model has a local minimum. What does that feature represent?", "a low point over the modeled interval", "A local minimum is a point where nearby outputs are higher.", ["the initial temperature always", "Initial temperature is T(0).", "a zero always", "A minimum may or may not be output 0.", "the degree of the polynomial", "A feature point does not identify degree."]),
("Which interpretation matches f(2) = 15 in context?", "when the input is 2, the output is 15", "Function notation pairs an input with its output.", ["when the output is 2, the input is 15", "That reverses input and output.", "the model has two zeros and degree 15", "Function notation does not state zeros or degree.", "15 is always the maximum", "One output value is not necessarily a maximum."]),
("If a polynomial model has zeros at 1 and 9, what interval might represent positive output between zeros?", "1 < x < 9", "If the graph is above the x-axis between zeros, that interval gives positive output.", ["x < 1 or x > 9", "That describes outside the zeros.", "x = 1 and x = 9 only", "At the zeros, output is 0.", "all real numbers", "Zeros divide intervals where sign may change."]),
("Why should units be included when interpreting a model answer?", "units explain what the number measures", "A value without units can be mathematically correct but unclear in context.", ["units change the algebraic solution", "Units do not change the arithmetic result.", "units replace the need for a graph", "Graphs and units answer different parts.", "units identify the leading coefficient", "Units do not directly identify it."]),
("A model predicts maximum height 64 at t = 2. What is 64?", "the maximum output", "The y-value at the peak is the maximum height.", ["the time of maximum height", "That is t = 2.", "a zero of the model", "A zero would have output 0.", "the domain endpoint", "64 is an output value."]),
("Which question is answered by finding x-intercepts in a context model?", "when the output is zero", "x-intercepts occur where the function value is 0.", ["what the initial value is", "Initial value is found at x = 0.", "what the leading coefficient is", "Leading coefficient comes from the equation.", "whether the graph is continuous", "Intercepts do not answer that directly."]),
("If a model gives two real zeros but only one is in the domain, what should happen?", "use only the zero in the domain", "Context restricts which algebraic solutions are meaningful.", ["use both zeros automatically", "A solution outside the domain should be rejected.", "reject the whole model", "One invalid solution does not invalidate the entire model.", "change the equation", "The equation is not changed by context."]),
("What does a negative leading coefficient often suggest for the right end of an odd-degree model?", "the output eventually decreases", "Odd degree with negative leading coefficient falls to the right.", ["the output eventually increases", "That would match a positive odd-degree leading coefficient.", "the model has no zeros", "End behavior does not determine whether zeros exist.", "the initial value is negative", "Initial value depends on f(0)."]),
]
write(root / "Lesson 06" / "ALG2_U02_L06_Quiz.gift", make("ALG2_U02_L06", application, l6))

l7 = [
("Solve x<sup>2</sup> - 6x + 8 = 0.", "x = 2 and x = 4", "Factoring gives (x - 2)(x - 4) = 0.", ["x = -2 and x = -4", "These reverse the signs of the factors.", "x = 6 and x = 8", "These are coefficient/constant values, not zeros.", "x = 0 and x = 8", "This uses the constant but misses the factors."]),
("Solve x<sup>2</sup> + x - 12 = 0.", "x = -4 and x = 3", "Factoring gives (x + 4)(x - 3) = 0.", ["x = 4 and x = -3", "These signs are reversed.", "x = 1 and x = -12", "These use coefficient and constant values.", "x = 0 and x = -12", "These do not make the quadratic equal 0."]),
("Which solves x<sup>2</sup> - 16 > 0?", "x < -4 or x > 4", "The upward-opening graph is above the x-axis outside the zeros.", ["-4 < x < 4", "Between the zeros, the expression is negative.", "-4 <= x <= 4", "This includes the wrong interval.", "all real numbers", "The expression is negative between -4 and 4."]),
("Which solves x<sup>2</sup> - 25 <= 0?", "-5 <= x <= 5", "The graph is on or below the x-axis between and including the zeros.", ["x < -5 or x > 5", "That is where the graph is above the x-axis.", "x <= -5 or x >= 5", "This includes outside values instead of the middle.", "all real numbers", "Values far from 0 make the expression positive."]),
("For y < x<sup>2</sup> - 3, which statement is true?", "Use a dashed boundary and shade below.", "Strict inequality uses a dashed boundary, and y less than means below.", ["Use a solid boundary and shade below.", "Solid would include equality.", "Use a dashed boundary and shade above.", "The boundary style is right, but shading is wrong.", "Use a solid boundary and shade above.", "Both boundary style and shading are wrong."]),
("For y >= -x<sup>2</sup> + 1, which statement is true?", "Use a solid boundary and shade above.", "The symbol includes equality, and y greater than means above.", ["Use a dashed boundary and shade above.", "The shading is right, but >= requires solid.", "Use a solid boundary and shade below.", "The boundary is right, but shading is wrong.", "Use no boundary.", "A two-variable inequality needs a boundary."]),
("Solve x<sup>2</sup> - 9 = 0.", "x = -3 and x = 3", "This is a difference of squares.", ["x = 9 and x = -9", "These come before taking square roots.", "x = 0 and x = 9", "These do not satisfy the equation.", "x = 3 only", "Both positive and negative roots solve it."]),
("Solve x<sup>2</sup> + 2x - 15 = 0.", "x = -5 and x = 3", "Factoring gives (x + 5)(x - 3) = 0.", ["x = 5 and x = -3", "These signs are reversed.", "x = -2 and x = 15", "These use coefficients, not zeros.", "x = 0 and x = -15", "These are not factor roots."]),
("Which solves x<sup>2</sup> - 4 >= 0?", "x <= -2 or x >= 2", "The graph is on or above the x-axis outside the zeros and includes them.", ["-2 < x < 2", "That interval gives negative values.", "-2 <= x <= 2", "That is where the expression is on or below zero.", "all real numbers", "Values between -2 and 2 do not work."]),
("Which solves x<sup>2</sup> - 1 < 0?", "-1 < x < 1", "The graph is below the x-axis between the zeros, excluding endpoints.", ["x < -1 or x > 1", "Outside the zeros, the expression is positive.", "-1 <= x <= 1", "The endpoints make the expression 0.", "all real numbers", "Outside values do not satisfy the inequality."]),
("For y <= x<sup>2</sup> + 4, how should the boundary be drawn?", "solid", "The symbol <= includes equality.", ["dashed", "Dashed is used for strict inequalities.", "vertical", "The boundary is a parabola.", "not graphed", "A boundary is needed."]),
("For y > -2x<sup>2</sup> + 5, where should the solution region be shaded?", "above the parabola", "y greater than means points above the boundary.", ["below the parabola", "Below would match y less than.", "only on the parabola", "Strict inequality excludes the boundary.", "outside the zeros", "That describes a one-variable interval."]),
("Solve x<sup>2</sup> - 10x + 21 = 0.", "x = 3 and x = 7", "Factoring gives (x - 3)(x - 7) = 0.", ["x = -3 and x = -7", "These signs are reversed.", "x = 10 and x = 21", "These are coefficient/constant values.", "x = 0 and x = 21", "These do not make the equation true."]),
("Solve x<sup>2</sup> + 6x + 8 = 0.", "x = -2 and x = -4", "Factoring gives (x + 2)(x + 4) = 0.", ["x = 2 and x = 4", "These signs are reversed.", "x = 6 and x = 8", "These are not roots.", "x = 0 and x = 8", "These do not satisfy the equation."]),
("Which solves -x<sup>2</sup> + 4 >= 0?", "-2 <= x <= 2", "The downward-opening graph is on or above the x-axis between the zeros.", ["x <= -2 or x >= 2", "Outside the zeros, the expression is negative.", "-2 < x < 2", "This misses endpoints included by >=.", "all real numbers", "Values outside the interval do not work."]),
("Which solves -x<sup>2</sup> + 9 < 0?", "x < -3 or x > 3", "The downward-opening graph is below the x-axis outside the zeros.", ["-3 < x < 3", "Between the zeros, the expression is positive.", "-3 <= x <= 3", "This includes values that are not negative.", "all real numbers", "Values between -3 and 3 do not work."]),
("For y = x<sup>2</sup> - 2 and y = 2, what equation finds intersection x-values?", "x<sup>2</sup> - 2 = 2", "Set the two y-values equal to find where the graphs meet.", ["x<sup>2</sup> - 2 = 0", "That finds x-intercepts of the parabola.", "x<sup>2</sup> = -2", "This does not set the functions equal correctly.", "2x = x<sup>2</sup> - 2", "This uses y = 2x, not y = 2."]),
("For y < -x<sup>2</sup> + 6, which boundary and shading are correct?", "dashed boundary, shade below", "Strict less-than excludes the boundary and shades below it.", ["solid boundary, shade below", "The shading is right, but strict inequality needs dashed.", "dashed boundary, shade above", "The boundary style is right, but shading is wrong.", "solid boundary, shade above", "Both boundary and shading are wrong."]),
("Solve x<sup>2</sup> + 5x = 0.", "x = 0 and x = -5", "Factoring gives x(x + 5) = 0.", ["x = 5 only", "This reverses the sign and misses x = 0.", "x = -5 only", "This misses the factor x = 0.", "x = 0 and x = 5", "The sign of the second solution is reversed."]),
("Solve 2x<sup>2</sup> - 8 = 0.", "x = -2 and x = 2", "Divide by 2 to get x<sup>2</sup> = 4.", ["x = 4 and x = -4", "These come before square rooting.", "x = 2 only", "Both positive and negative roots solve it.", "x = 0 and x = 8", "These do not satisfy the equation."]),
("Which interval solves (x - 1)(x + 3) <= 0?", "-3 <= x <= 1", "The product is nonpositive between the zeros and includes endpoints.", ["x <= -3 or x >= 1", "That is where the product is nonnegative.", "-3 < x < 1", "This misses endpoints.", "all real numbers", "The product is positive outside the zeros."]),
("Which interval solves (x - 4)(x + 2) > 0?", "x < -2 or x > 4", "The product is positive outside the zeros.", ["-2 < x < 4", "Between the zeros the product is negative.", "-2 <= x <= 4", "This includes the nonpositive interval.", "all real numbers", "Values between -2 and 4 do not work."]),
("For y >= x<sup>2</sup> - 1, which point should be in the solution region?", "(0, 0)", "At x = 0, the boundary value is -1, and 0 >= -1 is true.", ["(0, -2)", "-2 is below -1.", "(2, 0)", "At x = 2, the boundary is 3.", "(1, -2)", "At x = 1, the boundary is 0."]),
("For y < x<sup>2</sup>, which point is a solution?", "(2, 3)", "At x = 2, x<sup>2</sup> = 4 and 3 < 4.", ["(2, 5)", "5 is greater than 4.", "(0, 0)", "0 < 0 is false because the inequality is strict.", "(-1, 2)", "At x = -1, 2 < 1 is false."]),
("Which equation finds where x<sup>2</sup> - 4x and 0 intersect?", "x<sup>2</sup> - 4x = 0", "Set the quadratic equal to the x-axis value 0.", ["x<sup>2</sup> = 4", "This changes the expression.", "x - 4 = 0 only", "This misses the factor x.", "x<sup>2</sup> + 4x = 0", "This changes the sign."]),
]
write(root / "Lesson 07" / "ALG2_U02_L07_Quiz.gift", make("ALG2_U02_L07", std7, l7))

ua = [
("ALG2_U02_UA_Q01","MLA.A2.PF.3","What is the degree of f(x) = 5x<sup>2</sup> - 3x + 8?","2","The highest exponent is 2.",["5","This is the leading coefficient, not the degree.","3","This is part of the linear coefficient.","8","This is the constant term."]),
("ALG2_U02_UA_Q02","MLA.A2.PF.4","A quadratic has vertex (-2, 7) and opens downward. What is its maximum value?","7","The y-coordinate of the vertex is the maximum when the graph opens downward.",["-2","This is the x-coordinate where the maximum occurs.","2","This changes the sign of the vertex x-coordinate.","-7","This changes the sign of the output value."]),
("ALG2_U02_UA_Q03","MLA.A2.PF.8","Which describes f(x) = -3x<sup>5</sup> + 2x?","rises left, falls right","Odd degree with negative leading coefficient rises left and falls right.",["falls left, rises right","That would require a positive leading coefficient.","both ends rise","Both ends rising requires even degree with positive leading coefficient.","both ends fall","Both ends falling requires even degree with negative leading coefficient."]),
("ALG2_U02_UA_Q04",support,"For f(x) = (x - 2)<sup>2</sup>(x + 5), which zero has even multiplicity?","x = 2","The repeated factor (x - 2)<sup>2</sup> gives zero x = 2 with even multiplicity.",["x = -5","This zero has multiplicity 1.","x = 5","This reverses the sign of x + 5.","x = -2","This reverses the sign of x - 2."]),
("ALG2_U02_UA_Q05",support,"Which feature helps sketch f(x) = (x + 1)(x - 4)?","zeros at -1 and 4","Each factor gives a zero by setting it equal to 0.",["zeros at 1 and -4","These signs are reversed.","vertex at (-1, 4)","The factors do not directly give this vertex.","no x-intercepts","The factored form shows two x-intercepts."]),
("ALG2_U02_UA_Q06",application,"A model P(t) has P(0) = 120. What does 120 represent?","the initial output","P(0) is the y-intercept or starting output.",["a zero","A zero is an input where the output is 0.","the degree","The output at 0 does not identify degree.","the end behavior","End behavior describes very large inputs."]),
("ALG2_U02_UA_Q07","MLA.A2.PF.2","Solve x<sup>2</sup> - 1 >= 0.","x <= -1 or x >= 1","The graph is on or above the x-axis outside the zeros and includes them.",["-1 <= x <= 1","That interval gives values on or below the x-axis.","-1 < x < 1","This excludes endpoints and chooses the wrong interval.","all real numbers","Values between -1 and 1 make the expression negative."]),
("ALG2_U02_UA_Q08","MLA.A2.PF.5","For y < x<sup>2</sup> + 1, the boundary is","dashed","Strict inequality excludes equality, so the boundary is dashed.",["solid","Solid would include equality.","vertical","The boundary is a parabola.","not graphed","A boundary graph is needed."]),
("ALG2_U02_UA_Q09","MLA.A2.PF.6","For y <= -x<sup>2</sup> + 4, shade","below the parabola","The symbol <= means y-values less than or equal to the boundary.",["above the parabola","Above would match a greater-than inequality.","only the vertex","The solution is a region, not one point.","outside the zeros","That describes an interval, not a two-variable region."]),
("ALG2_U02_UA_Q10","MLA.A2.PF.3","Which expression is a quadratic polynomial?","3x<sup>2</sup> - 5x + 1","A quadratic polynomial has degree 2.",["4x<sup>3</sup> - 1","This is cubic.","7x - 2","This is linear.","5","This is constant."]),
("ALG2_U02_UA_Q11","MLA.A2.PF.4","For f(x) = (x - 3)<sup>2</sup> - 5, what is the vertex?","(3, -5)","Vertex form (x - h)<sup>2</sup> + k gives vertex (h, k).",["(-3, -5)","The sign inside the parentheses is reversed.","(3, 5)","The k-value is -5.","(-5, 3)","This switches the coordinates."]),
("ALG2_U02_UA_Q12","MLA.A2.PF.8","What is the end behavior of f(x) = 4x<sup>6</sup> - 2x?","both ends rise","Even degree with positive leading coefficient rises on both ends.",["both ends fall","That would require a negative leading coefficient.","left falls, right rises","That is positive odd-degree behavior.","left rises, right falls","That is negative odd-degree behavior."]),
("ALG2_U02_UA_Q13",support,"For f(x) = (x + 3)<sup>3</sup>(x - 1), which zero has multiplicity 3?","x = -3","The factor x + 3 has exponent 3.",["x = 3","This reverses the sign.","x = 1","This zero has multiplicity 1.","x = -1","This reverses the sign of x - 1."]),
("ALG2_U02_UA_Q14",support,"What does a zero with odd multiplicity usually do on a graph?","crosses the x-axis","Odd multiplicity usually changes sign at the zero.",["touches and turns","That is typical of even multiplicity.","creates a hole","Polynomial graphs are continuous.","creates a vertical asymptote","Polynomial graphs do not have vertical asymptotes."]),
("ALG2_U02_UA_Q15",application,"A height model has zeros at t = 0 and t = 6. What does t = 6 likely represent?","landing time","A zero height after launch often represents when the object returns to the ground.",["initial height","Initial height is H(0).","maximum height","Maximum height occurs at the vertex.","the degree","A zero does not identify degree."]),
("ALG2_U02_UA_Q16","MLA.A2.PF.2","Solve x<sup>2</sup> - 9 < 0.","-3 < x < 3","The upward-opening graph is below the x-axis between the zeros, excluding endpoints.",["x < -3 or x > 3","That is where the graph is above the x-axis.","-3 <= x <= 3","This includes endpoints where the value is 0.","all real numbers","Outside the interval, the expression is positive."]),
("ALG2_U02_UA_Q17","MLA.A2.PF.5","For y >= x<sup>2</sup> - 2, the boundary should be","solid","The symbol >= includes equality, so boundary points are included.",["dashed","Dashed is used for strict inequalities.","horizontal","The boundary is a parabola.","removed","The boundary is part of the graph."]),
("ALG2_U02_UA_Q18","MLA.A2.PF.6","For y > x<sup>2</sup> - 5, shade","above the parabola","y greater than means points with y-values above the boundary.",["below the parabola","Below matches y less than.","on the parabola only","Strict inequality excludes the boundary.","inside the zeros only","This is a two-variable region."]),
("ALG2_U02_UA_Q19","MLA.A2.PF.3","What is the leading coefficient of f(x) = -6x<sup>2</sup> + x - 4?","-6","The leading coefficient belongs to the highest-degree term.",["2","This is the degree.","1","This is the coefficient of the linear term.","-4","This is the constant term."]),
("ALG2_U02_UA_Q20","MLA.A2.PF.4","What is the axis of symmetry for f(x) = (x + 4)<sup>2</sup> + 9?","x = -4","The axis of symmetry passes through the vertex x-coordinate.",["x = 4","The sign inside the parentheses is reversed.","y = 9","This is a horizontal line.","x = 9","The y-coordinate is not the axis value."]),
("ALG2_U02_UA_Q21","MLA.A2.PF.8","Which polynomial has both ends falling?","-2x<sup>4</sup> + 3","Even degree with a negative leading coefficient falls on both ends.",["2x<sup>4</sup> - 3","This rises on both ends.","2x<sup>3</sup> - 3","Odd degree has opposite end behavior.","-2x<sup>3</sup> + 3","Odd degree has opposite end behavior."]),
("ALG2_U02_UA_Q22",support,"Which factor gives the zero x = 8?","x - 8","Setting x - 8 = 0 gives x = 8.",["x + 8","This gives x = -8.","8x","This gives x = 0.","x - 1","This gives x = 1."]),
("ALG2_U02_UA_Q23",support,"For f(x) = (x - 6)<sup>2</sup>, what is the x-intercept?","(6, 0)","The zero is x = 6, so the x-intercept is (6, 0).",["(-6, 0)","This reverses the sign.","(0, 6)","This is not an x-intercept.","(2, 0)","The exponent gives multiplicity."]),
("ALG2_U02_UA_Q24",application,"If a model gives a negative time solution, what should usually happen?","reject it in the context","Negative time is usually not meaningful for real elapsed time.",["keep it automatically","Algebraic solutions must be checked against context.","make it positive","Changing the sign changes the solution.","use it as the maximum","A negative input is not automatically a maximum."]),
("ALG2_U02_UA_Q25","MLA.A2.PF.2","Solve x<sup>2</sup> + 5x + 6 = 0.","x = -2 and x = -3","Factoring gives (x + 2)(x + 3) = 0.",["x = 2 and x = 3","These signs are reversed.","x = 5 and x = 6","These are coefficient and constant values.","x = 0 and x = 6","These do not satisfy the equation."]),
("ALG2_U02_UA_Q26","MLA.A2.PF.5","For y <= -x<sup>2</sup> + 3, which boundary is correct?","solid parabola","The symbol <= includes equality, and the boundary is a parabola.",["dashed parabola","Dashed would mean equality is not included.","solid line","The boundary is not linear.","no boundary","A boundary is required."]),
("ALG2_U02_UA_Q27","MLA.A2.PF.6","For y < -x<sup>2</sup> + 1, shade","below the parabola","y less than means points below the boundary.",["above the parabola","Above would match y greater than.","only on the parabola","Strict inequality excludes boundary points.","left of the y-axis","The inequality describes vertical shading relative to the curve."]),
("ALG2_U02_UA_Q28","MLA.A2.PF.3","Which value is f(0) for f(x) = x<sup>2</sup> - 5x + 6?","6","Substituting x = 0 leaves the constant term 6.",["0","The input is 0, but the output is 6.","-5","This is the linear coefficient.","1","This is the coefficient of x<sup>2</sup>."]),
("ALG2_U02_UA_Q29","MLA.A2.PF.4","A quadratic opens upward and has vertex (1, -4). What is its minimum value?","-4","For an upward-opening parabola, the vertex y-coordinate is the minimum.",["1","This is the x-coordinate where the minimum occurs.","4","This changes the sign.","-1","This uses the wrong coordinate."]),
("ALG2_U02_UA_Q30","MLA.A2.PF.8","Which leading term gives left end down and right end up?","5x<sup>7</sup>","Positive odd-degree leading terms fall left and rise right.",["-5x<sup>7</sup>","This rises left and falls right.","5x<sup>8</sup>","This rises on both ends.","-5x<sup>8</sup>","This falls on both ends."]),
("ALG2_U02_UA_Q31",support,"If a graph touches and turns at x = -2, what multiplicity is most likely?","even multiplicity","Touching and turning is typical of even multiplicity.",["odd multiplicity","Odd multiplicity usually crosses.","no multiplicity","A real zero has a multiplicity.","negative multiplicity","Multiplicity is a positive integer."]),
("ALG2_U02_UA_Q32",support,"Which zeros come from f(x) = x(x - 5)(x + 4)?","x = 0, 5, and -4","Set each factor equal to zero.",["x = 0, -5, and 4","The signs of the last two zeros are reversed.","x = 5 and -4 only","The factor x gives zero 0 too.","x = 1, 5, and 4","The coefficient of x is not a zero."]),
("ALG2_U02_UA_Q33",application,"A model has maximum output 80 at x = 3. What does 80 represent?","the greatest modeled output","The y-value at the maximum point is the maximum output.",["the input where maximum occurs","That is x = 3.","a zero of the model","A zero has output 0.","the starting value","Starting value is f(0)."]),
("ALG2_U02_UA_Q34","MLA.A2.PF.2","Which solves (x - 2)(x + 4) >= 0?","x <= -4 or x >= 2","The product is nonnegative outside the zeros and includes endpoints.",["-4 <= x <= 2","That interval gives nonpositive values.","-4 < x < 2","This is the wrong interval and excludes endpoints.","all real numbers","Between the zeros the product is negative."]),
("ALG2_U02_UA_Q35","MLA.A2.PF.5","For y > x<sup>2</sup> + 2, is the boundary included?","No, because the inequality is strict.","The symbol > does not include equality.",["Yes, because it is a parabola.","Graph type does not decide boundary inclusion.","Yes, because y is positive.","The sign of y does not decide boundary inclusion.","No, because all parabolas are dashed.","Only strict inequalities use dashed boundaries."]),
("ALG2_U02_UA_Q36","MLA.A2.PF.6","Which point satisfies y >= x<sup>2</sup> - 1?","(0, 0)","At x = 0, the boundary value is -1 and 0 >= -1 is true.",["(0, -2)","-2 is below -1.","(2, 0)","At x = 2, the boundary is 3.","(1, -2)","At x = 1, the boundary is 0."]),
("ALG2_U02_UA_Q37","MLA.A2.PF.3","Which function is written in factored form?","f(x) = (x - 2)(x + 5)","Factored form shows a product of factors.",["f(x) = x<sup>2</sup> + 3x - 10","This is standard form.","f(x) = (x - 1)<sup>2</sup> + 4","This is vertex form.","f(x) = 2x + 5","This is linear form."]),
("ALG2_U02_UA_Q38","MLA.A2.PF.4","For f(x) = x<sup>2</sup> - 4x + 3, what are the x-intercepts?","(1, 0) and (3, 0)","Factoring gives (x - 1)(x - 3).",["(-1, 0) and (-3, 0)","These signs are reversed.","(0, 1) and (0, 3)","These are not x-intercepts.","(4, 0) and (3, 0)","The coefficient 4 is not a zero."]),
("ALG2_U02_UA_Q39","MLA.A2.PF.8","What controls the end behavior of f(x) = -2x<sup>6</sup> + 9x<sup>2</sup> - 1?","-2x<sup>6</sup>","The highest-degree term dominates.",["9x<sup>2</sup>","This is a lower-degree term.","-1","The constant does not control end behavior.","all terms equally","The leading term controls end behavior."]),
("ALG2_U02_UA_Q40","Unit 2 standards synthesis; no new primary MLA standard","A graph rises on both ends and touches the x-axis at x = 4. Which factor could explain the touch point?","(x - 4)<sup>2</sup>","The factor gives zero 4 and even multiplicity, so it touches.",["(x + 4)<sup>2</sup>","This gives zero -4.","(x - 4)","This gives zero 4 but usually crosses.","(x + 4)","This gives zero -4 and usually crosses."]),
]
ua_items = [q(qid, std, prompt, correct, cfb, wrongs, i % 4) for i, (qid, std, prompt, correct, cfb, wrongs) in enumerate(ua)]
write(root / "Lesson 08" / "ALG2_U02_UnitAssessment.gift", ua_items)

replacements = {
root / "Pretest" / "ALG2_U02_Pretest.gift": {
"=2 #Correct. The highest exponent is 2.": "=2 #Correct. The highest exponent is 2, so this quadratic has degree 2 rather than using a coefficient or constant.",
"=Zeros at x = -2 and x = 5 #Correct. Each factor gives an x-intercept.": "=Zeros at x = -2 and x = 5 #Correct. Setting x + 2 = 0 and x - 5 = 0 gives the two x-intercepts for the sketch.",
},
root / "Lesson 05" / "ALG2_U02_L05_GuidedPractice.gift": {
"=x = 3 #Correct. The repeated factor has even multiplicity.": "=x = 3 #Correct. The repeated factor (x - 3)<sup>2</sup> gives zero x = 3, and even multiplicity makes the graph touch there.",
"=x = -4 and x = 2 #Correct. Set each factor equal to 0.": "=x = -4 and x = 2 #Correct. Solving x + 4 = 0 and x - 2 = 0 gives the zeros that anchor the sketch.",
"=degree and leading coefficient #Correct. These determine end behavior.": "=degree and leading coefficient #Correct. The leading term uses both degree and leading coefficient to show how the graph behaves on the far left and far right.",
"=the graph crosses #Correct. Odd multiplicity usually crosses.": "=the graph crosses #Correct. Odd multiplicity usually means the sign changes at the zero, so the graph crosses the x-axis.",
},
root / "Lesson 06" / "ALG2_U02_L06_GuidedPractice.gift": {
"=initial height #Correct. H(0) is the starting output.": "=initial height #Correct. H(0) is the output when time is 0, so it represents the starting height in the model.",
"=landing time #Correct. A zero height often represents hitting the ground.": "=landing time #Correct. A zero of a height model means the height is 0, which often represents when the object reaches the ground.",
"=the time of maximum height #Correct. The vertex gives the peak.": "=the time of maximum height #Correct. In a downward-opening height model, the vertex gives the peak, and its x-coordinate gives when the peak occurs.",
"=break-even point #Correct. Profit equal to zero means revenue and cost are equal.": "=break-even point #Correct. Profit equal to zero means revenue and cost are equal, so the model is at break-even.",
"=physical lengths must be real numbers #Correct. Complex values do not represent real measurements.": "=physical lengths must be real numbers #Correct. A complex value can be an algebraic solution, but it cannot represent an actual physical length.",
},
}
for path, reps in replacements.items():
    text = path.read_text(encoding="utf-8")
    for old, new in reps.items():
        text = text.replace(old, new)
    path.write_text(text, encoding="utf-8")
