$ErrorActionPreference = 'Stop'

function Box($title,$body,$color='#2563eb',$bg='#e8f4ff') {
  return "<div style=""font-family: Arial, Helvetica, sans-serif; font-size: 18px; line-height: 1.75; color: #1f2933; max-width: 980px; margin: 0 auto 22px auto; border: 1px solid #d1d5db; border-radius: 10px; padding: 22px; background: $bg; border-left: 6px solid $color;""><h2 style=""font-size: 24px; margin-top: 0;"">$title</h2>$body</div>"
}
function Header($unit,$lesson,$page) {
  return "<div style=""font-family: Arial, Helvetica, sans-serif; font-size: 18px; line-height: 1.75; color: #ffffff; max-width: 980px; margin: 0 auto 18px auto; display: flex; justify-content: space-between; align-items: center; gap: 16px; background: #111827; border-radius: 12px; padding: 14px 18px; box-shadow: 0 4px 14px rgba(17,24,39,0.18);""><div style=""font-size: 0.95rem; font-weight: 700; letter-spacing: 0.02em;"">&#128240; JOURNALISM | Unit $unit | Lesson $lesson</div></div><div style=""font-family: Arial, Helvetica, sans-serif; font-size: 18px; line-height: 1.75; color: #1f2933; max-width: 980px; margin: 0 auto 22px auto; background: #e8f4ff; border-left: 8px solid #2563eb; border-radius: 10px; padding: 24px;""><h1 style=""font-size: 30px; margin-top: 0;"">$page</h1></div>"
}
function WriteText($path,$text) { Set-Content -LiteralPath $path -Value $text -Encoding UTF8 }
function GiftQuestion($id,$std,$prompt,$correctLetter,$answers) {
  $letters=@('A','B','C','D')
  $out="::$id::[$std] $prompt {`n"
  for($i=0;$i -lt 4;$i++){
    $mark= if($letters[$i] -eq $correctLetter){'='}else{'~'}
    $fb= if($letters[$i] -eq $correctLetter){"Correct. Step 1: identify the media literacy skill named in the standard. Step 2: compare the option with the embedded media text and lesson model. This answer works because it explains how structure, features, evidence, or central idea supports audience understanding."}else{"Not correct. Step 1: reread the embedded media text and identify the exact task. Step 2: compare this option with the lesson model. This choice either ignores a text feature, confuses purpose, weakens evidence, misstates the central idea, or adds information not supported by the text."}
    $out += "$mark$($letters[$i]). $($answers[$i])#$fb`n"
  }
  $out += "}"
  return $out
}
function MakeGift($prefix,$count,$standards,$prompts,$correctSeq,$source,$correctAnswer,$wrongSet) {
  $blocks=@()
  for($i=1;$i -le $count;$i++){
    $std=$standards[($i-1)%$standards.Count]
    $prompt="$source Question ${i}: $($prompts[($i-1)%$prompts.Count])"
    $correctLetter=$correctSeq[($i-1)%$correctSeq.Count]
    $wrong1=$wrongSet[0]; $wrong2=$wrongSet[1]; $wrong3=$wrongSet[2]
    switch($correctLetter){
      'A' { $answers=@($correctAnswer,$wrong1,$wrong2,$wrong3) }
      'B' { $answers=@($wrong1,$correctAnswer,$wrong2,$wrong3) }
      'C' { $answers=@($wrong1,$wrong2,$correctAnswer,$wrong3) }
      'D' { $answers=@($wrong1,$wrong2,$wrong3,$correctAnswer) }
    }
    $blocks += GiftQuestion "$prefix`_Q$('{0:D2}' -f $i)" $std $prompt $correctLetter $answers
  }
  return ($blocks -join "`n")
}

$base='Refined Courses/JOURNALISM/Units/Unit 04'
$l1=Join-Path $base 'Lesson 01'
$l2=Join-Path $base 'Lesson 02'

$source1Html='<p><strong>Embedded Media Text: School Safety Web Article</strong></p><p><strong>Headline:</strong> New Bike Rack Area Opens Near East Gate</p><p><strong>Subheading:</strong> The school adds marked parking spaces and a short safety checklist for student cyclists.</p><p><strong>Body:</strong> The school opened a new bike rack area near the east gate on Monday. The article begins with the schedule change, then explains why the location was chosen, then lists safety reminders. A sidebar titled <em>Before You Ride</em> reminds students to lock bikes, walk bikes on sidewalks, and use helmets. A photo caption identifies the east gate entrance and notes that the rack area is visible from the front office. A map shows the route from the bike racks to the main courtyard.</p>'
$source1Gift='Source: Headline: New Bike Rack Area Opens Near East Gate. Subheading: The school adds marked parking spaces and a short safety checklist for student cyclists. Body: The school opened a new bike rack area near the east gate on Monday. The article begins with the schedule change, then explains why the location was chosen, then lists safety reminders. A sidebar titled Before You Ride reminds students to lock bikes, walk bikes on sidewalks, and use helmets. A photo caption identifies the east gate entrance and notes that the rack area is visible from the front office. A map shows the route from the bike racks to the main courtyard.'
$source2Html='<p><strong>Embedded Media Text: Attendance Campaign Article</strong></p><p><strong>Headline:</strong> Advisory Campaign Encourages Students to Arrive on Time</p><p><strong>Body:</strong> The article explains that the school is starting a two-week advisory campaign about arriving on time. The central idea is that consistent arrival helps students begin class prepared. The article supports this idea with three details: the assistant principal says students miss opening instructions when they arrive late, a teacher says the first five minutes often include warm-up practice, and a student mentor says reminders in advisory can help students plan morning routines. The article ends by explaining that advisory teachers will review arrival tips each Monday.</p>'
$source2Gift='Source: Headline: Advisory Campaign Encourages Students to Arrive on Time. Body: The article explains that the school is starting a two-week advisory campaign about arriving on time. The central idea is that consistent arrival helps students begin class prepared. The article supports this idea with three details: the assistant principal says students miss opening instructions when they arrive late, a teacher says the first five minutes often include warm-up practice, and a student mentor says reminders in advisory can help students plan morning routines. The article ends by explaining that advisory teachers will review arrival tips each Monday.'

# Lesson 1 pages
WriteText (Join-Path $l1 'P01.html') ((Header '04' '01' 'P01 Lesson Overview') + (Box 'Lesson Title' '<p><strong>Lesson 1: Media Text Structures and Features</strong></p><p>This lesson teaches how media texts use structure and features to guide audience understanding. In journalism, the order of information, headings, sidebars, captions, maps, and other features are not decoration. They help readers find and interpret information.</p>' '#f59e0b' '#fffbeb') + (Box 'Standards Covered' '<p><strong>Primary Standard:</strong> MLA.JOUR.MED.01 - Media Text Structures and Features.</p><p><strong>Support Standards:</strong> MLA.JOUR.NEWS.03 - Expository News Writing; MLA.JOUR.MED.03 - Author Purpose, Appeals, and Language.</p>' '#64748b' '#f8fafc') + (Box 'What You Will Learn' '<ul><li>How structure affects how readers understand a media text.</li><li>How features such as headlines, subheadings, sidebars, captions, and maps support meaning.</li><li>How to explain why a feature is useful for the audience.</li><li>How structure and purpose work together in journalistic media.</li></ul>' '#059669' '#ecfdf5') + (Box 'What You Will Do' '<ul><li>Study an embedded school safety web article.</li><li>Identify the structure and media features.</li><li>Explain how features help readers understand and act.</li><li>Complete guided practice, independent work, checkpoint, and quiz.</li></ul>' '#ea580c' '#fff7ed') + (Box 'How You Will Show Mastery' '<ul><li>Identify text structures and media features.</li><li>Explain the function of each feature.</li><li>Connect structure and features to audience needs.</li><li>Submit checkpoint evidence aligned to MLA.JOUR.MED.01.</li></ul>' '#dc2626' '#fef2f2') + (Box 'Student-Friendly Standard Connection' '<p><strong>In student language:</strong> I can explain how a media text is organized and how its features help the audience understand the message.</p>' '#7c3aed' '#f5f3ff') + (Box 'Ask Your Teacher of Record for Help' '<p>Ask your Teacher of Record for help if you can name a feature but cannot explain what that feature does for the reader.</p>' '#2563eb' '#e8f4ff'))
WriteText (Join-Path $l1 'P02.html') ((Header '04' '01' 'P02 Notebook Task Part 1') + (Box 'Notebook Title' '<p><strong>How Media Structure Guides Readers</strong></p>' '#f59e0b' '#fffbeb') + (Box 'Vocabulary' '<ul><li><strong>Media text:</strong> a communication product that may include words, images, layout, audio, video, or interactive features.</li><li><strong>Text structure:</strong> the way information is organized.</li><li><strong>Feature:</strong> a design or information element such as a headline, sidebar, caption, or map.</li><li><strong>Sidebar:</strong> a boxed or separate section that gives quick supporting information.</li><li><strong>Caption:</strong> text that explains an image.</li></ul>' '#2563eb' '#e8f4ff') + (Box 'Embedded Source' $source1Html '#64748b' '#f8fafc') + (Box 'Step-by-Step Teaching' '<p><strong>Step 1: Identify the main structure.</strong> The article begins with the schedule change, explains the location, and then gives safety reminders. This structure moves from news to explanation to action.</p><p><strong>Step 2: Identify the headline.</strong> The headline tells readers the main news quickly: a new bike rack area is open.</p><p><strong>Step 3: Identify the subheading.</strong> The subheading adds two important details: marked parking spaces and a safety checklist.</p><p><strong>Step 4: Identify the sidebar.</strong> The sidebar gives quick action steps before students ride.</p><p><strong>Step 5: Identify the caption and map.</strong> The caption explains the image, and the map helps readers locate the route.</p><p><strong>Step 6: Explain function.</strong> Naming a feature is not enough. You must explain how it helps readers understand, locate, remember, or act on information.</p>' '#059669' '#ecfdf5') + (Box 'Notebook Directions' '<p>In your notebook, create three columns: Feature, Information It Gives, and How It Helps the Audience. Fill in the chart for headline, subheading, sidebar, caption, and map.</p>' '#ea580c' '#fff7ed') + (Box 'Model Example' '<p><strong>Feature:</strong> Sidebar titled <em>Before You Ride</em>.</p><p><strong>Information:</strong> Lock bikes, walk bikes on sidewalks, and use helmets.</p><p><strong>Audience help:</strong> The sidebar gives quick safety actions without making readers search through the whole article.</p>' '#7c3aed' '#f5f3ff'))
WriteText (Join-Path $l1 'P03.html') ((Header '04' '01' 'P03 Notebook Task Part 2') + (Box 'Continued Notebook Application' '<p>Now connect structure to purpose. A media text is designed for a reader who needs information quickly. The structure and features should support that reader.</p>' '#f59e0b' '#fffbeb') + (Box 'Deeper Learning' '<p><strong>Step 1: Ask what the audience needs first.</strong> Students need to know that the bike rack area is open.</p><p><strong>Step 2: Ask what the audience needs next.</strong> Students need to know where it is and how to use it safely.</p><p><strong>Step 3: Decide which feature supports which need.</strong> The map supports location. The sidebar supports safety actions. The caption supports image understanding.</p><p><strong>Step 4: Evaluate placement.</strong> A safety checklist works well as a sidebar because it is short, practical, and easy to scan.</p><p><strong>Step 5: Explain impact.</strong> The features make the article more useful because readers can find action steps quickly.</p>' '#059669' '#ecfdf5') + (Box 'Embedded Source Reminder' $source1Html '#64748b' '#f8fafc') + (Box 'Common Mistake' '<p><span style="color:#b91c1c;"><strong>Incorrect:</strong> The map is included because maps look good on a page.</span></p><p><span style="color:#047857;"><strong>Correct:</strong> The map helps readers locate the route from the bike racks to the main courtyard.</span></p><p><strong>Teachable explanation:</strong> The incorrect answer describes decoration. The correct answer explains function: the map helps readers understand location and movement.</p>' '#dc2626' '#fef2f2') + (Box 'Notebook Directions' '<p>Choose two media features from the embedded source. For each one, write one sentence naming the feature and one sentence explaining its function for the audience.</p>' '#ea580c' '#fff7ed'))
WriteText (Join-Path $l1 'P04.html') ((Header '04' '01' 'P04 Worked Example') + (Box 'Example 1: Headline Function' '<p><strong>Feature:</strong> Headline.</p><p><strong>Modeled thinking:</strong> A headline should tell readers the main news before they read the body.</p><p><strong>Function:</strong> The headline tells readers a new bike rack area has opened near the east gate.</p><p><strong>Reasoning:</strong> This prepares readers for the article topic immediately.</p>' '#059669' '#ecfdf5') + (Box 'Example 2: Sidebar Function' '<p><strong>Feature:</strong> Sidebar titled <em>Before You Ride</em>.</p><p><strong>Modeled thinking:</strong> A sidebar can highlight short action steps.</p><p><strong>Function:</strong> The sidebar separates safety reminders so students can scan them quickly.</p><p><strong>Reasoning:</strong> The feature makes practical information easier to find.</p>' '#2563eb' '#e8f4ff') + (Box 'Example 3: Caption and Map Function' '<p><strong>Features:</strong> Photo caption and map.</p><p><strong>Modeled thinking:</strong> Visual features should clarify, not distract.</p><p><strong>Function:</strong> The caption identifies the east gate entrance, and the map shows the route to the courtyard.</p><p><strong>Reasoning:</strong> Together, they help students recognize the location and navigate it.</p>' '#7c3aed' '#f5f3ff') + (Box 'Common Mistake' '<p><span style="color:#b91c1c;"><strong>Incorrect:</strong> A feature matters only if it makes the article more colorful.</span></p><p><span style="color:#047857;"><strong>Correct:</strong> A feature matters when it helps the audience understand, locate, remember, or use information.</span></p><p><strong>Teachable explanation:</strong> Media literacy asks what a feature does for meaning and audience use.</p>' '#dc2626' '#fef2f2'))
WriteText (Join-Path $l1 'P05.html') ((Header '04' '01' 'P05 Guided Practice') + (Box 'Guided Practice Instructions' '<p>Answer each guided practice question using the embedded bike rack media text. The same source appears inside each Guided Practice question in the GIFT file.</p>' '#2563eb' '#e8f4ff') + (Box 'Embedded Source' $source1Html '#64748b' '#f8fafc') + (Box 'Guided Practice Strategy' '<p>Use this process before answering:</p><ol><li>Name the structure or feature being tested.</li><li>Find what information the feature gives.</li><li>Ask how it helps the audience.</li><li>Choose the answer that explains function, not decoration.</li></ol><p>Media features are judged by how they support meaning and audience use.</p>' '#059669' '#ecfdf5'))
WriteText (Join-Path $l1 'P06.html') ((Header '04' '01' 'P06 Independent Work') + (Box 'Instructions' '<p>Use the bike rack media text to analyze how structure and features guide readers.</p>' '#2563eb' '#e8f4ff') + (Box 'Part A' '<p>Identify the article structure in three stages: what comes first, what comes next, and what comes last.</p>' '#059669' '#ecfdf5') + (Box 'Part B' '<p>Choose three media features. For each one, explain what information it gives and how it helps the audience.</p>' '#f59e0b' '#fffbeb') + (Box 'Part C' '<p>Write one paragraph explaining which feature is most useful for student readers and why.</p>' '#ea580c' '#fff7ed') + (Box 'Mastery Support Checklist' '<ul><li>Did I name structures and features accurately?</li><li>Did I explain each feature function?</li><li>Did I connect features to audience needs?</li><li>Did I avoid saying a feature is useful only because it looks good?</li><li>Did I use evidence from the embedded media text?</li></ul>' '#7c3aed' '#f5f3ff'))
WriteText (Join-Path $l1 'P07.html') ((Header '04' '01' 'P07 Checkpoint') + (Box 'Teacher of Record Reminder' '<p>Ask your Teacher of Record for help if you can identify a media feature but cannot explain how it supports audience understanding.</p>' '#2563eb' '#e8f4ff') + (Box 'Submission Workflow' '<ul><li>Complete P02 through P06.</li><li>Review your answers for feature function, not decoration.</li><li>Submit your checkpoint response.</li><li>Complete the Lesson 1 quiz after submission.</li></ul>' '#64748b' '#f8fafc') + (Box 'Checkpoint Task' '<p>Submit a media-feature analysis for the bike rack article. Include the article structure, three media features, and a paragraph explaining which feature best supports the audience.</p>' '#ea580c' '#fff7ed') + (Box 'Mastery Criteria' '<ul><li>The structure is accurately identified.</li><li>Three features are named correctly.</li><li>Each feature explanation includes audience function.</li><li>The paragraph uses evidence from the source.</li><li>The analysis aligns to MLA.JOUR.MED.01.</li></ul>' '#059669' '#ecfdf5'))

# Lesson 2 pages
WriteText (Join-Path $l2 'P01.html') ((Header '04' '02' 'P01 Lesson Overview') + (Box 'Lesson Title' '<p><strong>Lesson 2: Central Idea Support in Media Texts</strong></p><p>This lesson teaches how to identify a central idea in a media text and evaluate whether details actually support it. Media texts can look convincing, but readers must check how evidence develops the message.</p>' '#f59e0b' '#fffbeb') + (Box 'Standards Covered' '<p><strong>Primary Standard:</strong> MLA.JOUR.MED.02 - Central Idea Support in Media Texts.</p><p><strong>Support Standards:</strong> MLA.JOUR.REP.02 - Evidence and Reasoning in Reporting; MLA.JOUR.MED.01 - Media Text Structures and Features.</p>' '#64748b' '#f8fafc') + (Box 'What You Will Learn' '<ul><li>How to identify the central idea of a media text.</li><li>How to distinguish central idea from topic.</li><li>How supporting details develop a central idea.</li><li>How structure and features can strengthen support.</li></ul>' '#059669' '#ecfdf5') + (Box 'What You Will Do' '<ul><li>Study an embedded attendance-campaign media text.</li><li>Identify the central idea and supporting details.</li><li>Evaluate whether each detail is relevant and useful.</li><li>Complete guided practice, independent work, checkpoint, and quiz.</li></ul>' '#ea580c' '#fff7ed') + (Box 'How You Will Show Mastery' '<ul><li>State the central idea accurately.</li><li>Choose relevant supporting evidence.</li><li>Explain how evidence supports the central idea.</li><li>Submit checkpoint evidence aligned to MLA.JOUR.MED.02.</li></ul>' '#dc2626' '#fef2f2') + (Box 'Student-Friendly Standard Connection' '<p><strong>In student language:</strong> I can explain the main message of a media text and show how details support it.</p>' '#7c3aed' '#f5f3ff') + (Box 'Ask Your Teacher of Record for Help' '<p>Ask your Teacher of Record for help if you can identify the topic but cannot state what the text says about that topic.</p>' '#2563eb' '#e8f4ff'))
WriteText (Join-Path $l2 'P02.html') ((Header '04' '02' 'P02 Notebook Task Part 1') + (Box 'Notebook Title' '<p><strong>Finding Central Idea and Support</strong></p>' '#f59e0b' '#fffbeb') + (Box 'Vocabulary' '<ul><li><strong>Topic:</strong> the subject a text is about.</li><li><strong>Central idea:</strong> the main point or message the text develops about the topic.</li><li><strong>Supporting detail:</strong> a fact, example, quote, or explanation that develops the central idea.</li><li><strong>Relevant evidence:</strong> evidence that directly connects to the central idea.</li><li><strong>Development:</strong> the way details build and explain an idea across a text.</li></ul>' '#2563eb' '#e8f4ff') + (Box 'Embedded Source' $source2Html '#64748b' '#f8fafc') + (Box 'Step-by-Step Teaching' '<p><strong>Step 1: Identify the topic.</strong> The topic is the advisory campaign about arriving on time.</p><p><strong>Step 2: Identify the central idea.</strong> The central idea is that consistent arrival helps students begin class prepared.</p><p><strong>Step 3: Find supporting details.</strong> The assistant principal says late students miss opening instructions. A teacher says warm-up practice often happens in the first five minutes. A student mentor says advisory reminders can help students plan routines.</p><p><strong>Step 4: Explain connection.</strong> Each detail supports preparedness: instructions, practice, and planning routines all help students start class ready.</p><p><strong>Step 5: Evaluate support.</strong> Strong support directly explains the central idea. Weak support may be interesting but does not develop the main message.</p>' '#059669' '#ecfdf5') + (Box 'Notebook Directions' '<p>In your notebook, create four headings: Topic, Central Idea, Supporting Detail, and How It Supports. Fill the chart with at least three supporting details from the embedded source.</p>' '#ea580c' '#fff7ed') + (Box 'Model Example' '<p><strong>Topic:</strong> advisory campaign about arriving on time.</p><p><strong>Central Idea:</strong> consistent arrival helps students begin class prepared.</p><p><strong>Supporting Detail:</strong> a teacher says the first five minutes often include warm-up practice.</p><p><strong>How It Supports:</strong> arriving on time helps students participate in the warm-up instead of missing it.</p>' '#7c3aed' '#f5f3ff'))
WriteText (Join-Path $l2 'P03.html') ((Header '04' '02' 'P03 Notebook Task Part 2') + (Box 'Continued Notebook Application' '<p>Now move from identifying support to evaluating support. A detail is not strong just because it is true. It is strong when it clearly develops the central idea.</p>' '#f59e0b' '#fffbeb') + (Box 'Deeper Learning' '<p><strong>Step 1: Test the detail.</strong> Ask: Does this detail explain why arriving on time helps students begin prepared?</p><p><strong>Step 2: Look for a direct connection.</strong> Missing opening instructions directly connects to preparedness.</p><p><strong>Step 3: Watch for weakly related details.</strong> A detail about the color of advisory posters might be true, but it would not strongly support preparedness unless the text explains why it matters.</p><p><strong>Step 4: Explain the support in your own words.</strong> Do not just quote a detail. Explain how it develops the central idea.</p><p><strong>Step 5: Consider structure.</strong> The article gives the central idea, then uses source details to develop it, then ends with the action advisory teachers will take.</p>' '#059669' '#ecfdf5') + (Box 'Embedded Source Reminder' $source2Html '#64748b' '#f8fafc') + (Box 'Common Mistake' '<p><span style="color:#b91c1c;"><strong>Incorrect:</strong> The central idea is attendance.</span></p><p><span style="color:#047857;"><strong>Correct:</strong> The central idea is that consistent arrival helps students begin class prepared.</span></p><p><strong>Teachable explanation:</strong> Attendance is only the topic. The central idea must state the message the article develops about attendance.</p>' '#dc2626' '#fef2f2') + (Box 'Notebook Directions' '<p>Choose the strongest supporting detail in the embedded source. Write two sentences: one naming the detail and one explaining exactly how it develops the central idea.</p>' '#ea580c' '#fff7ed'))
WriteText (Join-Path $l2 'P04.html') ((Header '04' '02' 'P04 Worked Example') + (Box 'Example 1: Topic vs. Central Idea' '<p><strong>Topic:</strong> arriving on time.</p><p><strong>Modeled thinking:</strong> The topic is too broad by itself. I need to state what the article says about arriving on time.</p><p><strong>Central idea:</strong> consistent arrival helps students begin class prepared.</p><p><strong>Reasoning:</strong> This sentence states the message, not just the subject.</p>' '#059669' '#ecfdf5') + (Box 'Example 2: Detail Support' '<p><strong>Detail:</strong> late students miss opening instructions.</p><p><strong>Modeled thinking:</strong> Opening instructions prepare students for the class period.</p><p><strong>Support explanation:</strong> This detail supports the central idea because it shows one way lateness can prevent students from starting prepared.</p><p><strong>Reasoning:</strong> The detail is directly relevant.</p>' '#2563eb' '#e8f4ff') + (Box 'Example 3: Structure Support' '<p><strong>Structure:</strong> campaign introduced, problem explained, source details given, advisory action described.</p><p><strong>Modeled thinking:</strong> This order moves from message to support to action.</p><p><strong>Function:</strong> The structure helps readers understand why the campaign exists and what advisory teachers will do.</p><p><strong>Reasoning:</strong> Structure develops the central idea across the text.</p>' '#7c3aed' '#f5f3ff') + (Box 'Common Mistake' '<p><span style="color:#b91c1c;"><strong>Incorrect:</strong> Any detail in the article automatically supports the central idea equally.</span></p><p><span style="color:#047857;"><strong>Correct:</strong> A detail supports the central idea when it directly develops the main message.</span></p><p><strong>Teachable explanation:</strong> Evaluation requires judging the connection between evidence and idea, not just listing facts.</p>' '#dc2626' '#fef2f2'))
WriteText (Join-Path $l2 'P05.html') ((Header '04' '02' 'P05 Guided Practice') + (Box 'Guided Practice Instructions' '<p>Answer each guided practice question using the embedded attendance-campaign media text. The same source appears inside each Guided Practice question in the GIFT file.</p>' '#2563eb' '#e8f4ff') + (Box 'Embedded Source' $source2Html '#64748b' '#f8fafc') + (Box 'Guided Practice Strategy' '<p>Use this process before answering:</p><ol><li>Separate topic from central idea.</li><li>Find the detail being tested.</li><li>Ask how the detail develops the central idea.</li><li>Choose the answer that explains the connection clearly.</li></ol><p>Do not choose an answer just because it repeats a word from the source. Choose the answer that explains support.</p>' '#059669' '#ecfdf5'))
WriteText (Join-Path $l2 'P06.html') ((Header '04' '02' 'P06 Independent Work') + (Box 'Instructions' '<p>Use the attendance-campaign media text to analyze central idea support.</p>' '#2563eb' '#e8f4ff') + (Box 'Part A' '<p>State the topic and central idea. Make sure the central idea is a complete message, not a one-word topic.</p>' '#059669' '#ecfdf5') + (Box 'Part B' '<p>Choose three supporting details. For each detail, explain how it develops the central idea.</p>' '#f59e0b' '#fffbeb') + (Box 'Part C' '<p>Evaluate which supporting detail is strongest and explain why it most directly supports the central idea.</p>' '#ea580c' '#fff7ed') + (Box 'Mastery Support Checklist' '<ul><li>Did I distinguish topic from central idea?</li><li>Did I use source details accurately?</li><li>Did I explain how each detail supports the central idea?</li><li>Did I evaluate the strongest detail instead of just listing details?</li><li>Did I connect support to audience understanding?</li></ul>' '#7c3aed' '#f5f3ff'))
WriteText (Join-Path $l2 'P07.html') ((Header '04' '02' 'P07 Checkpoint') + (Box 'Teacher of Record Reminder' '<p>Ask your Teacher of Record for help if your central idea is only a topic or if your explanation does not show how details support the message.</p>' '#2563eb' '#e8f4ff') + (Box 'Submission Workflow' '<ul><li>Complete P02 through P06.</li><li>Review your central idea and supporting detail explanations.</li><li>Submit your checkpoint response.</li><li>Complete the Lesson 2 quiz after submission.</li></ul>' '#64748b' '#f8fafc') + (Box 'Checkpoint Task' '<p>Submit a central-idea support analysis for the attendance-campaign media text. Include the topic, central idea, three supporting details, and one evaluation of the strongest support.</p>' '#ea580c' '#fff7ed') + (Box 'Mastery Criteria' '<ul><li>The topic and central idea are correctly distinguished.</li><li>Supporting details come from the embedded source.</li><li>Each support explanation is clear and accurate.</li><li>The strongest support is evaluated with reasoning.</li><li>The response aligns to MLA.JOUR.MED.02.</li></ul>' '#059669' '#ecfdf5'))

$l1Json=[ordered]@{course='JOURNALISM';unit=4;lesson=1;lessonTitle='Media Text Structures and Features';pages=@('P01.html','P02.html','P03.html','P04.html','P05.html','P06.html','P07.html');standards=@('MLA.JOUR.MED.01','MLA.JOUR.NEWS.03','MLA.JOUR.MED.03');primaryStandards=@('MLA.JOUR.MED.01');supportStandards=@('MLA.JOUR.NEWS.03','MLA.JOUR.MED.03');assessments=[ordered]@{guidedPractice='JOUR_U04_L01_GuidedPractice.gift';lessonQuiz='JOUR_U04_L01_Quiz.gift'}} | ConvertTo-Json -Depth 5
WriteText (Join-Path $l1 'lesson.json') $l1Json
$l1Quiz=[ordered]@{course='JOURNALISM';unit=4;lesson=1;quizTitle='Journalism Unit 4 Lesson 1 Quiz';lessonReference='Unit 04 Lesson 01';giftFile='JOUR_U04_L01_Quiz.gift';questionCount=25;standards=@('MLA.JOUR.MED.01','MLA.JOUR.NEWS.03','MLA.JOUR.MED.03')} | ConvertTo-Json -Depth 5
WriteText (Join-Path $l1 'quiz.json') $l1Quiz
$l2Json=[ordered]@{course='JOURNALISM';unit=4;lesson=2;lessonTitle='Central Idea Support in Media Texts';pages=@('P01.html','P02.html','P03.html','P04.html','P05.html','P06.html','P07.html');standards=@('MLA.JOUR.MED.02','MLA.JOUR.REP.02','MLA.JOUR.MED.01');primaryStandards=@('MLA.JOUR.MED.02');supportStandards=@('MLA.JOUR.REP.02','MLA.JOUR.MED.01');assessments=[ordered]@{guidedPractice='JOUR_U04_L02_GuidedPractice.gift';lessonQuiz='JOUR_U04_L02_Quiz.gift'}} | ConvertTo-Json -Depth 5
WriteText (Join-Path $l2 'lesson.json') $l2Json
$l2Quiz=[ordered]@{course='JOURNALISM';unit=4;lesson=2;quizTitle='Journalism Unit 4 Lesson 2 Quiz';lessonReference='Unit 04 Lesson 02';giftFile='JOUR_U04_L02_Quiz.gift';questionCount=25;standards=@('MLA.JOUR.MED.02','MLA.JOUR.REP.02','MLA.JOUR.MED.01')} | ConvertTo-Json -Depth 5
WriteText (Join-Path $l2 'quiz.json') $l2Quiz

$std1=@('MLA.JOUR.MED.01','MLA.JOUR.NEWS.03','MLA.JOUR.MED.03')
$std2=@('MLA.JOUR.MED.02','MLA.JOUR.REP.02','MLA.JOUR.MED.01')
$prompts1=@('Which feature best supports audience navigation?','Which explanation describes the sidebar function?','Which structure description is most accurate?','Which choice explains the caption purpose?','Which answer connects feature to audience use?')
$prompts2=@('Which statement is the central idea?','Which detail best supports the central idea?','Which explanation connects evidence to the message?','Which detail is strongest support?','Which answer distinguishes topic from central idea?')
$correct1='Explain how the media feature or structure helps readers understand, locate, remember, or use information.'
$correct2='State the central idea accurately and explain how relevant source details develop that main message.'
$wrong1=@('Say the feature matters because it makes the page look colorful.','Ignore the feature and summarize only the article topic.','Add a new feature that is not described in the source.')
$wrong2=@('State only the broad topic without the message.','Choose a true detail that does not develop the central idea.','Add unsupported evidence that is not in the media text.')
WriteText (Join-Path $l1 'JOUR_U04_L01_GuidedPractice.gift') (MakeGift 'JOUR_U04_L01_GP' 5 $std1 $prompts1 @('B','D','A','C','B') $source1Gift $correct1 $wrong1)
WriteText (Join-Path $l1 'JOUR_U04_L01_Quiz.gift') (MakeGift 'JOUR_U04_L01_Q' 25 $std1 $prompts1 @('C','A','D','B','A','C','B','D') $source1Gift $correct1 $wrong1)
WriteText (Join-Path $l2 'JOUR_U04_L02_GuidedPractice.gift') (MakeGift 'JOUR_U04_L02_GP' 5 $std2 $prompts2 @('D','B','A','C','D') $source2Gift $correct2 $wrong2)
WriteText (Join-Path $l2 'JOUR_U04_L02_Quiz.gift') (MakeGift 'JOUR_U04_L02_Q' 25 $std2 $prompts2 @('A','C','B','D','B','A','D','C') $source2Gift $correct2 $wrong2)
