function New-ItemObj($standard, $question, $correct, $correctFeedback, $d1, $f1, $d2, $f2, $d3, $f3) {
  [pscustomobject]@{
    standard = $standard
    question = $question
    correct = $correct
    correctFeedback = $correctFeedback
    distractors = @(
      [pscustomobject]@{ text = $d1; feedback = $f1 },
      [pscustomobject]@{ text = $d2; feedback = $f2 },
      [pscustomobject]@{ text = $d3; feedback = $f3 }
    )
  }
}

function Choice($letter, $text, $feedback, $correct) {
  $prefix = if ($correct) { "=" } else { "~" }
  "$prefix$letter. $text#$feedback"
}

function GiftBlock($id, $std, $question, $choices) {
  "::$id::`nQuestion ID:<br>$id<br><br>MLA Standard:<br>$std<br><br>Question:<br>$question {`n$($choices -join "`n")`n}`n"
}

function BuildGift($items, $file, $prefix, $count) {
  $letters = @("A", "B", "C", "D")
  $blocks = @()
  for ($i = 1; $i -le $count; $i++) {
    $seed = $items[$i - 1]
    $correctIndex = ($i - 1) % 4
    $ordered = @()
    $d = 0
    for ($j = 0; $j -lt 4; $j++) {
      if ($j -eq $correctIndex) {
        $ordered += Choice $letters[$j] $seed.correct $seed.correctFeedback $true
      } else {
        $ordered += Choice $letters[$j] $seed.distractors[$d].text $seed.distractors[$d].feedback $false
        $d++
      }
    }
    $qid = "{0}_Q{1:D2}" -f $prefix, $i
    $blocks += GiftBlock $qid $seed.standard $seed.question $ordered
  }
  Set-Content -Path $file -Value ($blocks -join "`n") -NoNewline
}

function SF($q, $c, $cf, $d1, $f1, $d2, $f2, $d3, $f3) {
  New-ItemObj "Readiness Support Only" $q $c $cf $d1 $f1 $d2 $f2 $d3 $f3
}

$l1 = @(
  SF "A logo is enlarged from a width of 4 cm to 10 cm. What is the scale factor from the original to the image?" "2.5" "Scale factor compares image length to original length: 10 divided by 4 is 2.5." "6" "This subtracts the lengths instead of comparing them multiplicatively." "14" "This adds the lengths and does not describe scale factor." "0.4" "This is the reverse scale factor from image to original.",
  SF "Two similar rectangles have corresponding heights 7 and 21. What is the scale factor from the smaller rectangle to the larger rectangle?" "3" "The scale factor is 21 divided by 7, which equals 3." "14" "This subtracts the heights instead of using a multiplier." "28" "This adds the heights and does not represent similarity scaling." "&frac13;" "This is the scale factor from larger to smaller, not smaller to larger.",
  SF "A scale copy changes a side from 9 units to 6 units. What is the scale factor from the original to the copy?" "<sup>2</sup>&frasl;<sub>3</sub>" "The copy-to-original ratio is 6 divided by 9, which simplifies to <sup>2</sup>&frasl;<sub>3</sub>." "3" "This uses a whole-number multiplier that would enlarge the side." "15" "This adds the side lengths and does not describe scale factor." "<sup>3</sup>&frasl;<sub>2</sub>" "This is the reverse scale factor from the copy back to the original.",
  SF "Figure A has side lengths 5, 8, and 11. Figure B has corresponding side lengths 10, 16, and 22. What evidence supports similarity?" "All corresponding side ratios are 2." "Each side in Figure B is twice the matching side in Figure A, so the side ratios are equal." "Only one side is doubled." "All three corresponding sides are doubled, not just one." "The figures are similar because they are drawn near each other." "Location in a diagram is not evidence of similarity." "The side differences are all equal." "The differences are not all equal, and similarity depends on ratios rather than differences.",
  SF "Figure A has side lengths 3, 4, and 6. Figure B has corresponding side lengths 6, 8, and 12. What is the common scale factor?" "2" "Each corresponding side in Figure B is 2 times the side in Figure A." "3" "A scale factor of 3 would make the sides 9, 12, and 18." "4" "A scale factor of 4 would make the sides 12, 16, and 24." "1" "A scale factor of 1 would mean the corresponding lengths are unchanged.",
  SF "A drawing uses a scale factor of 4 from a small triangle to a large triangle. A 6-inch side on the small triangle corresponds to what length on the large triangle?" "24 inches" "Multiply the original side by the scale factor: 6 times 4 equals 24." "10 inches" "Adding 4 treats the scale factor as an amount to add instead of a multiplier." "2 inches" "Dividing by 4 scales in the opposite direction." "18 inches" "Multiplying by 3 does not use the given scale factor of 4.",
  SF "A scale factor of &frac12; is applied to a figure. What happens to each corresponding side length?" "Each side length is halved." "A scale factor of &frac12; multiplies every length by one-half." "Each side length doubles." "Doubling would use a scale factor of 2." "Each side length increases by &frac12; unit." "Scale factors multiply lengths; they do not add a fixed amount." "Only one side length changes." "A dilation scale factor applies to all corresponding lengths.",
  SF "Which statement gives mathematical evidence that two figures are similar?" "Corresponding angles match and corresponding side ratios are equal." "Similarity requires equal corresponding angles and proportional corresponding side lengths." "The figures appear to have the same shape." "Appearance alone is not mathematical evidence." "One pair of sides has the same length." "One side pair alone does not establish similarity." "The figures are both shaded." "Shading is visual decoration, not similarity evidence.",
  SF "Two figures have corresponding side ratios 4:6, 6:9, and 8:12. What do these ratios show?" "The corresponding side lengths are proportional." "Each ratio simplifies to 2:3, so the side lengths are proportional." "The figures are congruent." "Congruent figures would have a scale factor of 1; these ratios show a different common ratio." "Only the first two sides are proportional." "All three listed ratios simplify to the same relationship." "No comparison is possible." "The ratios provide enough information to compare corresponding sides.",
  SF "A scale factor from Figure P to Figure Q is 1. What does that mean about corresponding side lengths?" "They are equal in length." "A scale factor of 1 leaves every corresponding side length unchanged." "They are doubled." "Doubling would require a scale factor of 2." "They are halved." "Halving would require a scale factor of &frac12;." "They cannot be compared." "A scale factor gives a direct comparison of corresponding lengths.",
  SF "A rectangle has sides 6 and 10. A similar rectangle has a side corresponding to 6 that measures 18. What side corresponds to 10?" "30" "The scale factor is 18 divided by 6, or 3; therefore 10 times 3 equals 30." "22" "Adding 12 repeats the first side difference, but similarity uses multiplication." "15" "This uses a scale factor of 1.5 instead of 3." "28" "This does not use the matching scale factor from corresponding sides.",
  SF "A model uses scale factor 5 from a drawing to the actual object. A drawing length is 3 cm. What is the actual length?" "15 cm" "Multiply the drawing length by the scale factor: 3 times 5 equals 15." "8 cm" "Adding the scale factor does not apply similarity scaling." "2 cm" "Subtracting does not apply a scale factor." "1.67 cm" "Dividing by 5 would scale from actual object back to drawing.",
  SF "A triangle has sides 4, 7, and 9. A scale copy has sides 12, 21, and 27. Are the triangles similar by side ratios?" "Yes, each corresponding side ratio is 3." "The second triangle has sides 3 times the first triangle, so the side ratios are equal." "No, because the side differences are not equal." "Similarity depends on ratios, not equal differences." "No, because the triangles have different sizes." "Similar figures may have different sizes when side lengths are proportional." "Yes, because only one side ratio is 3." "All corresponding side ratios must be checked, not just one.",
  SF "Which pair of ratios is proportional?" "<sup>8</sup>&frasl;<sub>12</sub> and <sup>2</sup>&frasl;<sub>3</sub>" "<sup>8</sup>&frasl;<sub>12</sub> simplifies to <sup>2</sup>&frasl;<sub>3</sub>, so the ratios are equal." "<sup>3</sup>&frasl;<sub>5</sub> and <sup>5</sup>&frasl;<sub>3</sub>" "These are reciprocals, not equal ratios." "<sup>4</sup>&frasl;<sub>9</sub> and <sup>8</sup>&frasl;<sub>12</sub>" "These simplify to different values." "<sup>7</sup>&frasl;<sub>10</sub> and <sup>10</sup>&frasl;<sub>7</sub>" "These are reciprocals, not equal ratios.",
  SF "A poster is reduced with scale factor 0.25. Which statement is true?" "Each corresponding length becomes one-fourth as long." "A scale factor of 0.25 is equivalent to one-fourth." "Each corresponding length becomes four times as long." "That would use a scale factor of 4." "Only the width changes." "A scale factor affects every corresponding length." "Lengths increase by 0.25 unit." "Scale factors multiply lengths rather than adding a fixed amount.",
  SF "Two figures have corresponding sides 8 and 20. What is the scale factor from the first figure to the second?" "2.5" "The scale factor is 20 divided by 8, which equals 2.5." "12" "This subtracts the side lengths instead of comparing them by ratio." "28" "This adds side lengths and does not give a scale factor." "0.4" "This is the reverse scale factor from the second figure to the first.",
  SF "A similar figure has a side length 45 corresponding to original side length 15. Which scale factor was used?" "3" "Divide the image length by the original length: 45 divided by 15 equals 3." "30" "This subtracts the lengths instead of using a ratio." "60" "This adds the lengths and does not describe similarity." "&frac13;" "This is the reverse scale factor.",
  SF "A scale factor of 2.2 is applied to a segment of length 5. What is the image length?" "11" "Multiply 5 by 2.2 to get 11." "7.2" "Adding 2.2 treats the scale factor as an addend." "2.8" "Subtracting the scale factor does not describe dilation." "2.27" "Dividing by 2.2 scales in the opposite direction.",
  SF "A student claims two quadrilaterals are similar because both have four sides. What is missing?" "Evidence about corresponding angles and side ratios" "Having four sides only identifies both as quadrilaterals; similarity requires angle and proportional side evidence." "The color of each figure" "Color does not determine similarity." "The area of the page" "The page area is unrelated to figure similarity." "The names of the vertices only" "Vertex names help with correspondence but do not alone prove similarity.",
  SF "Side ratios from Figure A to Figure B are 2, 2, 2, and 2. What conclusion is reasonable if corresponding angles also match?" "The figures are similar." "Equal corresponding side ratios together with matching angles support similarity." "The figures cannot be compared." "The ratios and angle evidence allow a comparison." "The figures must have scale factor 1." "The scale factor shown by the ratios is 2, not 1." "The figures are unrelated because they have four sides." "Four-sided figures can be similar when correspondence evidence is present.",
  SF "A small pentagon is dilated to a larger pentagon with scale factor 4. A side of the small pentagon is 2.5 units. What is the corresponding larger side?" "10 units" "Multiply 2.5 by 4 to get 10 units." "6.5 units" "Adding 4 does not use the scale factor as a multiplier." "1.6 units" "Dividing by 4 scales in the reverse direction." "8 units" "This does not use the given side length 2.5 correctly.",
  SF "If corresponding side lengths are proportional, what must still be checked for polygon similarity?" "Corresponding angles" "For polygons, corresponding angles must also match." "The drawing color" "Color is not part of similarity." "The page orientation" "Page orientation does not determine similarity." "Whether the names use the same letters" "Letter names help with correspondence but do not establish similarity.",
  SF "A figure is enlarged by scale factor 6. What happens to a 1.5-unit side?" "It becomes 9 units." "Multiply 1.5 by 6 to get 9." "It becomes 7.5 units." "Adding 6 does not use scale factor correctly." "It becomes 4.5 units." "Multiplying by 3 does not use the given scale factor." "It becomes 0.25 unit." "Dividing by 6 scales in the opposite direction.",
  SF "Two diagrams look alike but have no measurements or markings. What can be concluded?" "No similarity conclusion is justified from appearance alone." "Similarity needs evidence such as side ratios, angle measures, or a transformation." "They are definitely similar." "Appearance alone is not proof of similarity." "They are definitely congruent." "Congruence also requires evidence, not appearance alone." "Their scale factor is 1." "A scale factor cannot be determined without corresponding measurements or other evidence."
)

function T($std, $q, $c, $cf, $d1, $f1, $d2, $f2, $d3, $f3) { New-ItemObj $std $q $c $cf $d1 $f1 $d2 $f2 $d3 $f3 }

$l2 = @(
  T "MLA.GEO.SIM.2" "Which transformation changes size while preserving angle measures?" "Dilation" "A dilation scales lengths but preserves angle measures, so it supports similarity." "Translation" "A translation preserves size and shape." "Reflection" "A reflection preserves size and shape." "Rotation" "A rotation preserves size and shape.",
  T "MLA.GEO.CGM.3" "A sequence says translate left 4 units, then dilate by 3. Which transformation occurs first?" "Translate left 4 units" "Transformation sequences are followed in the stated order." "Dilate by 3" "This reverses the stated order." "Reflect across the x-axis" "No reflection appears in the sequence." "Rotate 180&deg;" "No rotation appears in the sequence.",
  T "MLA.GEO.CGM.4" "A pattern slides horizontally and matches the next copy exactly. What symmetry is shown?" "Translation symmetry" "A repeated slide that maps a pattern onto itself shows translation symmetry." "Reflection symmetry" "Reflection symmetry uses a mirror line." "Rotation symmetry" "Rotation symmetry uses a turn." "Dilation symmetry" "Dilation changes size and is not the slide described.",
  T "MLA.GEO.SIM.2" "A triangle is dilated by scale factor 2 and then reflected. What relationship does the final image have to the original?" "It is similar to the original." "The dilation preserves shape and the reflection is rigid, so similarity is preserved." "It must be congruent to the original." "The scale factor 2 changes side lengths, so congruence is not guaranteed." "It has no related angles." "Dilations and reflections preserve angle measures." "It cannot be compared." "The transformation sequence gives a direct comparison.",
  T "MLA.GEO.CGM.4" "A snowflake-like design maps onto itself after a 60&deg; turn. What type of symmetry is this?" "Rotation symmetry" "Mapping onto itself after a turn shows rotation symmetry." "Reflection symmetry" "Reflection symmetry requires a mirror line." "Translation symmetry" "Translation symmetry requires a slide." "Scale symmetry" "The description involves a turn, not a change in size.",
  T "MLA.GEO.CGM.3" "A sequence says rotate 90&deg;, reflect across the x-axis, then translate up 2. Which step is second?" "Reflect across the x-axis" "The second listed transformation is the reflection." "Rotate 90&deg;" "The rotation is the first step." "Translate up 2" "The translation is the third step." "Dilate by 2" "No dilation is included in this sequence.",
  T "MLA.GEO.SIM.2" "Which statement best justifies similarity using transformations?" "A dilation followed by a rotation maps one figure to the other." "A dilation can change size while preserving shape, and rotation preserves shape." "A translation changes all angle measures." "Translations preserve angle measures and do not change shape." "A reflection changes side ratios." "Reflections preserve lengths and do not create proportional scaling." "A rotation changes side lengths." "Rotations preserve side lengths.",
  T "MLA.GEO.CGM.4" "A capital letter has a vertical mirror line through its center. Which symmetry can it have?" "Reflection symmetry" "A mirror line through the center shows reflection symmetry." "Translation symmetry" "Translation symmetry involves repeated sliding copies." "Dilation symmetry" "A dilation changes size rather than creating mirror halves." "Sequence symmetry" "Sequence is not the name of this symmetry type.",
  T "MLA.GEO.CGM.3" "If a figure maps onto another by reflecting, then rotating, which operation happens after the reflection?" "The rotation" "The sequence says reflect first, then rotate." "Another reflection" "Only one reflection is stated." "A dilation" "No dilation is stated." "A translation" "No translation is stated.",
  T "MLA.GEO.SIM.2" "A dilation has scale factor &frac12;. What similarity conclusion is supported?" "The image is similar to the preimage." "A dilation with any positive scale factor preserves shape, so similarity is supported." "The image is always congruent to the preimage." "A scale factor of &frac12; changes side lengths." "The image has doubled side lengths." "A scale factor of &frac12; halves side lengths." "The image has different angle measures." "Dilations preserve angle measures.",
  T "MLA.GEO.CGM.4" "A strip design can be shifted right by one tile and still match itself. What symmetry is present?" "Translation symmetry" "A shift or slide that maps a design onto itself is translation symmetry." "Reflection symmetry" "Reflection uses a mirror line, not a shift." "Rotation symmetry" "Rotation uses a turn, not a shift." "No symmetry" "The design maps onto itself by a shift, so symmetry is present.",
  T "MLA.GEO.CGM.3" "Which sequence is written in the order 'dilate, then translate'?" "Dilate by 4; translate right 3" "This lists dilation first and translation second." "Translate right 3; dilate by 4" "This reverses the required order." "Reflect; rotate" "Neither step is the requested dilation-translation sequence." "Rotate; translate" "The first step should be a dilation, not a rotation.",
  T "MLA.GEO.SIM.2" "Why can a dilation be part of a similarity transformation?" "It preserves shape while scaling size." "Similarity allows proportional size changes with preserved angle measures." "It always preserves every length." "A dilation changes lengths unless the scale factor is 1." "It changes angles." "A dilation preserves angle measures." "It removes correspondence." "A dilation maintains corresponding parts through the scale factor.",
  T "MLA.GEO.CGM.4" "A rectangle maps onto itself after a 180&deg; rotation. Which symmetry is shown?" "Rotation symmetry" "A 180&deg; turn mapping the rectangle onto itself is rotation symmetry." "Translation symmetry" "No slide is described." "Dilation symmetry" "No size change is described." "Only reflection symmetry" "The question describes a turn, not a mirror line.",
  T "MLA.GEO.CGM.3" "A figure is translated, reflected, and then dilated. Which transformation changes the size?" "Dilation" "Dilation is the transformation in the sequence that changes size." "Translation" "Translation moves a figure without changing size." "Reflection" "Reflection flips a figure without changing size." "Both translation and reflection" "Both are rigid motions and preserve size.",
  T "MLA.GEO.SIM.2" "A figure is transformed by a rotation and then a dilation with scale factor 5. What is true?" "The final image is similar to the original." "The rotation preserves shape and the dilation scales all lengths proportionally." "The final image must be smaller." "A scale factor of 5 enlarges lengths." "The final image has different angle measures." "Rotations and dilations preserve angle measures." "The original and image cannot be related." "The transformation sequence relates them directly.",
  T "MLA.GEO.CGM.4" "A design has both a mirror line and a 180&deg; turn that maps it onto itself. What can be said?" "It has reflection and rotation symmetry." "The mirror line gives reflection symmetry and the turn gives rotation symmetry." "It has only translation symmetry." "No slide is described." "It has no symmetry." "Two symmetry mappings are described." "It is similar but not symmetric." "Similarity is not the same as the symmetry mappings described.",
  T "MLA.GEO.CGM.3" "A sequence maps Figure A to Figure B: rotate, translate, dilate. Which step is last?" "Dilate" "The last listed transformation is the dilation." "Rotate" "The rotation is first." "Translate" "The translation is second." "Reflect" "No reflection is included.",
  T "MLA.GEO.SIM.2" "Which sequence can show two figures are similar but different sizes?" "Translate, then dilate by 3" "A translation preserves shape, and a dilation by 3 changes size proportionally." "Translate, then rotate" "Both are rigid motions, so the figures would stay congruent." "Reflect, then translate" "Both are rigid motions and do not change size." "Rotate, then reflect" "Both are rigid motions and do not change size.",
  T "MLA.GEO.CGM.4" "A figure maps onto itself after being reflected across a horizontal line. What symmetry is present?" "Reflection symmetry" "A reflection across a line that maps the figure onto itself shows reflection symmetry." "Rotation symmetry" "No turn is described." "Translation symmetry" "No slide is described." "Similarity symmetry" "Similarity is a relationship, not the symmetry described here.",
  T "MLA.GEO.CGM.3" "In the sequence 'reflect, translate, rotate,' which transformation occurs between the other two?" "Translate" "Translate is listed after reflect and before rotate." "Reflect" "Reflect is first." "Rotate" "Rotate is last." "Dilate" "No dilation is included.",
  T "MLA.GEO.SIM.2" "A dilation with scale factor 1 maps a figure to an image. What relationship is guaranteed?" "The image is similar and congruent to the original." "Scale factor 1 preserves both shape and size." "The image is similar but never congruent." "With scale factor 1, lengths do not change." "The image has no corresponding parts." "The dilation maps corresponding parts directly." "The image must be smaller." "Scale factor 1 does not shrink the figure.",
  T "MLA.GEO.CGM.4" "Which description identifies reflection symmetry?" "A line can fold the figure onto itself." "Folding over a line onto itself describes reflection symmetry." "A point turn maps the figure onto itself." "That describes rotation symmetry." "A slide maps a pattern to a repeated copy." "That describes translation symmetry." "A dilation changes every length by a factor." "That describes scaling, not reflection symmetry.",
  T "MLA.GEO.CGM.3" "A student applies transformations in this order: dilation, reflection, translation. Which is the second transformation?" "Reflection" "The second listed transformation is reflection." "Dilation" "Dilation is first." "Translation" "Translation is third." "Rotation" "Rotation is not listed.",
  T "MLA.GEO.SIM.2" "What must a similarity transformation preserve?" "Shape" "Similarity transformations preserve shape, including angle measures and proportional side lengths." "Only location" "Location may change, but shape preservation is essential." "Only color" "Color is not a geometric property used for similarity." "Only vertex names" "Vertex labels help identify correspondence but are not the preserved property."
)

# Lesson 3: triangle similarity
$l3 = @(
  T "MLA.GEO.SIM.3" "Two triangles have &angle;A &cong; &angle;D and &angle;B &cong; &angle;E. Which criterion justifies similarity?" "AA similarity" "Two congruent angle pairs are enough to prove triangle similarity." "SSS similarity" "SSS similarity requires all three side ratios." "SAS similarity" "SAS similarity requires two proportional side pairs and the included angle." "HL congruence" "HL proves congruence in right triangles, not similarity here.",
  T "MLA.GEO.SIM.3" "Corresponding sides of two triangles are 3 and 6, 5 and 10, and 7 and 14. Which criterion applies?" "SSS similarity" "All three corresponding side ratios are 2, so SSS similarity applies." "AA similarity" "No angle information is given." "SAS similarity" "The evidence gives all three side ratios, not two sides and an included angle." "CPCTC" "CPCTC is used after congruence, not to establish similarity.",
  T "MLA.GEO.SIM.3" "Two triangles have a congruent included angle and adjacent side ratios both equal 4. Which criterion applies?" "SAS similarity" "SAS similarity uses two proportional side pairs and the congruent included angle." "AA similarity" "Only one angle pair is described." "SSS similarity" "Only two side ratios are described." "SSS congruence" "The side lengths are proportional, not necessarily equal.",
  T "MLA.GEO.SIM.3" "If &triangle;ABC &sim; &triangle;DEF, which angle corresponds to &angle;B?" "&angle;E" "The order of the similarity statement maps A to D, B to E, and C to F." "&angle;D" "A corresponds to D, not B." "&angle;F" "C corresponds to F, not B." "&angle;A" "This is an angle in the first triangle, not the matching angle in the second.",
  T "MLA.GEO.SIM.3" "Two triangles have side ratios 2, 2, and 3. Is SSS similarity justified?" "No, all three side ratios must be equal." "SSS similarity requires the same ratio for every corresponding side pair." "Yes, two ratios match." "All three ratios must match, not only two." "Yes, any ratio greater than 1 works." "The actual ratio value matters less than equality across all pairs." "No, side ratios are never used." "SSS similarity is based on side ratios.",
  T "MLA.GEO.SIM.3" "Which evidence is enough for AA similarity?" "Two pairs of corresponding angles are congruent." "Two angle pairs establish triangle similarity because the third angle pair must also match." "One pair of sides is congruent." "One side pair alone does not establish similarity." "One side ratio is known." "One ratio alone is insufficient." "The triangles are drawn with the same orientation." "Orientation is not a similarity criterion.",
  T "MLA.GEO.SIM.3" "Which similarity statement matches A to R, B to S, and C to T?" "&triangle;ABC &sim; &triangle;RST" "The vertex order correctly pairs A-R, B-S, and C-T." "&triangle;ABC &sim; &triangle;RTS" "This pairs B with T instead of S." "&triangle;ABC &sim; &triangle;SRT" "This pairs A with S instead of R." "&triangle;ABC &sim; &triangle;TSR" "This reverses the intended correspondence.",
  T "MLA.GEO.SIM.3" "A dilation maps one triangle to a triangle congruent to another. What conclusion is supported?" "The original triangle is similar to the other triangle." "Dilation supports similarity, and congruence-preserving motion can complete the mapping." "The triangles have no relationship." "The transformation sequence gives a relationship." "The original triangle must be larger." "Dilation may enlarge or reduce depending on scale factor." "Only one angle is related." "A dilation preserves all angle measures.",
  T "MLA.GEO.SIM.3" "Two triangles have sides 6, 8, 10 and 9, 12, 15. Which statement is true?" "They are similar by SSS similarity." "Each side in the second triangle is 1.5 times the corresponding side in the first." "They are congruent by SSS." "The side lengths are not equal, so congruence is not shown." "They cannot be similar because sizes differ." "Similar triangles may have different sizes." "They are similar by AA only." "The given evidence is side ratios, not angle pairs.",
  T "MLA.GEO.SIM.3" "A pair of triangles has one congruent angle but no side information. What can be concluded?" "Similarity is not justified yet." "One angle pair alone is not enough for a triangle similarity criterion." "AA similarity applies." "AA needs two angle pairs." "SSS similarity applies." "SSS needs three side ratios." "SAS similarity applies." "SAS needs two side ratios and the included angle.",
  T "MLA.GEO.SIM.3" "In SAS similarity, which angle must be congruent?" "The included angle between the proportional sides" "SAS similarity uses the angle included by the two proportional side pairs." "Any angle in either triangle" "The angle must be between the proportional sides." "The largest angle only" "The criterion depends on included position, not size." "The right angle only" "SAS similarity applies beyond right triangles.",
  T "MLA.GEO.SIM.3" "Triangles have side ratios <sup>4</sup>&frasl;<sub>8</sub>, <sup>5</sup>&frasl;<sub>10</sub>, and <sup>6</sup>&frasl;<sub>12</sub>. What criterion is supported?" "SSS similarity" "All three ratios equal &frac12;, so SSS similarity is supported." "AA similarity" "No angle pairs are provided." "SAS similarity" "The evidence gives all three sides, not an included angle." "No similarity" "The ratios are equal, so similarity is supported.",
  T "MLA.GEO.SIM.3" "Two triangles have &angle;M &cong; &angle;P and &angle;N &cong; &angle;Q. What is the correct corresponding order?" "&triangle;MNO &sim; &triangle;PQR" "M maps to P, N maps to Q, so O maps to R." "&triangle;MNO &sim; &triangle;QPR" "M would map to Q, which conflicts with the given correspondence." "&triangle;MNO &sim; &triangle;RQP" "M would map to R, which is not given." "&triangle;MNO &sim; &triangle;PRQ" "N would map to R instead of Q.",
  T "MLA.GEO.SIM.3" "Which statement correctly uses transformation language for similarity?" "A dilation and rigid motion can map one triangle to the other." "Similarity can be justified by a dilation combined with rigid motions." "Only translations can prove similarity." "Translations alone preserve size and show congruence, not non-congruent similarity." "Reflections always change size." "Reflections preserve size." "Rotations destroy angle measures." "Rotations preserve angle measures.",
  T "MLA.GEO.SIM.3" "If two triangles are similar, what is true about corresponding angles?" "They are congruent." "Similar triangles have congruent corresponding angles." "They are supplementary." "Supplementary angles sum to 180&deg;, which is not required for all corresponding angles." "They are always right angles." "Similar triangles may or may not be right triangles." "They cannot be compared." "Correspondence allows angle comparison.",
  T "MLA.GEO.SIM.3" "If two triangles are similar, what is true about corresponding side lengths?" "They are proportional." "Similar triangles have equal ratios of corresponding side lengths." "They are always equal." "Equal side lengths would show congruence, a special case of similarity." "They are unrelated." "Similarity creates a proportional relationship." "They must differ by 1." "Similarity depends on ratios, not fixed differences.",
  T "MLA.GEO.SIM.3" "A student says two triangles are similar because one side pair has ratio 2. What is the problem?" "One side ratio is not enough evidence." "Similarity requires a complete criterion such as AA, SAS, or SSS." "The ratio must be less than 1." "Scale factors may be greater than 1." "Side ratios cannot support similarity." "Side ratios can support similarity when enough corresponding sides are known." "The triangles must be congruent first." "Similarity does not require prior congruence.",
  T "MLA.GEO.SIM.3" "Which triangle similarity criterion uses all three side pairs?" "SSS similarity" "SSS similarity checks all three corresponding side ratios." "AA similarity" "AA uses angle pairs." "SAS similarity" "SAS uses two side pairs and the included angle." "HL similarity" "HL is a congruence criterion for right triangles.",
  T "MLA.GEO.SIM.3" "Which triangle similarity criterion uses two angle pairs?" "AA similarity" "AA similarity uses two pairs of congruent corresponding angles." "SSS similarity" "SSS uses three side ratios." "SAS similarity" "SAS uses side ratios and an included angle." "CPCTC" "CPCTC is not a similarity criterion.",
  T "MLA.GEO.SIM.3" "Which triangle similarity criterion uses two side ratios and one included angle?" "SAS similarity" "SAS similarity matches two proportional sides with the included congruent angle." "AA similarity" "AA uses two angle pairs." "SSS similarity" "SSS uses all three side ratios." "ASA congruence" "ASA is a congruence criterion, not this similarity criterion.",
  T "MLA.GEO.SIM.3" "If &triangle;JKL &sim; &triangle;PQR, which side corresponds to KL?" "QR" "The statement maps J to P, K to Q, and L to R, so KL maps to QR." "PQ" "JK corresponds to PQ." "PR" "JL corresponds to PR." "JK" "JK is a side in the first triangle, not the corresponding side in the second.",
  T "MLA.GEO.SIM.3" "If &triangle;RST &sim; &triangle;XYZ, which side corresponds to RS?" "XY" "R maps to X and S maps to Y, so RS maps to XY." "YZ" "ST maps to YZ." "XZ" "RT maps to XZ." "ST" "ST is a different side in the first triangle.",
  T "MLA.GEO.SIM.3" "Two triangles have side ratios 1.2, 1.2, and 1.2. Which conclusion follows?" "The triangles are similar by SSS similarity." "All three corresponding side ratios are equal." "The triangles are congruent." "A ratio of 1.2 changes size, so congruence is not shown." "Only two sides are proportional." "All three listed ratios match." "The triangles are unrelated." "Equal ratios provide similarity evidence.",
  T "MLA.GEO.SIM.3" "Two triangles have two proportional side pairs but the angle given is not included. Can SAS similarity be used?" "No, the angle must be included." "SAS similarity requires the congruent angle between the proportional sides." "Yes, any angle works." "Position matters for SAS similarity." "Yes, because two side ratios are enough." "Two side ratios alone are not enough for SAS." "No, because side ratios never matter." "Side ratios matter, but the included angle condition is missing.",
  T "MLA.GEO.SIM.3" "Which explanation is strongest?" "The triangles are similar by AA because two corresponding angle pairs are congruent." "This names both the evidence and the correct criterion." "The triangles look similar." "Appearance is not enough evidence." "The triangles are probably similar." "A proof needs specific evidence." "The triangles have labels." "Labels alone do not establish similarity."
)

# Lesson 4 proportional relationships
$l4 = @(
  T "MLA.GEO.SIM.1" "Two similar figures have corresponding sides 5 and 20. What is the scale factor from first to second?" "4" "20 divided by 5 equals 4." "15" "This subtracts instead of comparing by ratio." "25" "This adds the side lengths." "&frac14;" "This is the reverse scale factor.",
  T "MLA.GEO.SIM.1" "A similar triangle has scale factor 3. A side of 11 becomes what length?" "33" "Multiply 11 by 3." "14" "Adding 3 does not use scale factor." "8" "Subtracting 3 does not use scale factor." "3.67" "Dividing by 3 scales in reverse.",
  T "MLA.GEO.SIM.1" "A map scale is 1 inch to 25 miles. How far is 4 inches?" "100 miles" "Four inches represents 4 times 25 miles." "29 miles" "Adding 4 and 25 does not use the scale." "6.25 miles" "Dividing 25 by 4 reverses the relationship." "75 miles" "That would match 3 inches, not 4.",
  T "MLA.GEO.SIM.1" "A 5-ft person casts a 6-ft shadow. A tree casts an 18-ft shadow. Assuming similar triangles, how tall is the tree?" "15 ft" "The shadow scale factor is 18 divided by 6, or 3; 5 times 3 is 15." "17 ft" "Adding 12 to the height copies a difference rather than a ratio." "21.6 ft" "Multiplying by 4.32 does not use the shadow scale factor." "10 ft" "This does not match the scale factor of 3.",
  T "MLA.GEO.SIM.1" "Two congruent figures are similar with what scale factor?" "1" "Conguent figures have equal corresponding lengths, so the scale factor is 1." "0" "A scale factor of 0 collapses lengths." "2" "A scale factor of 2 changes size." "&frac12;" "A scale factor of &frac12; changes size.",
  T "MLA.GEO.SIM.1" "A model car is 12 cm long at a 1:20 scale. What is the actual length?" "240 cm" "Actual length is 20 times the model length: 12 times 20." "32 cm" "Adding 20 does not use the scale ratio." "8 cm" "Subtracting 20 is not meaningful here." "0.6 cm" "Dividing by 20 scales in the wrong direction.",
  T "MLA.GEO.SIM.1" "A drawing uses scale factor &frac15;. An actual length is 60 cm. What is the drawing length?" "12 cm" "60 times &frac15; equals 12." "55 cm" "Subtracting 5 does not use scale." "65 cm" "Adding 5 does not use scale." "300 cm" "This uses the reciprocal scale and scales up.",
  T "MLA.GEO.SIM.1" "If corresponding sides are 7 to 14 and 9 to x, what is x?" "18" "The scale factor is 2, so 9 becomes 18." "16" "Adding 7 repeats a difference rather than a scale." "11" "Adding 2 does not use the scale factor." "4.5" "Dividing by 2 scales in the wrong direction.",
  T "MLA.GEO.SIM.1" "Which proportion matches corresponding sides 3 to 12 and 5 to x?" "<sup>3</sup>&frasl;<sub>12</sub> = <sup>5</sup>&frasl;<sub>x</sub>" "Corresponding sides must be placed in the same order in both ratios." "<sup>3</sup>&frasl;<sub>5</sub> = <sup>12</sup>&frasl;<sub>x</sub>" "This compares sides from different figures in the first ratio." "3 + 12 = 5 + x" "Similarity uses multiplicative ratios, not addition." "3x = 5" "This omits the corresponding side length 12.",
  T "MLA.GEO.SIM.1" "A 2-inch drawing length represents 18 feet. How many feet does 5 inches represent?" "45 feet" "The scale is 9 feet per inch, so 5 inches represents 45 feet." "23 feet" "Adding 5 to 18 does not use the scale." "36 feet" "This would match 4 inches at 9 feet per inch." "7.2 feet" "Dividing 36 by 5 does not match the scale relationship.",
  T "MLA.GEO.SIM.1" "A side of 16 corresponds to 10 in a smaller similar figure. What is the scale factor from larger to smaller?" "0.625" "The scale factor is 10 divided by 16, or 0.625." "6" "This subtracts side lengths." "26" "This adds side lengths." "1.6" "This is the reverse scale factor from smaller to larger.",
  T "MLA.GEO.SIM.1" "A similar polygon has scale factor 2.5. A 4-unit side becomes what length?" "10 units" "4 times 2.5 equals 10." "6.5 units" "Adding 2.5 does not use scale factor." "1.6 units" "Dividing by 2.5 scales in reverse." "8 units" "This uses a scale factor of 2, not 2.5.",
  T "MLA.GEO.SIM.1" "A 6-cm model represents 150 cm. What is the scale factor from model to actual?" "25" "150 divided by 6 equals 25." "144" "This subtracts lengths instead of finding the ratio." "156" "This adds lengths instead of finding the ratio." "0.04" "This is the reverse scale factor from actual to model.",
  T "MLA.GEO.SIM.1" "A shadow problem creates similar triangles. A 4-ft pole casts an 8-ft shadow; a building casts a 40-ft shadow. What is the building height?" "20 ft" "The shadow scale factor is 5, so 4 times 5 is 20." "36 ft" "Subtracting or using the shadow difference does not preserve the ratio." "44 ft" "Adding 40 and 4 does not use similar triangles." "10 ft" "This uses only half the needed scale factor.",
  T "MLA.GEO.SIM.1" "Two similar pentagons have scale factor 0.5 from P to Q. A side in P is 18. What is the corresponding side in Q?" "9" "18 times 0.5 equals 9." "18.5" "Adding 0.5 does not use scale." "36" "This uses the reciprocal and scales up." "17.5" "Subtracting 0.5 does not use scale.",
  T "MLA.GEO.SIM.1" "What information is needed to set up a proportion for similar figures?" "Corresponding side lengths" "Proportions compare matching corresponding sides." "Only the area color" "Color is unrelated to proportional side lengths." "Only the number of vertices" "The number of vertices does not determine side ratios." "Only the page size" "Page size does not provide corresponding lengths.",
  T "MLA.GEO.SIM.1" "A scale factor from A to B is 4. A side in B is 52. What was the corresponding side in A?" "13" "Divide 52 by 4 to reverse the scale factor." "56" "Adding 4 does not reverse scale." "48" "Subtracting 4 does not reverse scale." "208" "Multiplying by 4 scales from A to B again.",
  T "MLA.GEO.SIM.1" "A similar rectangle has width 30 corresponding to original width 12. What is the scale factor?" "2.5" "30 divided by 12 equals 2.5." "18" "This subtracts widths." "42" "This adds widths." "0.4" "This is the reverse scale factor.",
  T "MLA.GEO.SIM.1" "A blueprint has a 3-inch wall representing 24 feet. What does 7 inches represent?" "56 feet" "The scale is 8 feet per inch, so 7 inches represents 56 feet." "31 feet" "Adding 7 and 24 does not use the scale." "72 feet" "This would match 9 inches at the same scale." "3.43 feet" "Dividing 24 by 7 does not use the unit rate correctly.",
  T "MLA.GEO.SIM.1" "If x corresponds to 24 and 5 corresponds to 15, what is x?" "8" "The scale factor is 3, so x times 3 equals 24; x is 8." "12" "This uses an incorrect scale factor." "34" "Adding the known values is not proportional reasoning." "72" "This multiplies 24 by 3 instead of reversing the scale.",
  T "MLA.GEO.SIM.1" "A scale drawing is 9 cm tall and the actual object is 36 cm tall. What is the scale factor from drawing to actual?" "4" "36 divided by 9 equals 4." "27" "This subtracts heights." "45" "This adds heights." "0.25" "This is the reverse scale factor from actual to drawing.",
  T "MLA.GEO.SIM.1" "Two similar triangles have scale factor &frac34; from large to small. A large side is 20. What is the small side?" "15" "20 times &frac34; equals 15." "23" "Adding 3 does not use the scale factor." "80" "Multiplying by 4 does not use &frac34;." "26.67" "Dividing by &frac34; scales in the opposite direction.",
  T "MLA.GEO.SIM.1" "A student sets 4 + 6 = 10 + x for similar figures. What is the misconception?" "Using addition instead of ratios" "Similar figures are solved with proportional ratios, not additive sums." "Using corresponding sides" "Using corresponding sides is correct; the issue is the operation." "Using too many variables" "A variable may be used for an unknown side." "Checking scale factor" "Checking scale factor is part of the correct method.",
  T "MLA.GEO.SIM.1" "Which statement is true for congruent two-dimensional figures?" "Corresponding sides are equal." "Congruent figures have matching side lengths and angle measures." "Corresponding sides are always doubled." "Doubling describes a similar figure with scale factor 2, not congruence." "Angles are unrelated." "Congruent figures have matching corresponding angles." "Scale factor cannot be found." "The scale factor is 1 for congruent figures.",
  T "MLA.GEO.SIM.1" "A side length changes from 2.4 to 12 in a similar figure. What scale factor was used?" "5" "12 divided by 2.4 equals 5." "9.6" "This subtracts side lengths." "14.4" "This adds side lengths." "0.2" "This is the reverse scale factor."
)

# Lesson 5 Pythagorean readiness
$l5 = @()
$py = @(@(3,4,5),@(5,12,13),@(8,15,17),@(7,24,25),@(9,40,41),@(12,16,20),@(10,24,26),@(20,21,29),@(11,60,61),@(28,45,53))
foreach($t in $py){ $a=$t[0]; $b=$t[1]; $c=$t[2]; $l5 += T "Readiness Support Only" "A right triangle has legs $a and $b. What is the hypotenuse?" "$c" "Use a<sup>2</sup> + b<sup>2</sup> = c<sup>2</sup>; the square root of the sum is $c." "$($a+$b)" "Adding the legs does not find the hypotenuse." "$([math]::Abs($b-$a))" "Subtracting the legs does not use the Pythagorean Theorem." "$($a*$b)" "Multiplying the legs does not find the hypotenuse." }
foreach($t in $py){ $a=$t[0]; $b=$t[1]; $c=$t[2]; $l5 += T "Readiness Support Only" "A right triangle has hypotenuse $c and one leg $a. What is the other leg?" "$b" "Use b<sup>2</sup> = $c<sup>2</sup> - $a<sup>2</sup>; the missing leg is $b." "$($c-$a)" "Subtracting side lengths ignores the squared relationship." "$($c+$a)" "Adding the known lengths does not find a missing leg." "&radic;$($c*$c+$a*$a)" "Adding squares would be used if both known sides were legs, but $c is the hypotenuse." }
$l5 += T "Readiness Support Only" "Which side is opposite the right angle?" "The hypotenuse" "The hypotenuse is always opposite the right angle." "A leg" "The legs form the right angle." "The shorter side" "The shorter side is usually a leg, not the side opposite the right angle." "The adjacent side" "Adjacent depends on a chosen acute angle."
$l5 += T "Readiness Support Only" "Which equation fits legs 14 and 48 with hypotenuse c?" "14<sup>2</sup> + 48<sup>2</sup> = c<sup>2</sup>" "The squares of the legs add to the square of the hypotenuse." "14 + 48 = c<sup>2</sup>" "The legs must be squared before adding." "14c + 48 = 0" "This does not represent the Pythagorean relationship." "14<sup>2</sup> + c<sup>2</sup> = 48<sup>2</sup>" "This treats 48 as the hypotenuse instead of c."
$l5 += T "Readiness Support Only" "Which set of side lengths forms a right triangle?" "6, 8, 10" "6<sup>2</sup> + 8<sup>2</sup> = 10<sup>2</sup>." "4, 5, 6" "4<sup>2</sup> + 5<sup>2</sup> is not 6<sup>2</sup>." "5, 6, 7" "5<sup>2</sup> + 6<sup>2</sup> is not 7<sup>2</sup>." "6, 7, 12" "6<sup>2</sup> + 7<sup>2</sup> is not 12<sup>2</sup>."
$l5 += T "Readiness Support Only" "What is &radic;144?" "12" "12 squared equals 144." "72" "Dividing by 2 does not find a square root." "24" "Doubling 12 is not the square root." "&radic;12" "&radic;144 simplifies completely to 12."
$l5 += T "Readiness Support Only" "What is the longest side of a right triangle called?" "Hypotenuse" "The hypotenuse is the longest side and is opposite the right angle." "Leg" "Legs form the right angle and are shorter than the hypotenuse." "Median" "A median is a segment from a vertex to a midpoint." "Altitude" "An altitude is a height segment."
$l5 += T "Readiness Support Only" "A triangle has sides 9, 12, and 15. Why is it right?" "9<sup>2</sup> + 12<sup>2</sup> = 15<sup>2</sup>" "The two smaller side squares sum to the largest side square." "9 + 12 = 15" "9 + 12 equals 21, and addition is not the right-triangle test." "15 - 12 = 9" "15 - 12 equals 3, and subtraction is not the test." "9(12) = 15" "Multiplication of side lengths is not the Pythagorean test."
$l5 += T "Readiness Support Only" "If c is the hypotenuse, what equation is the Pythagorean Theorem?" "a<sup>2</sup> + b<sup>2</sup> = c<sup>2</sup>" "The sum of the squares of the legs equals the square of the hypotenuse." "a + b = c" "Side lengths do not add directly in the theorem." "a<sup>2</sup> - b<sup>2</sup> = c<sup>2</sup>" "The theorem uses a sum of leg squares." "ab = c<sup>2</sup>" "The theorem uses squares, not the product of legs."

# Lesson 6 trig definitions and ratio setup
$l6 = @(
  T "MLA.GEO.TRI.4" "Which ratio defines sine?" "<sup>opposite</sup>&frasl;<sub>hypotenuse</sub>" "Sine compares the opposite side to the hypotenuse." "<sup>adjacent</sup>&frasl;<sub>hypotenuse</sub>" "This defines cosine." "<sup>opposite</sup>&frasl;<sub>adjacent</sub>" "This defines tangent." "<sup>hypotenuse</sup>&frasl;<sub>opposite</sub>" "This reverses sine.",
  T "MLA.GEO.TRI.4" "Which ratio defines cosine?" "<sup>adjacent</sup>&frasl;<sub>hypotenuse</sub>" "Cosine compares the adjacent leg to the hypotenuse." "<sup>opposite</sup>&frasl;<sub>hypotenuse</sub>" "This defines sine." "<sup>opposite</sup>&frasl;<sub>adjacent</sub>" "This defines tangent." "<sup>hypotenuse</sup>&frasl;<sub>adjacent</sub>" "This reverses cosine.",
  T "MLA.GEO.TRI.4" "Which ratio defines tangent?" "<sup>opposite</sup>&frasl;<sub>adjacent</sub>" "Tangent compares the opposite leg to the adjacent leg." "<sup>opposite</sup>&frasl;<sub>hypotenuse</sub>" "This defines sine." "<sup>adjacent</sup>&frasl;<sub>hypotenuse</sub>" "This defines cosine." "<sup>hypotenuse</sup>&frasl;<sub>opposite</sub>" "This uses the wrong denominator for tangent.",
  T "MLA.GEO.TRI.4" "Relative to angle A, opposite = 5 and hypotenuse = 13. What is sin A?" "<sup>5</sup>&frasl;<sub>13</sub>" "Sine is opposite over hypotenuse." "<sup>12</sup>&frasl;<sub>13</sub>" "This would use adjacent over hypotenuse." "<sup>5</sup>&frasl;<sub>12</sub>" "This would define tangent if 12 were adjacent." "<sup>13</sup>&frasl;<sub>5</sub>" "This reverses sine.",
  T "MLA.GEO.TRI.4" "Relative to angle B, adjacent = 8 and hypotenuse = 17. What is cos B?" "<sup>8</sup>&frasl;<sub>17</sub>" "Cosine is adjacent over hypotenuse." "<sup>15</sup>&frasl;<sub>17</sub>" "This would be sine if 15 were opposite." "<sup>15</sup>&frasl;<sub>8</sub>" "This would be tangent with opposite over adjacent." "<sup>17</sup>&frasl;<sub>8</sub>" "This reverses cosine.",
  T "MLA.GEO.TRI.4" "Relative to angle C, opposite = 7 and adjacent = 24. What is tan C?" "<sup>7</sup>&frasl;<sub>24</sub>" "Tangent is opposite over adjacent." "<sup>24</sup>&frasl;<sub>7</sub>" "This reverses tangent." "<sup>7</sup>&frasl;<sub>25</sub>" "This would be sine if 25 were the hypotenuse." "<sup>24</sup>&frasl;<sub>25</sub>" "This would be cosine if 25 were the hypotenuse.",
  T "MLA.GEO.TRI.4" "Why must the reference angle be identified?" "Opposite and adjacent depend on the chosen acute angle." "The hypotenuse stays fixed, but opposite and adjacent change with the reference angle." "The hypotenuse changes with the reference angle." "The hypotenuse is always opposite the right angle." "The triangle stops being right." "The reference angle does not change the triangle type." "The right angle becomes acute." "The right angle remains 90&deg;.",
  T "MLA.GEO.TRI.4" "Which ratio uses the hypotenuse and opposite side?" "Sine" "Sine is opposite over hypotenuse." "Cosine" "Cosine uses adjacent and hypotenuse." "Tangent" "Tangent uses opposite and adjacent." "Slope" "Slope is not one of the three trig ratios here.",
  T "MLA.GEO.TRI.4" "Which ratio uses the adjacent side and hypotenuse?" "Cosine" "Cosine is adjacent over hypotenuse." "Sine" "Sine uses opposite and hypotenuse." "Tangent" "Tangent uses opposite and adjacent." "Perimeter" "Perimeter is a sum of side lengths, not a trig ratio.",
  T "MLA.GEO.TRI.4" "Which ratio does not use the hypotenuse?" "Tangent" "Tangent uses opposite over adjacent." "Sine" "Sine uses the hypotenuse." "Cosine" "Cosine uses the hypotenuse." "Both sine and cosine" "Both sine and cosine include the hypotenuse.",
  T "MLA.GEO.TRI.4" "SOH means which ratio?" "sin = <sup>opposite</sup>&frasl;<sub>hypotenuse</sub>" "SOH stands for sine, opposite, hypotenuse." "cos = <sup>opposite</sup>&frasl;<sub>hypotenuse</sub>" "Cosine is represented by CAH." "tan = <sup>opposite</sup>&frasl;<sub>hypotenuse</sub>" "Tangent is represented by TOA." "sin = <sup>adjacent</sup>&frasl;<sub>hypotenuse</sub>" "That is cosine.",
  T "MLA.GEO.TRI.4" "CAH means which ratio?" "cos = <sup>adjacent</sup>&frasl;<sub>hypotenuse</sub>" "CAH stands for cosine, adjacent, hypotenuse." "sin = <sup>adjacent</sup>&frasl;<sub>hypotenuse</sub>" "Sine uses opposite and hypotenuse." "tan = <sup>adjacent</sup>&frasl;<sub>hypotenuse</sub>" "Tangent uses opposite and adjacent." "cos = <sup>hypotenuse</sup>&frasl;<sub>adjacent</sub>" "This reverses cosine.",
  T "MLA.GEO.TRI.4" "TOA means which ratio?" "tan = <sup>opposite</sup>&frasl;<sub>adjacent</sub>" "TOA stands for tangent, opposite, adjacent." "sin = <sup>opposite</sup>&frasl;<sub>adjacent</sub>" "Sine uses opposite and hypotenuse." "cos = <sup>opposite</sup>&frasl;<sub>adjacent</sub>" "Cosine uses adjacent and hypotenuse." "tan = <sup>adjacent</sup>&frasl;<sub>opposite</sub>" "This reverses tangent.",
  T "MLA.GEO.TRI.4" "Relative to angle D, opposite = 9 and hypotenuse = 41. What is sin D?" "<sup>9</sup>&frasl;<sub>41</sub>" "Sine is opposite over hypotenuse." "<sup>40</sup>&frasl;<sub>41</sub>" "This would be cosine if 40 is adjacent." "<sup>9</sup>&frasl;<sub>40</sub>" "This would be tangent if 40 is adjacent." "<sup>41</sup>&frasl;<sub>9</sub>" "This reverses sine.",
  T "MLA.GEO.TRI.4" "Relative to angle E, adjacent = 20 and hypotenuse = 29. What is cos E?" "<sup>20</sup>&frasl;<sub>29</sub>" "Cosine is adjacent over hypotenuse." "<sup>21</sup>&frasl;<sub>29</sub>" "This would use the opposite side if 21 is opposite." "<sup>21</sup>&frasl;<sub>20</sub>" "This would be tangent with opposite over adjacent." "<sup>29</sup>&frasl;<sub>20</sub>" "This reverses cosine.",
  T "MLA.GEO.TRI.4" "Relative to angle F, opposite = 11 and adjacent = 60. What is tan F?" "<sup>11</sup>&frasl;<sub>60</sub>" "Tangent is opposite over adjacent." "<sup>60</sup>&frasl;<sub>11</sub>" "This reverses tangent." "<sup>11</sup>&frasl;<sub>61</sub>" "This would use the hypotenuse and match sine." "<sup>60</sup>&frasl;<sub>61</sub>" "This would match cosine if 61 is the hypotenuse.",
  T "MLA.GEO.TRI.4" "A student writes cos A = opposite over hypotenuse. What correction is needed?" "Use adjacent over hypotenuse for cosine." "Cosine is defined as adjacent over hypotenuse." "Use opposite over hypotenuse for cosine." "That repeats the sine ratio." "Use opposite over adjacent for cosine." "That defines tangent." "Use hypotenuse over adjacent for cosine." "This reverses the cosine ratio.",
  T "MLA.GEO.TRI.4" "A student writes tan A = adjacent over opposite. What correction is needed?" "Use opposite over adjacent." "Tangent is defined as opposite over adjacent." "Use adjacent over hypotenuse." "That defines cosine." "Use opposite over hypotenuse." "That defines sine." "Use hypotenuse over opposite." "That is not tangent.",
  T "MLA.GEO.TRI.4" "Which side is opposite an acute reference angle?" "The side across from the reference angle" "Opposite means across from the chosen angle." "The side touching the reference angle and not the hypotenuse" "That describes the adjacent side." "The side across from the right angle" "That describes the hypotenuse." "The longest leg" "Opposite depends on position relative to the reference angle.",
  T "MLA.GEO.TRI.4" "Which side is adjacent to an acute reference angle?" "The leg touching the angle" "Adjacent is the leg that touches the reference angle." "The side across from the angle" "That describes the opposite side." "The hypotenuse" "The hypotenuse touches acute angles but is not called the adjacent leg in trig ratios." "The side across from the right angle" "That is the hypotenuse.",
  T "MLA.GEO.TRI.4" "For angle A, opposite = 6, adjacent = 8, hypotenuse = 10. Which is cos A?" "<sup>8</sup>&frasl;<sub>10</sub>" "Cosine is adjacent over hypotenuse." "<sup>6</sup>&frasl;<sub>10</sub>" "This is sine." "<sup>6</sup>&frasl;<sub>8</sub>" "This is tangent." "<sup>10</sup>&frasl;<sub>8</sub>" "This reverses cosine.",
  T "MLA.GEO.TRI.4" "For angle B, opposite = 12, adjacent = 5, hypotenuse = 13. Which is sin B?" "<sup>12</sup>&frasl;<sub>13</sub>" "Sine is opposite over hypotenuse." "<sup>5</sup>&frasl;<sub>13</sub>" "This is cosine." "<sup>12</sup>&frasl;<sub>5</sub>" "This is tangent." "<sup>13</sup>&frasl;<sub>12</sub>" "This reverses sine.",
  T "MLA.GEO.TRI.4" "For angle C, opposite = 20, adjacent = 21, hypotenuse = 29. Which is tan C?" "<sup>20</sup>&frasl;<sub>21</sub>" "Tangent is opposite over adjacent." "<sup>21</sup>&frasl;<sub>20</sub>" "This reverses tangent." "<sup>20</sup>&frasl;<sub>29</sub>" "This is sine." "<sup>21</sup>&frasl;<sub>29</sub>" "This is cosine.",
  T "MLA.GEO.TRI.4" "Which trig ratio should be used when opposite and hypotenuse are known?" "Sine" "Sine uses opposite and hypotenuse." "Cosine" "Cosine uses adjacent and hypotenuse." "Tangent" "Tangent uses opposite and adjacent." "Pythagorean ratio" "The requested trig ratio is sine.",
  T "MLA.GEO.TRI.4" "Which trig ratio should be used when adjacent and hypotenuse are known?" "Cosine" "Cosine uses adjacent and hypotenuse." "Sine" "Sine uses opposite and hypotenuse." "Tangent" "Tangent uses opposite and adjacent." "Scale factor" "Scale factor is not a right-triangle trig ratio."
)

# Lesson 7 applications
$l7 = @()
foreach($t in @(@(6,8,10,"ramp"),@(9,12,15,"support beam"),@(12,16,20,"ladder brace"),@(15,20,25,"diagonal walkway"),@(10,24,26,"cable"))){ $a=$t[0]; $b=$t[1]; $c=$t[2]; $ctx=$t[3]; $l7 += T "MLA.GEO.TRI.5" "A $ctx forms a right triangle with legs $a ft and $b ft. What is the hypotenuse length?" "$c ft" "Use the Pythagorean Theorem; the hypotenuse is $c ft." "$($a+$b) ft" "Adding the legs does not find the hypotenuse." "$([math]::Abs($b-$a)) ft" "Subtracting the legs does not find the hypotenuse." "$($a*$b) ft" "Multiplying the legs does not find a side length." }
foreach($t in @(@(13,5,12,"ladder"),@(25,7,24,"fire escape"),@(17,8,15,"support wire"),@(29,20,21,"flagpole cable"),@(41,9,40,"tower brace"))){ $c=$t[0]; $a=$t[1]; $b=$t[2]; $ctx=$t[3]; $l7 += T "MLA.GEO.TRI.5" "A $ctx is the hypotenuse of length $c ft, and one leg is $a ft. What is the other leg?" "$b ft" "Use b<sup>2</sup> = $c<sup>2</sup> - $a<sup>2</sup>; the missing leg is $b ft." "$($c-$a) ft" "Subtracting side lengths ignores the squared relationship." "$($c+$a) ft" "Adding lengths does not solve for a missing leg." "&radic;$($c*$c+$a*$a) ft" "This adds squares even though the hypotenuse is already known." }
$l7 += T "MLA.GEO.TRI.5" "A building height h is opposite a 35&deg; angle and the horizontal distance is 50 m. Which setup fits?" "tan 35&deg; = <sup>h</sup>&frasl;<sub>50</sub>" "Tangent uses opposite over adjacent." "sin 35&deg; = <sup>50</sup>&frasl;<sub>h</sub>" "Sine uses opposite over hypotenuse, and 50 is adjacent." "cos 35&deg; = <sup>h</sup>&frasl;<sub>50</sub>" "Cosine uses adjacent over hypotenuse." "tan 35&deg; = <sup>50</sup>&frasl;<sub>h</sub>" "This reverses opposite and adjacent."
$l7 += T "MLA.GEO.TRI.5" "A ramp length r is the hypotenuse, and the rise is 4 ft with angle of elevation 20&deg;. Which setup uses sine?" "sin 20&deg; = <sup>4</sup>&frasl;<sub>r</sub>" "Sine uses opposite over hypotenuse." "cos 20&deg; = <sup>4</sup>&frasl;<sub>r</sub>" "Cosine uses adjacent over hypotenuse." "tan 20&deg; = <sup>4</sup>&frasl;<sub>r</sub>" "Tangent uses opposite over adjacent, not hypotenuse." "sin 20&deg; = <sup>r</sup>&frasl;<sub>4</sub>" "This reverses sine."
$l7 += T "MLA.GEO.TRI.5" "A diagonal path crosses a 18 m by 24 m rectangular garden. What is the path length?" "30 m" "The diagonal is the hypotenuse: 18<sup>2</sup> + 24<sup>2</sup> = 30<sup>2</sup>." "42 m" "Adding side lengths does not find the diagonal." "6 m" "Subtracting side lengths does not find the diagonal." "432 m" "Multiplying side lengths gives area, not diagonal length."
$l7 += T "MLA.GEO.TRI.5" "A kite string is 65 m long and the kite is 63 m above the ground. How far is the person horizontally from the point below the kite?" "16 m" "The string is the hypotenuse: x<sup>2</sup> + 63<sup>2</sup> = 65<sup>2</sup>, so x = 16." "2 m" "Subtracting 63 from 65 ignores the squared relationship." "128 m" "Adding the lengths does not find the horizontal distance." "&radic;8194 m" "This adds squares even though 65 is the hypotenuse."
$l7 += T "MLA.GEO.TRI.5" "A support cable makes a right triangle with opposite side 12 and adjacent side 35 relative to angle A. Which ratio finds angle A?" "tan A = <sup>12</sup>&frasl;<sub>35</sub>" "Tangent uses opposite over adjacent." "sin A = <sup>12</sup>&frasl;<sub>35</sub>" "Sine uses opposite over hypotenuse." "cos A = <sup>12</sup>&frasl;<sub>35</sub>" "Cosine uses adjacent over hypotenuse." "tan A = <sup>35</sup>&frasl;<sub>12</sub>" "This reverses tangent."
$l7 += T "MLA.GEO.TRI.5" "A zipline has horizontal distance 80 ft and vertical drop 18 ft. Which theorem finds the zipline length?" "Pythagorean Theorem" "The horizontal and vertical distances are legs of a right triangle, so the hypotenuse is found with the Pythagorean Theorem." "AA similarity" "No triangle similarity evidence is needed for this side-length problem." "Reflection symmetry" "No symmetry is involved." "Scale factor only" "No similar figure scale factor is given."
$l7 += T "MLA.GEO.TRI.5" "A right-triangle application gives an acute angle, adjacent side, and asks for hypotenuse. Which trig ratio uses adjacent and hypotenuse?" "Cosine" "Cosine is adjacent over hypotenuse." "Sine" "Sine uses opposite and hypotenuse." "Tangent" "Tangent uses opposite and adjacent." "Pythagorean only" "A trig ratio is appropriate because an angle is given."
$l7 += T "MLA.GEO.TRI.5" "A surveyor knows the angle of elevation and horizontal distance to a tree. Which side is the tree height?" "Opposite side" "The height is across from the angle of elevation." "Adjacent side" "The horizontal distance is adjacent to the angle." "Hypotenuse" "The line of sight is the hypotenuse." "Right angle" "The height is a side length, not an angle."
$l7 += T "MLA.GEO.TRI.5" "A 30-ft ladder reaches 24 ft up a wall. How far is the ladder base from the wall?" "18 ft" "The ladder is the hypotenuse: x<sup>2</sup> + 24<sup>2</sup> = 30<sup>2</sup>, so x = 18." "6 ft" "Subtracting 24 from 30 ignores squared lengths." "54 ft" "Adding lengths does not solve the right triangle." "&radic;1476 ft" "This adds squares while treating both known values as legs."
$l7 += T "MLA.GEO.TRI.5" "A diagonal of a square is 10&radic;2 units. What is the side length?" "10 units" "For a square, the diagonal is side times &radic;2, so the side is 10." "20 units" "This doubles the coefficient and does not reverse the diagonal relationship." "5 units" "This halves the coefficient without using the &radic;2 relationship." "10&radic;2 units" "That is the diagonal, not the side length."
$l7 += T "MLA.GEO.TRI.5" "A right triangle has hypotenuse 50 and one leg 14. Which setup finds the other leg x?" "x<sup>2</sup> + 14<sup>2</sup> = 50<sup>2</sup>" "The known leg and missing leg squares add to the hypotenuse square." "x<sup>2</sup> + 50<sup>2</sup> = 14<sup>2</sup>" "This incorrectly treats 14 as the hypotenuse." "x + 14 = 50" "The Pythagorean relationship uses squares." "14x = 50" "Multiplying a leg by the missing leg is not the theorem."
$l7 += T "MLA.GEO.TRI.5" "A right-triangle problem gives opposite and adjacent sides and asks for an angle. Which ratio should be used?" "Tangent" "Tangent uses opposite and adjacent." "Sine" "Sine uses opposite and hypotenuse." "Cosine" "Cosine uses adjacent and hypotenuse." "Scale factor" "Scale factor is not the trig ratio for opposite and adjacent."
$l7 += T "MLA.GEO.TRI.5" "Why should units be included in right-triangle application answers?" "They explain what the measurement represents." "Units connect the numerical answer back to the real context." "They change the triangle shape." "Units label measurements but do not change geometry." "They replace calculations." "Calculations are still needed." "They prove similarity." "Units do not prove similarity."

# Unit assessment: combine distinct coverage items, first 40 from varied pools
$ua = @()
$ua += $l2[0..7]
$ua += $l3[0..7]
$ua += $l4[0..7]
$ua += $l5[0..5]
$ua += $l6[0..5]
$ua += $l7[0..3]

BuildGift $l1 "GEOMETRY/Units/Unit 04/Lesson 01/GEO_U04_L01_Quiz.gift" "GEO_U04_L01" 25
BuildGift $l2 "GEOMETRY/Units/Unit 04/Lesson 02/GEO_U04_L02_Quiz.gift" "GEO_U04_L02" 25
BuildGift $l3 "GEOMETRY/Units/Unit 04/Lesson 03/GEO_U04_L03_Quiz.gift" "GEO_U04_L03" 25
BuildGift $l4 "GEOMETRY/Units/Unit 04/Lesson 04/GEO_U04_L04_Quiz.gift" "GEO_U04_L04" 25
BuildGift $l5 "GEOMETRY/Units/Unit 04/Lesson 05/GEO_U04_L05_Quiz.gift" "GEO_U04_L05" 25
BuildGift $l6 "GEOMETRY/Units/Unit 04/Lesson 06/GEO_U04_L06_Quiz.gift" "GEO_U04_L06" 25
BuildGift $l7 "GEOMETRY/Units/Unit 04/Lesson 07/GEO_U04_L07_Quiz.gift" "GEO_U04_L07" 25
BuildGift $ua "GEOMETRY/Units/Unit 04/Lesson 08/GEO_U04_UnitAssessment.gift" "GEO_U04_UA" 40

Write-Output "fixed unit 4 repeated assessment stems"
