const fs=require('fs'), path=require('path');
const root=__dirname, cw=path.join(root,'Crosswalk'), xmlDir=path.join(root,'Moodle XML');
const clean=s=>s.replace(/â€”/g,'—').replace(/â€“/g,'–').replace(/â€™/g,'’').trim();
const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
function one(s,r){const m=s.match(r);return m?clean(m[1]):''}
function vocab(s){const a=s.indexOf('Required Vocabulary'),b=s.indexOf('Required Evidence and Visuals',a);const z=s.slice(a,b>0?b:s.length),out=[];for(const l of z.split(/\r?\n/)){const p=l.split('\t');if(p.length>1&&!/^Term$/i.test(p[0]))out.push([clean(p[0]),clean(p.slice(1).join(' '))]);}return out;}
function answer(text,ok){return `<answer fraction="${ok?100:0}" format="html"><text><![CDATA[${text}]]></text><feedback format="html"><text><![CDATA[${ok?'Correct.':'Review the lesson evidence and reasoning.'}]]></text></feedback></answer>`}
function question(id,stem,choices,correct,tag){const order=[0,1,2,3].map(i=>(i+id.length)%4);const arranged=order.map(i=>choices[i]);const newCorrect=arranged.indexOf(choices[correct]);return `<question type="multichoice"><name><text>${esc(id)}</text></name><questiontext format="html"><text><![CDATA[${stem}]]></text></questiontext><generalfeedback format="html"><text><![CDATA[Use the evidence and vocabulary from the lesson to verify your reasoning.]]></text></generalfeedback><defaultgrade>1.0000000</defaultgrade><penalty>0.3333333</penalty><hidden>0</hidden><single>true</single><shuffleanswers>true</shuffleanswers><answernumbering>ABCD</answernumbering>${arranged.map((x,i)=>answer(x,i===newCorrect)).join('')}<tag><text>${tag}</text></tag></question>`}
function category(name){return `<question type="category"><category><text>$course$/top/${name}</text></category></question>`}
function lessonQuestions(n){const s=fs.readFileSync(path.join(cw,`Lesson ${String(n).padStart(2,'0')}.txt`),'utf8'),v=vocab(s),title=one(s,/Lesson Title\s+(.+)/),iq=one(s,/Investigation Question\s+(.+)/),skill=one(s,/Primary Historical-Thinking Skill\s+(.+)/),qs=[];
 for(let i=0;i<5;i++){const [term,def]=v[i%v.length],wrong=[v[(i+1)%v.length]?.[1],v[(i+2)%v.length]?.[1],v[(i+3)%v.length]?.[1]];qs.push(question(`WH_U03_L${String(n).padStart(2,'0')}_Q${String(i+1).padStart(2,'0')}`,`<p><strong>Foundational content:</strong> Which definition best matches <strong>${esc(term)}</strong>?</p>`,[def,...wrong],0,'foundational'));}
 for(let i=0;i<10;i++){const a=v[(i+2)%v.length],b=v[(i+5)%v.length];const stimulus=`<table border="1" cellpadding="6"><tr><th>Evidence A</th><th>Evidence B</th></tr><tr><td><strong>${esc(a[0])}</strong>: ${esc(a[1])}</td><td><strong>${esc(b[0])}</strong>: ${esc(b[1])}</td></tr></table>`;const choices=[`Both details provide relevant evidence for studying ${esc(title)}.`,`The two details prove that every society developed identically.`,`Neither detail can be used as historical evidence.`,`The details show that chronology and context never matter.`];qs.push(question(`WH_U03_L${String(n).padStart(2,'0')}_Q${String(i+6).padStart(2,'0')}`,`<p><strong>Source/visual interpretation:</strong></p>${stimulus}<p>Which conclusion is best supported by the evidence table?</p>`,choices,0,'interpretation'));}
 for(let i=0;i<10;i++){const a=v[(i+1)%v.length],b=v[(i+4)%v.length];const choices=[`Use ${esc(a[0])} and ${esc(b[0])} as specific evidence, then explain how they support a claim.`,`List the two terms without explaining their relationship.`,`Assume one detail proves every part of the Investigation Question.`,`Ignore evidence that might limit the claim.`];qs.push(question(`WH_U03_L${String(n).padStart(2,'0')}_Q${String(i+16).padStart(2,'0')}`,`<p><strong>Application and historical reasoning:</strong> A student is answering: “${esc(iq)}”</p><p>Which approach best demonstrates <strong>${esc(skill)}</strong> and Claim-Evidence-Reasoning?</p>`,choices,0,'application_reasoning'));}
 return {title,qs};}
fs.mkdirSync(xmlDir,{recursive:true}); const banks=[];
for(let n=1;n<=7;n++){const b=lessonQuestions(n);banks.push(b);const body=`<?xml version="1.0" encoding="UTF-8"?><quiz>${category(`WH U03 L${String(n).padStart(2,'0')} Quiz Bank`)}${b.qs.join('')}</quiz>`;fs.writeFileSync(path.join(xmlDir,`WH_U03_L${String(n).padStart(2,'0')}_Quiz_MoodleXML.xml`),body);fs.writeFileSync(path.join(root,`Lesson ${String(n).padStart(2,'0')}`,'quiz.json'),JSON.stringify({format:'Moodle XML',lesson_quiz:`WH_U03_L${String(n).padStart(2,'0')}_Quiz_MoodleXML.xml`,pool_size:25,delivered:5,passing_score:80,distribution:{foundational:5,interpretation:10,application_reasoning:10}},null,2)+'\n');}
fs.writeFileSync(path.join(root,'Lesson 08','quiz.json'),JSON.stringify({lesson_quiz:null,unit_assessment_replaces_quiz:true},null,2)+'\n');
const pre=[];for(let i=0;i<10;i++){const l=i%7,src=banks[l].qs[i%25].replace(/WH_U03_L\d\d_Q\d\d/,`WH_U03_PRE_Q${String(i+1).padStart(2,'0')}`);pre.push(src);}fs.writeFileSync(path.join(xmlDir,'WH_U03_Pretest_MoodleXML.xml'),`<?xml version="1.0" encoding="UTF-8"?><quiz>${category('WH U03 Pretest')}${pre.join('')}</quiz>`);
const dist=[5,5,5,6,6,6,7],unit=[];for(let l=0;l<7;l++)for(let i=0;i<dist[l];i++)unit.push(banks[l].qs[(i*4+l)%25].replace(/WH_U03_L\d\d_Q\d\d/,`WH_U03_UA_L${l+1}_Q${String(i+1).padStart(2,'0')}`));fs.writeFileSync(path.join(xmlDir,'WH_U03_UnitAssessment_MoodleXML.xml'),`<?xml version="1.0" encoding="UTF-8"?><quiz>${category('WH U03 Unit Assessment')}${unit.join('')}</quiz>`);
for(const f of fs.readdirSync(xmlDir))if(/GuidedPractice/.test(f))fs.unlinkSync(path.join(xmlDir,f));
console.log('Built seven 25-question lesson banks, 10-question pretest, and 40-question Unit 3 assessment pool.');
