/* Curated student-facing content profiles for the Biology rebuild.
 * Each profile carries the biological substance used by lessons and assessments.
 * Facts are deliberately concrete so the generator never falls back to generic
 * "use evidence" language.
 */

function p(bridge, why, next, visual, vocab, steps, facts) {
  return { bridge, why, next, visual, vocab, steps, facts };
}

const profiles = {
  U01L01: p(
    'You already observe patterns and make explanations every day. Biology makes that thinking testable and evidence-based.',
    'This skill helps you judge health, environmental, and product claims instead of being persuaded by confidence alone.',
    'Next, you will turn a testable biology question into a fair investigation with clearly defined variables.',
    'evidence',
    [['observation','a description or measurement obtained with senses or tools'],['inference','an interpretation based on one or more observations'],['testable question','a question answered by collecting measurable evidence'],['claim','a direct answer to a scientific question'],['evidence','a specific observation or value that supports or challenges a claim'],['reasoning','the biology principle that explains why the evidence matters']],
    ['Separate what was directly seen or measured from what was interpreted.','Rewrite broad questions so the variable and measurable outcome are named.','Select evidence that directly addresses the question; interesting details are not automatically relevant.','Write a claim, cite exact evidence, and explain the biological connection without exceeding the evidence.'],
    [['Seedling observation','Seedling A is 8.2 cm tall after 7 days; Seedling B is 5.1 cm.','A is taller under the recorded conditions, but height alone does not prove it is healthier.'],['Pond micrograph','Twenty-four oval cells appear in the field of view.','The count is an observation; calling them a new species would require more evidence.'],['Testable question','How does daily light duration affect mean radish height after 14 days?','Light duration is changed and mean height is measurable.'],['Yeast data','At 20°C, 12 bubbles/min formed; at 30°C, 28; at 40°C, 5.','The data support an optimum near 30°C among the tested temperatures.'],['Scientific boundary','A claim must be open to testing with observations or measurements.','Claims that cannot be tested scientifically are not answered by biology methods.'],['CER limit','One short investigation supports a bounded conclusion, not a universal law.','A strong explanation states what the evidence can and cannot establish.']]
  ),
  U01L02: p(
    'Lesson 1 showed how to ask a measurable question and match evidence to it.',
    'Fair-test design helps you evaluate claims about foods, cleaners, medicines, and growing conditions.',
    'Next, you will collect measurements safely and decide whether the resulting data are trustworthy.',
    'experiment',
    [['independent variable','the factor deliberately changed'],['dependent variable','the outcome measured'],['control variable','a condition kept the same'],['control group','a comparison group without the tested treatment'],['trial','one complete repetition of a procedure'],['confounding variable','an uncontrolled difference that could explain the result']],
    ['Start with one measurable cause-and-effect question.','Name the independent variable, dependent variable, comparison group, and constants before writing the procedure.','Use repeated trials and one change at a time so differences can be attributed to the tested factor.','Write numbered, safe steps and prepare a data table with units before collecting data.'],
    [['Radish light study','Light duration is 4, 8, or 12 h/day; mean height after 14 days is measured.','Light duration is the independent variable and mean height is the dependent variable.'],['Fair comparison','All trays use the same seed type, soil mass, water volume, pot size, and temperature.','Keeping these conditions constant reduces alternative explanations.'],['Repeated trials','Ten seedlings are grown in each light condition.','Replication reveals variation and makes one unusual seedling less influential.'],['Confounded design','The 12-hour tray also receives twice as much water.','Light and water both change, so the cause of a height difference cannot be isolated.'],['Safe procedure','Use a virtual or teacher-approved investigation and record data without tasting or handling unknown materials.','Safety requirements are part of valid procedure design.'],['Data table','Columns are light (h/day), trial number, height (cm), and mean height (cm).','Headings identify the variable, measurement, unit, and summary.']]
  ),
  U01L03: p(
    'Lesson 2 produced a fair plan. A fair plan still fails if tools are misread or unsafe steps change the data.',
    'Measurement quality matters in medicine doses, food safety, water testing, and every evidence-based decision.',
    'Next, you will use microscopes and models to extend observations beyond unaided senses.',
    'measurement',
    [['accuracy','closeness to an accepted value'],['precision','closeness of repeated measurements to one another'],['resolution','smallest change a tool can distinguish'],['outlier','a value far from the overall pattern'],['uncertainty','the reasonable range around a measurement'],['mean','sum of values divided by the number of values']],
    ['Identify the hazard before choosing a precaution and tool.','Read the scale at eye level, record the correct unit, and estimate one place beyond the smallest marked division when appropriate.','Repeat measurements and organize every value before calculating a mean or range.','Investigate an outlier; do not erase it merely because it is inconvenient.'],
    [['Graduated cylinder','The meniscus bottom is halfway between 36 and 37 mL.','Record 36.5 mL when the scale supports tenths.'],['Replicates','Leaf lengths are 6.1, 6.2, 6.1, 9.8, and 6.2 cm.','9.8 cm is an outlier to check, not automatically delete.'],['Mean','Measurements 12.0, 12.2, and 12.1 cm have a mean of 12.1 cm.','The mean summarizes the center of repeated values.'],['Accuracy versus precision','Values 8.1, 8.1, 8.2 are tightly grouped when the accepted value is 10.0.','They are precise but not accurate.'],['Safety','Broken glass is reported and left for approved cleanup.','Picking it up by hand adds injury risk and can contaminate evidence.'],['Uncertainty','A ruler marked every millimeter cannot justify a length of 4.236781 cm.','Reported precision must match the tool.']]
  ),
  U01L04: p(
    'Lesson 3 established how to choose and read measurement tools. Microscopes are tools for structures too small to see unaided.',
    'Microscopy supports medical diagnosis, cell research, food safety, and water-quality monitoring.',
    'Next, you will judge whether tool-produced observations and sources support a scientific claim.',
    'microscope',
    [['ocular lens','the eyepiece, commonly 10×'],['objective lens','a rotating lens that provides additional magnification'],['total magnification','ocular magnification multiplied by objective magnification'],['field of view','the circular area visible through the microscope'],['resolution','ability to distinguish close details'],['model','a purposeful representation that shows selected features']],
    ['Carry a microscope by the arm and base; begin with the lowest-power objective.','Center and focus the specimen at low power before switching higher; use fine focus at high power.','Calculate total magnification by multiplying ocular and objective powers.','Describe visible features as observations, then clearly label interpretations as inferences and state model limits.'],
    [['Magnification','A 10× ocular and 40× objective produce 400× total magnification.','Multiply lens powers; do not add them.'],['Field of view','Moving from 40× to 400× shows less of the specimen but more detail.','Higher magnification narrows the visible area.'],['Onion cells','Repeated rectangular boundaries are visible in a micrograph.','The boundaries are observations; identifying cell walls uses prior biological knowledge.'],['Model limit','A colored cell drawing clearly labels organelles but is not to scale.','The model helps locate parts but cannot support exact size comparisons.'],['Tool choice','A compound light microscope can show whole cells; an electron micrograph resolves smaller structures.','Choose a tool whose resolution matches the question.'],['Observation/inference','Several dark circular structures are visible; they may be nuclei.','The first statement describes evidence; the second interprets it.']]
  ),
  U01L05: p(
    'Lessons 3 and 4 produced measurements and images. Now you must decide whether a source and design deserve trust.',
    'Source evaluation helps you avoid misinformation in health, purchasing, and community decisions.',
    'Next, you will see how many reliable observations accumulated into cell theory.',
    'sources',
    [['reliable source','a source with relevant expertise, transparent evidence, and methods that can be checked'],['corroboration','independent evidence that agrees with a finding'],['bias','a preference or incentive that may influence a claim or method'],['alternative explanation','another mechanism that could produce the observation'],['correlation','two variables change together'],['causation','one variable produces change in another']],
    ['State the exact claim before judging its support.','Check author expertise, date, method, sample, data, conflicts, and whether other reliable sources agree.','Compare the claim with the actual pattern; correlation alone does not prove cause.','Consider alternatives and revise broad claims so they match the evidence and limitations.'],
    [['Source A','A university extension report names researchers, methods, sample size, and complete data.','Its transparent evidence can be checked.'],['Source B','An influencer sells the tested supplement and provides testimonials but no method.','The conflict and missing evidence weaken reliability.'],['Lake data','Nitrate rose from 0.4 to 2.1 mg/L while algae density tripled after runoff events.','The pattern supports an association; controlled evidence is needed for causation.'],['Alternative','Water temperature also increased during the algae bloom.','Temperature is a competing explanation to evaluate.'],['Corroboration','Three independent monitoring teams report the same nitrate pattern.','Agreement from independent sources strengthens confidence.'],['Bounded claim','Runoff is a supported contributor to this bloom under the measured conditions.','This wording matches evidence better than claiming runoff always causes every bloom.']]
  ),
  U01L06: p(
    'Microscopes made cells observable, and source evaluation showed how independent evidence becomes trustworthy.',
    'Cell theory explains growth, infection, healing, and why a scientific theory is much stronger than a guess.',
    'Next, the unit investigation connects scientific evidence, cell theory, water, and life’s major molecules.',
    'cellTheory',
    [['cell theory','the evidence-supported explanation that organisms are cellular, cells are basic units of life, and cells arise from cells'],['theory','a broad explanation repeatedly supported by evidence'],['law','a description of a consistent natural pattern'],['model','a representation used to explain or predict selected features'],['microscopy','use of microscopes to observe small structures'],['replication','repetition of observations or investigations']],
    ['Connect each historical observation to the specific cell-theory statement it supports.','Explain how improved tools expanded evidence from cork to living cells, tissues, and cell division.','Distinguish a model of one cell from cell theory, which explains evidence across living systems.','Treat theories as revisable, evidence-rich explanations—not guesses that become laws.'],
    [['Hooke, 1665','Cork contained repeating boxlike compartments he called cells.','This added early evidence of cellular structure.'],['Leeuwenhoek','Living single-celled organisms were observed in water.','Cells were shown to be living units, not only empty cork spaces.'],['Schleiden and Schwann','Plant and animal tissues were consistently made of cells.','Evidence across kingdoms supported that all organisms are cellular.'],['Virchow','Cell division observations showed new cells forming from existing cells.','This supports the third statement of cell theory.'],['Cell model','A diagram labels nucleus, membrane, and cytoplasm.','It represents selected features but is not cell theory itself.'],['Theory status','New evidence can refine a theory without making the theory “just a guess.”','Scientific theories explain broad evidence and remain open to revision.']]
  ),
  U01L07: p(
    'Lessons 1–6 built the complete investigation chain: question, design, safe measurement, tool use, source judgment, and cell theory.',
    'Water and carbon-based molecules allow cells to transport materials, form membranes, perform work, and store information.',
    'Next, you will synthesize the full evidence chain and decide what each type of evidence can support.',
    'foundationsLab',
    [['polarity','uneven distribution of electrical charge'],['hydrogen bond','attraction between partially charged regions of nearby water molecules'],['macromolecule','a large biological molecule such as carbohydrate, lipid, protein, or nucleic acid'],['variable','a factor changed, measured, or controlled'],['pattern','a meaningful relationship in observations or data'],['limitation','a condition that restricts what a conclusion can establish']],
    ['Read the investigation question, identify the comparison, and predict what evidence would answer it.','Use the supplied water and macromolecule models; record observations before interpretations.','Calculate changes, graph the provided data, and compare patterns across sources.','Write a bounded conclusion using exact values, cell-theory evidence, molecular function, and one limitation.'],
    [['Water polarity','Oxygen is partially negative and hydrogens are partially positive.','Polarity helps water dissolve and transport charged substances.'],['Temperature data','Equal samples change 8°C in water and 21°C in oil after heating.','Water moderates temperature change more strongly in this comparison.'],['Carbohydrate','Glucose units provide readily available chemical energy.','Structure and bonds support short-term cellular energy needs.'],['Lipid','Phospholipids have water-attracting heads and water-avoiding tails.','They self-organize into cell membranes.'],['Protein','A folded amino-acid chain forms a specific working shape.','Shape enables transport, signaling, structure, or enzyme function.'],['Nucleic acid','A nucleotide sequence stores biological information.','DNA instructions can be copied and used to build proteins.']]
  ),
  U01L08: p(
    'The Lesson 7 investigation connected inquiry, data quality, cells, water, and molecules in one evidence chain.',
    'Real biological decisions require you to integrate a question, method, evidence quality, and mechanism—not recall isolated words.',
    'Unit 2 begins by comparing the cell types introduced by cell theory.',
    'synthesis1',
    [['synthesis','combining related evidence into one coherent explanation'],['validity','how well a method and evidence address the intended question'],['reliability','consistency of a result across repeated measurements or sources'],['mechanism','the process that explains how a result occurs'],['constraint','a boundary or limitation on a model or conclusion']],
    ['Unpack the question and select only evidence that addresses it.','Check design, safety, measurement, tool, and source quality before interpreting a pattern.','Connect observed evidence to cell theory and molecular mechanisms.','Compare alternatives and state a conclusion with a clear boundary.'],
    [['Pond micrograph','Many bounded cellular units are visible.','The image supports cellular organization but not every molecular function.'],['Nitrate table','Nitrate is higher downstream after rain.','This pattern is relevant to a runoff claim.'],['Source card','Methods, dates, and raw measurements are provided.','Transparency raises confidence because the evidence is checkable.'],['Water model','Partial charges explain attraction to ions.','The model supplies a mechanism for transport in cells.'],['Macromolecule model','Lipids form a boundary while proteins perform specific work.','Different molecular structures support different cellular functions.'],['Synthesis limit','A short simulated case cannot establish a universal ecosystem rule.','The response should remain within the packet evidence.']]
  ),

  U02L01: p(
    'Cell theory says all organisms are made of cells. The next question is how cell types are alike and different.',
    'Cell comparison explains why antibiotics can target bacteria differently from human cells and why plant cells perform photosynthesis.',
    'Next, you will connect each labeled organelle to the job it performs.',
    'cellCompare',
    [['prokaryotic cell','a cell without a nucleus or other membrane-bound organelles'],['eukaryotic cell','a cell with a nucleus and membrane-bound organelles'],['nucleoid','the non-membrane-bound region containing prokaryotic DNA'],['cell wall','a rigid outer layer that supports and protects some cells'],['chloroplast','a plant organelle that captures light energy'],['central vacuole','a large plant compartment that stores water and supports pressure']],
    ['First locate DNA: a nucleus means eukaryotic; a nucleoid without a nucleus means prokaryotic.','If the cell is eukaryotic, look for a cell wall, chloroplasts, and a large central vacuole to identify a plant cell.','Identify shared structures—membrane, cytoplasm, DNA, and ribosomes—before unique structures.','Classify with visible structural evidence, then connect at least one structure to its function.'],
    [['Bacterial cell','DNA lies in a nucleoid; a membrane, ribosomes, and cell wall are present; no nucleus is present.','The missing nucleus identifies a prokaryotic cell.'],['Plant cell','A nucleus, cell wall, chloroplasts, and large central vacuole are visible.','These structures identify a plant eukaryotic cell.'],['Animal cell','A nucleus and flexible membrane are visible; there is no cell wall or chloroplast.','These features identify an animal eukaryotic cell.'],['Shared structure','All three cell types have a plasma membrane and ribosomes.','All cells regulate a boundary and build proteins.'],['Scale','A typical bacterium is much smaller than a typical plant or animal cell.','Cell drawings are often not drawn to the same scale.'],['Evidence rule','Shape alone is weaker evidence than labeled internal structures.','A rectangular-looking cell without a visible wall is not automatically a plant cell.']]
  ),
  U02L02: p(
    'Lesson 1 identified plant and animal cells by their structures. Now each part becomes a structure–function explanation.',
    'Organelle functions explain how cells make proteins, transfer energy, move materials, and survive.',
    'Next, you will focus on the plasma membrane and how substances cross it.',
    'organelles',
    [['organelle','a specialized cell structure with a specific function'],['nucleus','stores DNA and regulates gene access'],['ribosome','builds proteins from amino acids'],['rough ER','folds and transports many proteins'],['Golgi apparatus','modifies, sorts, and packages cell products'],['mitochondrion','transfers energy from food molecules to ATP'],['lysosome','contains enzymes that break down materials']],
    ['Locate the organelle in the cell model.','Describe a visible structural feature before naming its function.','Connect the organelle’s function to a whole-cell need.','Predict what accumulates, decreases, or fails when the organelle malfunctions.'],
    [['Protein export','Nucleus information is read at ribosomes; rough ER folds the protein; Golgi modifies and packages it.','The pathway coordinates multiple organelles.'],['Mitochondrion','The highly folded inner membrane provides space for energy-transfer reactions.','Cells with high energy demand often contain many mitochondria.'],['Central vacuole','Water stored in the vacuole presses outward against the cell wall.','This helps plant tissues remain firm.'],['Chloroplast','Internal membranes contain pigments that capture light energy.','The structure supports photosynthesis.'],['Lysosome failure','Damaged molecules and worn organelles accumulate.','Breakdown and recycling functions are disrupted.'],['Ribosome','Both prokaryotic and eukaryotic cells contain ribosomes.','All cells need protein synthesis even though prokaryotes lack membrane-bound organelles.']]
  ),
  U02L03: p(
    'Lesson 2 identified the plasma membrane as the selective boundary of every cell.',
    'Membrane transport explains hydration, IV saline, food preservation, kidney function, and why cells swell or shrink.',
    'Next, you will connect transport to homeostasis in cells and whole organisms.',
    'membrane',
    [['selective permeability','allowing some substances to cross more readily than others'],['concentration gradient','a difference in amount across space'],['diffusion','net movement from higher to lower concentration'],['osmosis','diffusion of water across a selectively permeable membrane'],['facilitated diffusion','passive movement through a membrane protein'],['active transport','movement against a gradient using cellular energy']],
    ['Identify the substance and compare its concentration on both sides of the membrane.','Draw the net movement arrow from high to low concentration unless energy drives movement against the gradient.','Check whether the substance crosses the bilayer, uses a channel, or uses an ATP-powered pump.','Name the transport process and predict how the movement affects cell water or solute balance.'],
    [['Simple diffusion','Oxygen moves from 18 units outside to 5 units inside through the bilayer.','Movement down the gradient requires no ATP.'],['Facilitated diffusion','Glucose moves from high to low concentration through a carrier protein.','The protein assists passive movement.'],['Osmosis','Water moves toward the side with more dissolved solute when solute cannot cross.','Water movement changes cell volume.'],['Active transport','A pump moves sodium from 4 units inside to 14 units outside while ATP becomes ADP.','Movement against the gradient requires energy.'],['Hypertonic solution','A cell loses water and shrinks when the outside has more nonpenetrating solute.','Osmosis changes cell water balance.'],['Dynamic equilibrium','Particles continue moving, but no net concentration change occurs.','Equilibrium does not mean particles stop.']]
  ),
  U02L04: p(
    'Lesson 3 showed how membranes move water and solutes. Homeostasis uses those movements and feedback to keep conditions within workable ranges.',
    'Temperature, blood glucose, and water balance must be regulated continuously for cells to function.',
    'Next, you will trace transport and regulation through roots, stems, and leaves.',
    'feedback',
    [['homeostasis','maintenance of internal conditions within functional ranges'],['stimulus','a detectable change in a condition'],['receptor','a structure that detects change'],['control center','a system component that compares information with a target range'],['effector','a structure that carries out a response'],['negative feedback','a response that reduces the original change']],
    ['Identify the regulated condition and its normal range.','Trace stimulus to receptor, control center, effector, and response.','Explain how the response moves the condition back toward the range.','Use a graph to decide whether regulation succeeds, overshoots, or fails.'],
    [['Body temperature','Temperature rises above range; sweating and skin blood flow increase.','Heat loss reduces the original increase.'],['Blood glucose','After a meal, glucose rises and cells increase glucose uptake.','The response moves glucose back toward its range.'],['Water balance','Concentrated body fluids trigger increased water conservation by kidneys.','Less water loss opposes dehydration.'],['RBC isotonic','Water enters and leaves at equal average rates.','Cell volume stays near stable even though molecules move.'],['Failed feedback','A graph remains far above the target range after a response should begin.','The regulation did not restore homeostasis.'],['Homeostasis boundary','Homeostasis maintains ranges, not perfectly unchanging values.','Small fluctuations are normal in a regulated system.']]
  ),
  U02L05: p(
    'Osmosis and homeostasis explain how plant cells take up water and keep tissues firm.',
    'Plant transport affects food production, drought response, gardening, and climate resilience.',
    'Next, you will compare coordinated plant transport with nervous, cardiovascular, and immune functions in humans.',
    'plant',
    [['root hair','a root cell extension that increases absorption area'],['xylem','vascular tissue that carries water and minerals mainly upward'],['phloem','vascular tissue that transports sugars from sources to sinks'],['stoma','an adjustable pore for gas exchange and water loss'],['transpiration','evaporation of water from plant surfaces'],['guard cell','a cell that changes shape to regulate a stoma']],
    ['Trace water from soil into root hairs by osmosis.','Follow water and minerals upward through xylem to leaves.','At stomata, connect carbon dioxide entry with water-vapor loss and guard-cell regulation.','Trace sugars made in leaves through phloem to growing or storage tissues.'],
    [['Root hair','Its long extension contacts more soil water.','Greater surface area supports absorption.'],['Xylem','Dyed water appears in stem xylem and later leaf veins.','The observation traces the water pathway.'],['Stoma','Open pores increase carbon dioxide entry but also water loss.','Gas exchange has a water-balance tradeoff.'],['High humidity','Transpiration rate is lower when the air already contains more water vapor.','A smaller gradient reduces evaporation.'],['Phloem','Sugars move from a photosynthesizing leaf to roots and fruits.','Phloem connects sources with sinks.'],['Wilt','Water loss exceeds water uptake, reducing vacuole pressure.','Cells lose firmness even if cell walls remain present.']]
  ),
  U02L06: p(
    'Plant organs coordinate transport and regulation. Human organs also work in connected systems to maintain life.',
    'Nervous signals, circulation, and immunity explain pulse, reflexes, oxygen delivery, infection response, and vaccination.',
    'Next, the unit investigation connects cell transport, homeostasis, plants, human systems, pathogens, and immunity.',
    'systems',
    [['neuron','a cell specialized to transmit information'],['reflex','a rapid automatic response to a stimulus'],['artery','a vessel that carries blood away from the heart'],['capillary','a thin vessel where materials exchange with tissues'],['pathogen','a biological agent capable of causing disease'],['antibody','a protein that binds a specific target marker']],
    ['Trace a nervous pathway from receptor to processing center to motor response.','Trace blood through heart, arteries, capillaries, and veins while identifying material exchange.','Separate barriers, rapid nonspecific responses, and specific immune responses.','Explain how systems cooperate—for example, circulation transports oxygen and immune cells to tissues.'],
    [['Reflex','A heat receptor sends a signal to the spinal cord, which activates an arm muscle.','The rapid pathway reduces injury before conscious processing finishes.'],['Circulation','Oxygen leaves capillaries and enters tissue cells down a concentration gradient.','Thin capillary walls support exchange.'],['Heart','Pumping creates pressure that moves blood through vessels.','Structure and contraction support transport.'],['Barrier defense','Intact skin blocks many pathogens before they enter tissues.','This is a first-line physical defense.'],['Specific response','Antibody concentration rises faster after a second exposure to the same marker.','Immune memory supports a more rapid response.'],['System cooperation','Inflammation increases local blood flow and brings immune cells to an injury.','Cardiovascular and immune systems coordinate.']]
  ),
  U02L07: p(
    'Lessons 1–6 connected cell structures to organelles, membranes, homeostasis, plant transport, human systems, and health.',
    'This investigation shows how cellular mechanisms scale up to hydration, plant function, infection prevention, and immune response.',
    'Next, you will synthesize the complete structure–function–regulation chain.',
    'cellsLab',
    [['tonicity','the effect of a solution on cell water movement'],['transmission','movement of a pathogen from one host or source to another'],['immune memory','faster, stronger specific response after prior exposure'],['control condition','a comparison without the tested change'],['model limitation','a feature a model simplifies or omits'],['percent change','difference divided by the original value, multiplied by 100']],
    ['Station A: classify actual displayed cell models using nucleus, wall, chloroplast, and nucleoid evidence.','Station B: compare solute concentrations, predict osmosis, and calculate red-blood-cell volume change.','Station C: graph stomatal or transpiration data and connect the trend to plant water balance.','Station D: calculate transmission and interpret first- versus second-exposure antibody graphs before writing a multi-source conclusion.'],
    [['Unknown cell A','No nucleus; nucleoid, membrane, ribosomes, and wall are shown.','Classify it as prokaryotic.'],['Saline data','RBC volume changes from 90 to 72 fL in concentrated saline.','The 20% decrease shows net water loss.'],['Plant data','Transpiration falls from 6.2 to 2.1 mL/h as humidity rises.','The gradient for water loss becomes smaller.'],['Transmission','8 of 40 exposed people become infected versus 2 of 40 with prevention.','Rates are 20% and 5%; the difference supports reduced transmission.'],['Antibody graph','The second-exposure response begins earlier and reaches a higher peak.','The pattern is consistent with immune memory.'],['Limitation','Models omit many interacting tissues and individual differences.','Conclusions should address the displayed mechanisms only.']]
  ),
  U02L08: p(
    'The Lesson 7 stations connected structures and transport across cells, plants, human systems, and health evidence.',
    'Understanding biological organization helps you connect everyday health and environmental observations to mechanisms rather than memorized labels.',
    'Unit 3 begins with water and macromolecules—the materials that build cell structures and support cell work.',
    'synthesis2',
    [['structure–function relationship','an explanation of how a feature enables a biological job'],['regulation','control of a condition or process'],['system','interacting parts that produce a larger function'],['response','a biological change produced after a stimulus'],['transfer','application of learned reasoning to a new case']],
    ['Identify the biological level shown: molecule, organelle, cell, tissue, organ, or system.','Interpret each diagram or graph before connecting across levels.','Link structure to function, transport to regulation, and regulation to health or organism function.','Test the explanation on a new case and state what the evidence cannot establish.'],
    [['Cell identity','A wall and chloroplasts identify a plant cell.','Classification begins with visible structures.'],['Organelle function','Many mitochondria support high ATP demand.','Structure abundance connects to cell work.'],['Membrane movement','A water gradient changes cell volume.','Transport can disrupt or restore homeostasis.'],['Plant pathway','Root uptake, xylem transport, stomata, and phloem coordinate.','Multiple organs support matter movement.'],['Human pathway','Circulation supplies tissues and transports immune components.','Systems cooperate to maintain function.'],['Health evidence','Transmission and antibody data support bounded prevention and immunity claims.','Data do not diagnose an individual.']]
  ),

  U03L01: p(
    'Unit 2 showed that cells need membranes, transport proteins, genetic information, and usable energy. Those functions depend on water and carbon-based molecules.',
    'Hydration, nutrition labels, body temperature, medicine transport, and cell survival all depend on molecular structure.',
    'Next, you will examine proteins that act as enzymes and learn why their shape and conditions control reactions.',
    'macromolecules',
    [['polarity','uneven charge distribution in a molecule'],['cohesion','attraction between molecules of the same substance'],['monomer','a small building block of a larger molecule'],['polymer','a large molecule built from repeating units'],['carbohydrate','a molecule used for immediate energy and some structures'],['lipid','a mostly nonpolar molecule used in membranes and long-term energy storage'],['protein','a folded amino-acid chain with structural or working roles'],['nucleic acid','a nucleotide polymer that stores and transmits information']],
    ['Read the partial charges on water and connect hydrogen bonding to solvent, cohesion, adhesion, and temperature stability.','Identify a macromolecule by both its structural clue and its function—not by function alone.','Connect monomers to polymers: sugars to carbohydrates, amino acids to proteins, nucleotides to nucleic acids.','Locate each molecule in a cell or life process and explain how structure enables function.'],
    [['Water solvent','Partially negative oxygen surrounds positive ions while hydrogens orient toward negative ions.','Polarity helps separate and transport charged particles.'],['Cohesion','Water molecules attract one another through hydrogen bonds.','This supports continuous water columns in plant xylem.'],['Carbohydrate','A chain of sugar rings is broken down for quick cellular fuel.','The model and function identify a carbohydrate.'],['Phospholipid','A charged head and two nonpolar tails form a bilayer in water.','Amphipathic structure supports membranes.'],['Protein','A folded amino-acid chain has a specific binding pocket.','Shape supports a specialized function.'],['Nucleic acid','A sequence of nucleotides contains ordered bases.','Base order stores biological information.']]
  ),
  U03L02: p(
    'Lesson 1 introduced proteins. Some proteins are enzymes that speed chemical reactions without being used up.',
    'Enzyme conditions matter in digestion, fever, food preservation, and metabolism.',
    'Next, you will learn how ATP transfers usable energy to cell processes, many of which are enzyme-controlled.',
    'enzyme',
    [['enzyme','a biological catalyst that lowers activation energy'],['substrate','the reactant that binds an enzyme'],['active site','the enzyme region where a substrate binds'],['activation energy','minimum energy needed to begin a reaction'],['optimum','the condition producing the greatest measured rate'],['denaturation','loss of functional protein shape']],
    ['Follow substrate binding, reaction, product release, and enzyme reuse on the model.','Compare activation-energy curves with and without the enzyme.','Read pH and temperature axes and identify the tested optimum from data.','Distinguish reversible rate changes from loss of active-site shape and avoid extending beyond tested conditions.'],
    [['Specificity','Substrate A fits the active site; substrate B does not.','Active-site shape makes the enzyme selective.'],['Activation energy','The uncatalyzed barrier is 80 kJ/mol and the catalyzed barrier is 35 kJ/mol.','The enzyme lowers the barrier by 45 kJ/mol.'],['Temperature data','Rate rises from 8 units at 15°C to 31 at 37°C, then falls to 4 at 60°C.','37°C is the tested optimum; high heat may alter shape.'],['pH data','Rate peaks at pH 2 for enzyme X and pH 8 for enzyme Y.','Different enzymes can have different optima.'],['Enzyme reuse','The enzyme is unchanged after products leave.','Catalysts can participate again.'],['Overclaim','A graph from pH 2–10 cannot establish behavior at pH 12.','Conclusions remain within the tested range.']]
  ),
  U03L03: p(
    'Enzymes control reactions, but cellular work also needs a rapid way to transfer energy.',
    'Muscle contraction, nerve signaling, active transport, repair, and temperature regulation all use ATP.',
    'Next, you will see how photosynthesis stores light energy in glucose that can recharge ATP.',
    'atp',
    [['ATP','adenosine triphosphate, a molecule that transfers usable energy'],['ADP','adenosine diphosphate, produced when ATP loses a phosphate'],['phosphate','the terminal group transferred during many coupled reactions'],['energy coupling','using energy released by one reaction to drive another'],['cellular work','transport, movement, synthesis, or signaling performed by cells']],
    ['Identify adenine, ribose, and three phosphates on ATP.','Trace ATP → ADP + phosphate and label where usable energy is transferred.','Trace energy input that joins phosphate to ADP and reforms ATP.','Connect ATP cycling to a visible cell job and distinguish rapid transfer from long-term storage.'],
    [['ATP structure','ATP has three phosphates; ADP has two.','Loss of the terminal phosphate accompanies energy transfer.'],['Membrane pump','ATP becomes ADP while a pump moves ions against a gradient.','ATP breakdown is coupled to active transport.'],['Muscle protein','ATP binding and breakdown change protein interactions.','Chemical energy transfer enables movement.'],['Recharge','Energy from food reactions reforms ATP from ADP and phosphate.','ATP is continuously recycled.'],['Storage comparison','Glucose and lipids store much more energy than one ATP molecule.','ATP is an immediate transfer molecule, not the cell’s only energy store.'],['Matter boundary','ATP does not create energy.','It transfers energy released or captured in other processes.']]
  ),
  U03L04: p(
    'ATP must be recharged. Photosynthesis captures light energy and stores part of it in glucose.',
    'Nearly all food energy and much atmospheric oxygen trace back to photosynthesis.',
    'Next, you will follow glucose and oxygen into cellular respiration, where energy is transferred to ATP.',
    'photosynthesis',
    [['photosynthesis','process that uses light energy to build glucose from carbon dioxide and water'],['chloroplast','plant organelle where photosynthesis occurs'],['chlorophyll','pigment that absorbs light energy'],['reactant','a starting substance in a chemical process'],['product','a substance formed by a chemical process'],['limiting factor','a resource or condition that restricts process rate']],
    ['Locate photosynthesis in chloroplasts and distinguish matter inputs from light energy.','Read the equation: 6 CO₂ + 6 H₂O + light → C₆H₁₂O₆ + 6 O₂.','Track carbon from carbon dioxide into glucose and oxygen atoms into products.','Interpret rate data for increase, plateau, and a possible limiting factor without overclaiming.'],
    [['Inputs','Carbon dioxide enters leaves and water arrives through xylem; light is absorbed.','Matter and energy enter the process in different forms.'],['Outputs','Glucose stores chemical energy and oxygen is released.','Products contain rearranged atoms from reactants.'],['Carbon tracking','Six CO₂ molecules supply the six carbons in one glucose.','Plant carbon does not come mainly from soil.'],['Light data','Oxygen rate rises from 2 to 9 units as light increases, then remains near 9.','Another factor becomes limiting at the plateau.'],['Location','Chloroplasts are abundant in photosynthetic leaf cells.','Organelle location connects to plant function.'],['Plant boundary','Plants also perform cellular respiration.','Photosynthesis is not the only energy process in plants.']]
  ),
  U03L05: p(
    'Photosynthesis stores energy in glucose and releases oxygen. Cellular respiration uses those materials to transfer energy to ATP.',
    'Respiration explains why breathing rate rises with exercise and why both animals and plants need cellular fuel.',
    'Next, you will connect photosynthesis and respiration as interdependent matter pathways.',
    'respiration',
    [['cellular respiration','process that transfers energy from glucose to ATP'],['mitochondrion','eukaryotic organelle where much aerobic respiration occurs'],['aerobic','requiring oxygen'],['gas exchange','movement of oxygen and carbon dioxide between organism and environment'],['ATP yield','amount of ATP produced under a condition']],
    ['Locate aerobic respiration in mitochondria and separate it from breathing.','Read the equation: C₆H₁₂O₆ + 6 O₂ → 6 CO₂ + 6 H₂O + energy transferred to ATP.','Track carbon from glucose to carbon dioxide and oxygen into water.','Compare ATP-yield data with and without oxygen and connect the pattern to cell work.'],
    [['Inputs','Cells use glucose and oxygen during aerobic respiration.','These reactants contain matter and enable energy transfer.'],['Outputs','Carbon dioxide and water are matter products.','Atoms are rearranged rather than destroyed.'],['ATP data','Aerobic conditions yield about 30 ATP per glucose in the lesson model; low-oxygen fermentation yields 2.','Oxygen allows much greater ATP yield in this comparison.'],['Exercise','Muscle cells use ATP faster, increasing oxygen demand and carbon dioxide production.','Breathing supports gas exchange; respiration occurs inside cells.'],['Plant cells','Plant mitochondria respire day and night.','Plants both photosynthesize and respire.'],['Energy boundary','Energy is transferred, not created by mitochondria.','Glucose energy is coupled to ATP formation.']]
  ),
  U03L06: p(
    'Lessons 4 and 5 established both equations. Now the outputs of one become inputs of the other in living systems.',
    'This connection explains food–oxygen relationships, plant–animal interdependence, and why matter cycles while energy flows.',
    'Next, the investigation combines water, enzymes, ATP, photosynthesis, respiration, and Earth cycles.',
    'energyLink',
    [['interdependence','mutual reliance among processes or organisms'],['matter cycle','repeated movement and transformation of atoms'],['energy flow','one-way transfer and eventual dispersal of usable energy'],['net exchange','overall movement after opposing processes are combined'],['carbon cycle','movement of carbon among organisms and reservoirs']],
    ['Place both equations side by side and match products with reactants.','Trace carbon, oxygen, and water as matter that can be reused.','Trace light energy into glucose, ATP transfer, biological work, and dispersed heat.','Use day/night gas data to distinguish gross processes from net exchange.'],
    [['Matter link','Photosynthesis produces glucose and oxygen used in respiration.','Respiration produces carbon dioxide and water used in photosynthesis.'],['Energy link','Light energy becomes chemical energy; respiration transfers some to ATP.','Energy flows rather than cycling back to sunlight.'],['Day data','A plant chamber’s CO₂ falls in bright light.','Photosynthesis removes CO₂ faster than respiration adds it.'],['Night data','The chamber’s CO₂ rises in darkness.','Respiration continues while photosynthesis stops without light.'],['Closed chamber','Gas levels can remain balanced briefly with plants and animals.','The model omits waste, nutrients, growth, and long-term losses.'],['Misconception','The processes are related but not simply identical reverse reactions.','They use different pathways and energy transformations.']]
  ),
  U03L07: p(
    'Lessons 1–6 built a system from water and molecules to enzymes, ATP, photosynthesis, respiration, and interdependence.',
    'Scientists integrate molecular and ecosystem data to explain drought, crop productivity, metabolism, and carbon change.',
    'Next, you will synthesize the complete unit system and transfer it to a new organism–environment case.',
    'energyLab',
    [['flux','rate of movement into or out of a reservoir'],['reservoir','a place where matter is stored'],['net change','total inputs minus total outputs'],['rate','amount of change per unit time'],['system boundary','the parts and exchanges included in a model'],['uncertainty','a source of limited confidence in a measurement or explanation']],
    ['Analyze the enzyme graph and calculate rate change across conditions.','Use the ATP model to connect reaction rate with available cellular work.','Trace carbon and water through photosynthesis, respiration, and environmental reservoirs.','Calculate net flux, graph the data, compare claims, and write a multi-source conclusion with uncertainty.'],
    [['Enzyme rate','Rate is 18 units at 25°C and 30 units at 35°C.','The increase is 12 units, or about 67% relative to 18.'],['ATP model','Lower respiration rate reduces the rate at which ADP is recharged to ATP.','Molecular conditions can affect cell work.'],['Carbon flux','Photosynthesis removes 120 units while respiration returns 85.','Net atmospheric removal is 35 units in the model.'],['Water flux','Evaporation 60 plus transpiration 25 balances precipitation 85.','The modeled reservoir has zero net change.'],['Drought transfer','Stomata close, reducing water loss but also limiting carbon dioxide entry.','One response creates a photosynthesis tradeoff.'],['Limitation','Short-term simulated values omit seasonal and organism variation.','The conclusion must remain tied to the model.']]
  ),
  U03L08: p(
    'The investigation linked molecular conditions to cellular energy and Earth matter cycles.',
    'A complete biological explanation traces both matter and energy across scales instead of treating vocabulary as isolated facts.',
    'Unit 4 asks how DNA stores the instructions for the proteins and enzymes used throughout Unit 3.',
    'synthesis3',
    [['matter','atoms and molecules that can be rearranged and cycled'],['energy','capacity to cause change, transferred and transformed in processes'],['scale','level of organization from molecule to ecosystem'],['coupling','linking one process to another'],['system model','a representation of connected components and exchanges']],
    ['Identify the scale and locate matter and energy inputs and outputs.','Connect water and macromolecule structure to enzyme and membrane function.','Trace ATP coupling to photosynthesis or respiration evidence.','Extend the explanation to carbon and water cycles while naming model limits.'],
    [['Water','Polarity supports transport and reaction environments.','Molecular properties enable cell processes.'],['Protein enzyme','Shape controls reaction rate and conditions can alter shape.','Structure connects to metabolism.'],['ATP','ATP transfers usable energy to cell work.','Energy coupling connects reactions.'],['Photosynthesis','Light energy is stored in glucose while carbon enters living matter.','Matter and energy change form.'],['Respiration','Glucose carbon returns as CO₂ while energy is transferred to ATP and heat.','Matter cycles while usable energy disperses.'],['Cycle model','Reservoir and flux data reveal system-level patterns.','Models support bounded predictions.']]
  ),

  U04L01: p(
    'Unit 3 introduced nucleic acids as information molecules. Cells must copy that information before growth, repair, or reproduction.',
    'Accurate DNA copying supports growth and healing; copying errors introduce mutations studied later.',
    'Next, you will follow copied DNA information through transcription and translation to build proteins.',
    'dna',
    [['nucleotide','DNA unit containing sugar, phosphate, and a base'],['complementary base pairing','A pairs with T and C pairs with G'],['template strand','an existing strand used to build a complementary strand'],['replication','copying DNA before cell division'],['semiconservative','each copied DNA molecule contains one old and one new strand'],['mutation','a change in nucleotide sequence']],
    ['Label nucleotide parts and the antiparallel DNA strands at the lesson’s required depth.','Separate strands and apply A–T and C–G pairing to each template.','Track parental and new strands through the replication fork.','Check the copy for mismatches and explain how semiconservative replication preserves sequence information.'],
    [['Complement','Template 3′-A C G T-5′ produces 5′-T G C A-3′.','Base-pair rules determine the new sequence.'],['Semiconservative model','Each daughter double helix has one parental strand and one newly made strand.','The color pattern demonstrates semiconservative copying.'],['Mismatch','Template C is paired with new A.','C should pair with G, so this is a copying error.'],['Helicase concept','The double helix opens so bases become accessible.','Separation permits each strand to act as a template.'],['Polymerase concept','New nucleotides are joined in complementary order.','The enzyme builds the copy.'],['Boundary','Replication preserves information with high accuracy but is not error-free.','Rare errors can become mutations.']]
  ),
  U04L02: p(
    'Lesson 1 copied DNA. Cells use selected genes—not the entire genome at once—to build proteins.',
    'Gene expression explains how inherited information influences cell function and traits.',
    'Next, you will change a DNA sequence and investigate whether the protein and phenotype change.',
    'geneExpression',
    [['gene','a DNA sequence used to produce a functional RNA or protein product'],['transcription','building RNA from a DNA template'],['mRNA','messenger RNA carrying codon information'],['translation','assembling amino acids according to mRNA codons'],['codon','a three-base mRNA sequence'],['ribosome','structure that reads mRNA and joins amino acids']],
    ['Use the stated DNA template orientation and transcribe with A–U, T–A, C–G, and G–C pairing.','Read mRNA from 5′ to 3′ in groups of three beginning at the stated start codon.','Use the embedded codon chart to select amino acids until a stop codon.','Trace the amino-acid sequence to protein shape, function, and a possible trait while avoiding deterministic overclaims.'],
    [['Transcription','DNA template 3′-TAC GGA ACT-5′ gives mRNA 5′-AUG CCU UGA-3′.','RNA is complementary and uses U instead of T.'],['Translation','AUG codes methionine, CCU codes proline, and UGA is stop.','The codon chart converts mRNA information to amino acids.'],['Location','Transcription occurs in the nucleus; translation occurs at ribosomes.','The pathway moves information across cell locations.'],['Universal code','Most organisms interpret the same codons as the same amino acids.','The shared code supports common biological ancestry and biotechnology.'],['Protein function','Amino-acid order influences folding and binding.','Sequence can affect cell function.'],['Boundary','A gene influences a trait through biological pathways and environment.','One gene does not automatically determine every outcome.']]
  ),
  U04L03: p(
    'Lesson 2 traced DNA through mRNA to protein. A sequence change must be followed through that same pathway to evaluate its effect.',
    'Mutation concepts help you understand variation, cancer, inherited conditions, and why a DNA change is not automatically harmful.',
    'Next, you will model how allele versions of genes pass from parents to offspring.',
    'mutation',
    [['substitution','replacement of one nucleotide with another'],['insertion','addition of nucleotide(s)'],['deletion','removal of nucleotide(s)'],['frameshift','change in the reading groups after insertion or deletion not divisible by three'],['somatic mutation','a mutation in a body cell'],['germline mutation','a mutation in a cell lineage that can contribute to gametes']],
    ['Align original and changed DNA to identify the exact sequence difference.','Transcribe and translate both sequences using the same reading frame and codon chart.','Compare amino-acid sequences and infer a possible protein effect.','Classify the cell lineage and state whether the change could be inherited, while using cautious phenotype language.'],
    [['Silent substitution','mRNA UCU changes to UCC; both code serine.','The DNA changes but the amino-acid sequence does not.'],['Missense','GAA changes to GUA, replacing glutamate with valine.','One amino-acid change may alter folding or function.'],['Nonsense','A coding codon changes to a stop codon.','Translation may end early.'],['Frameshift','One base is inserted near the beginning of the sequence.','Downstream codon grouping changes.'],['Somatic case','A mutation occurs in a skin cell after UV exposure.','It can affect descendant skin cells but is not passed through gametes.'],['Germline case','A mutation occurs in a sperm-forming cell lineage.','It may be inherited by offspring if present in a gamete.']]
  ),
  U04L04: p(
    'Lesson 3 distinguished germline mutations and allele versions. Mendelian models predict how alleles segregate into gametes.',
    'Inheritance models explain family resemblance and probability without pretending to predict one individual with certainty.',
    'Next, you will expand beyond complete dominance to patterns such as codominance, sex linkage, and polygenic variation.',
    'punnett',
    [['allele','an alternative version of a gene'],['genotype','an organism’s allele combination'],['phenotype','an observable or measurable trait outcome'],['homozygous','having two identical alleles'],['heterozygous','having two different alleles'],['segregation','separation of allele pairs into gametes']],
    ['Write the trait key and parental genotypes before drawing the square.','List one allele per possible gamete along the top and side.','Combine row and column alleles in every box.','Count genotype and phenotype outcomes, convert to probabilities, and explain that probability is not a guarantee.'],
    [['Aa × Aa','Offspring genotypes are AA, Aa, Aa, and aa.','The genotype ratio is 1:2:1.'],['Complete dominance','If A is dominant, three of four boxes show the dominant phenotype.','Expected phenotype probability is 75%.'],['Test cross','Unknown dominant-phenotype parent crossed with aa produces recessive offspring.','The unknown parent must carry a recessive allele.'],['Segregation','An Aa parent makes A and a gametes.','The two alleles separate during gamete formation.'],['Observed variation','A family of four does not have to contain exactly three dominant and one recessive child.','Each event is probabilistic and samples can differ from expectation.'],['Boundary','A Punnett square predicts probabilities under the model.','It does not determine the phenotype of a particular future child.']]
  ),
  U04L05: p(
    'Lesson 4 established the Punnett-square method for complete dominance. Many real traits require a different inheritance model.',
    'Complex inheritance prevents the misleading idea that every trait has one “dominant gene.”',
    'Next, you will connect gametes and inheritance models to meiosis and genetic variation.',
    'nonMendelian',
    [['incomplete dominance','heterozygote has an intermediate phenotype'],['codominance','both alleles are detectably expressed in a heterozygote'],['multiple alleles','more than two allele versions exist in a population'],['sex-linked','a gene located on a sex chromosome'],['polygenic','influenced by multiple genes'],['pedigree','a diagram of trait occurrence across a family']],
    ['Compare the evidence with a complete-dominance baseline.','Identify the pattern-specific clue: intermediate, both expressed, sex bias, or continuous distribution.','Use the correct allele notation and model to calculate probabilities.','Explain why the evidence fits that pattern and state environmental or sample limits.'],
    [['Incomplete dominance','Red RR × white WW flowers produce pink RW offspring.','The heterozygote is intermediate.'],['Codominance','IAIB produces type AB blood.','Both A and B markers are expressed.'],['Multiple alleles','ABO has IA, IB, and i alleles in the population.','More than two allele versions exist even though each person has two.'],['X-linked','A son receives his X chromosome from his mother.','X-linked recessive patterns can differ by sex chromosome combination.'],['Polygenic','Height forms a continuous population distribution.','Many genes plus environment influence the trait.'],['Pattern evidence','An intermediate heterozygote is not evidence of codominance.','Codominance shows both traits, not a blend.']]
  ),
  U04L06: p(
    'Punnett squares begin with gametes. Meiosis explains how gametes receive one allele from each pair and become genetically varied.',
    'Mitosis supports growth and repair; meiosis supports sexual reproduction and variation.',
    'Next, the investigation connects DNA, mutations, inheritance, cell division, and biotechnology evidence.',
    'division',
    [['mitosis','nuclear division producing two genetically similar nuclei'],['meiosis','two divisions producing haploid gametes'],['homologous chromosomes','chromosome pair carrying the same gene locations'],['sister chromatids','copied versions of one chromosome'],['haploid','having one chromosome set'],['crossing over','exchange between homologous chromosomes']],
    ['Track chromosome number and copied chromatids rather than memorizing stage names alone.','In mitosis, separate sister chromatids once to produce two similar diploid cells.','In meiosis I, pair and separate homologs; in meiosis II, separate sister chromatids.','Connect crossing over and independent assortment to new allele combinations in haploid gametes.'],
    [['Mitosis result','One diploid cell produces two diploid cells with similar chromosome sets.','The process supports growth and repair.'],['Meiosis result','One diploid cell produces four haploid cells.','Chromosome number is reduced for gametes.'],['2n=4 model','After meiosis, each gamete has n=2 chromosomes.','Homolog pairs are separated.'],['Crossing over','Homologs exchange matching segments in meiosis I.','Chromatids can carry new allele combinations.'],['Independent assortment','Each homolog pair can orient in more than one way.','Gametes receive different combinations of maternal and paternal chromosomes.'],['Key distinction','DNA replicates once before meiosis but the cell divides twice.','Replication is not repeated between meiosis I and II.']]
  ),
  U04L07: p(
    'Lessons 1–6 traced genetic information from copying to expression, mutation, inheritance, and cell division.',
    'Genetic evidence can inform decisions, but probability, controls, privacy, consent, and model limits matter.',
    'Next, you will synthesize how information is copied, expressed, inherited, varied, and applied responsibly.',
    'geneticsLab',
    [['biotechnology','use of biological systems or information for practical applications'],['control sample','known comparison used to interpret a test'],['gel band','a visible DNA-fragment position in an electrophoresis model'],['mitotic index','fraction of observed cells undergoing mitosis'],['informed consent','voluntary agreement based on understood information'],['genetic privacy','protection of a person’s genetic information']],
    ['Inventory the fictional case evidence and identify the question and privacy boundary.','Transcribe and translate reference and variant sequences; classify the mutation and possible protein effect.','Complete the inheritance model and connect allele segregation to meiosis.','Interpret biotechnology controls or cell-cycle data, weigh benefits and risks, and give a bounded recommendation.'],
    [['Variant sequence','One codon changes and one amino acid differs in the model protein.','The evidence supports a possible function change, not a diagnosis.'],['Inheritance','Aa × aa gives a 50% modeled chance of Aa.','Probability applies to each event.'],['Meiosis','Alleles separate when homologs move to different cells.','Cell division provides the gametes used in the cross.'],['DNA bands','The unknown band aligns with the positive control and not the negative control.','Controls support interpretation of the test.'],['Mitotic index','18 of 120 cells are dividing.','The mitotic index is 15%.'],['Ethics','Testing requires consent, limited data use, and protected access.','Scientific usefulness does not remove privacy responsibilities.']]
  ),
  U04L08: p(
    'The Lesson 7 case combined sequence, protein, probability, cell division, test controls, and ethical limits.',
    'Responsible genetic reasoning follows information through mechanisms and keeps probability separate from certainty.',
    'Unit 5 uses inherited genetic variation as the raw material for evolution and population change.',
    'synthesis4',
    [['genetic information','ordered DNA bases that can be copied and expressed'],['inheritance probability','modeled likelihood of an allele combination'],['variation','differences among individuals or sequences'],['evidence limit','a boundary on what data can establish'],['ethical safeguard','a practice protecting people affected by biological information']],
    ['Trace DNA replication before tracing transcription and translation.','Connect a sequence change to protein and phenotype only through explicit evidence.','Connect meiosis to gametes and inheritance probabilities.','Evaluate biotechnology results with controls, limitations, consent, and privacy.'],
    [['Replication','Complementary pairing creates semiconservative DNA copies.','Information is conserved before division.'],['Expression','DNA is transcribed to mRNA and translated to amino acids.','Information directs protein production.'],['Mutation','Sequence change may be silent or alter protein.','Effects depend on location and code.'],['Inheritance','Meiosis segregates alleles and Punnett squares model combinations.','Predictions are probabilities.'],['Variation','Mutation, crossing over, and assortment create or reshuffle differences.','Variation links genetics to evolution.'],['Responsible use','Controls, uncertainty, consent, and privacy bound genetic conclusions.','Evidence quality and ethics both matter.']]
  ),

  U05L01: p(
    'Unit 4 showed how DNA is inherited and varied. Similarities and differences in DNA and anatomy can reveal biological history.',
    'Evolutionary evidence explains antibiotic resistance, biodiversity, and how scientists reconstruct changes no person directly observed.',
    'Next, you will study natural selection—the mechanism that can change heritable trait frequencies.',
    'evolutionEvidence',
    [['evolution','change in inherited characteristics of populations across generations'],['fossil','preserved evidence of past life'],['homologous structure','structure inherited from a common ancestor, possibly used differently'],['biogeography','geographic distribution of organisms'],['molecular evidence','DNA or protein similarities used to compare relationships'],['common ancestry','descent of lineages from shared ancestral populations']],
    ['Distinguish the observation in each source from the historical inference.','Read fossil position and age, anatomical structure, geographic location, and sequence similarity.','State what each source directly supports and one limitation.','Combine independent lines of evidence only when they address the same ancestry or change claim.'],
    [['Fossil layers','A form with small limb bones occurs between older land forms and younger aquatic forms.','Its age and traits support a transitional sequence.'],['Forelimbs','Human, bat, whale, and cat limbs contain the same basic bone arrangement.','Homology supports inheritance from common ancestry.'],['Analogous wings','Bird and insect wings perform flight but have different underlying structures.','Similar function alone does not establish close ancestry.'],['DNA alignment','Species A and B differ at 2 of 20 sites; A and C differ at 9.','A and B are more similar in this sequence.'],['Biogeography','Island finches resemble nearby mainland species but differ among islands.','Location and variation support descent with change after dispersal.'],['Observed change','Resistance frequency rises after repeated antibiotic exposure.','Population change can be observed over generations.']]
  ),
  U05L02: p(
    'Lesson 1 established that populations change. Natural selection explains one way heritable traits become more common.',
    'Selection helps explain antibiotic and pesticide resistance and why individuals do not evolve because they “need to.”',
    'Next, you will distinguish the sources of variation from drift, gene flow, and selection.',
    'selection',
    [['variation','differences among individuals in a population'],['heritability','ability of a trait difference to be passed genetically'],['selection pressure','environmental factor affecting survival or reproduction'],['fitness','relative reproductive contribution in a particular environment'],['adaptation','inherited trait that increases fitness in an environment'],['population','members of one species in the same area and time']],
    ['Verify that individuals vary and that the relevant difference is heritable.','Identify the environmental pressure and compare survival and reproduction among variants.','Calculate trait-frequency change across generations.','Explain change at the population level; individuals survive, reproduce, or acclimate but do not genetically evolve during a lifetime.'],
    [['Beetles before','40 green and 40 brown beetles begin the population.','Heritable color variation is present.'],['Predation','Birds capture 30 green but 10 brown beetles on dark ground.','The environment produces different survival.'],['After reproduction','Brown frequency rises from 50% to 68%.','Differential reproduction changed the population.'],['Antibiotics','Some bacteria already carry resistance before treatment.','Treatment selects existing variants rather than creating need-based resistance.'],['Missing heritability','Exercise increases muscle size, but the acquired size is not inherited.','This does not meet the heritable-variation condition.'],['Environment dependence','Brown color helps on dark soil but may not help on light sand.','Fitness is context-specific.']]
  ),
  U05L03: p(
    'Natural selection acts on heritable variation. This lesson separates the origins of variation from other mechanisms that change allele frequencies.',
    'Small isolated populations can lose diversity by chance, while migration can restore or spread alleles.',
    'Next, you will use inherited traits and molecular differences to construct evolutionary relationships.',
    'variation',
    [['mutation','DNA change that can create a new allele'],['recombination','reshuffling of existing alleles during meiosis'],['gene flow','allele movement between populations through migration and reproduction'],['genetic drift','random allele-frequency change, strongest in small populations'],['bottleneck effect','drift after a sharp population reduction'],['founder effect','drift when a new population begins from few individuals']],
    ['Identify whether a new sequence appears or existing alleles are merely reshuffled.','Track migration only when migrants reproduce and contribute alleles.','Model chance sampling and calculate before/after allele frequencies.','Contrast random drift with directional selection by checking whether survival is consistently tied to a trait.'],
    [['Mutation','DNA site changes from A to G in a reproductive cell lineage.','A new allele can enter the population.'],['Recombination','Crossing over places existing alleles in a new chromosome combination.','Variation is reshuffled, not newly created.'],['Gene flow','Ten migrants reproduce in a neighboring population.','Their alleles enter that population.'],['Bottleneck','A storm leaves 8 random survivors from 200 individuals.','Chance sampling can sharply change frequencies and diversity.'],['Founder effect','Five birds colonize an island with allele frequencies unlike the mainland.','The new population begins from a small, unrepresentative sample.'],['Selection contrast','A frequency changes with no consistent trait advantage.','Drift is more supported than directional selection.']]
  ),
  U05L04: p(
    'Inherited differences and molecular evidence can be organized into testable hypotheses of relationship.',
    'Classification changes when new evidence reveals that appearance alone grouped organisms incorrectly.',
    'Next, you will apply relationship reasoning to domains, kingdoms, and the diversity of life.',
    'cladogram',
    [['taxonomy','science of naming and classifying organisms'],['cladogram','branching model of hypothesized relationships'],['node','branch point representing a shared ancestor'],['derived trait','inherited feature that appears in a lineage and its descendants'],['outgroup','comparison lineage outside the main group'],['phylogeny','evolutionary history and relationships']],
    ['Read the root, tips, nodes, and derived-trait marks before answering.','Find closest relatives by the most recent shared node, not by tip spacing.','Use a trait or DNA-distance matrix to propose grouping.','Revise a classification when stronger molecular or anatomical evidence conflicts with the old grouping.'],
    [['Node reading','Whale and hippo join at a more recent node than whale and shark.','Whale is more closely related to hippo.'],['Tip rotation','Branches can rotate around a node without changing relationships.','Left-to-right order is not evolutionary progress.'],['Trait matrix','Hair occurs only in taxa C and D.','Hair supports grouping C and D if homologous.'],['DNA distance','A–B distance is 3 substitutions; A–C is 12.','A and B are more similar in the compared sequence.'],['Whale revision','Molecular and ankle-bone evidence links whales within even-toed mammals.','New evidence can revise classification.'],['Model limit','A cladogram shows a relationship hypothesis, not exact ancestor appearance or time unless scaled.','Do not infer information absent from the model.']]
  ),
  U05L05: p(
    'Lesson 4 showed how evidence supports nested relationships. Domains and kingdoms apply that logic to broad diversity.',
    'Recognizing microbial and eukaryotic differences supports health, ecology, and accurate classification.',
    'Next, you will evaluate scientific evidence and limits in explanations for life’s earliest emergence.',
    'domains',
    [['domain','highest broad taxonomic rank in the three-domain system'],['Bacteria','prokaryotic domain with bacterial-type cell walls and molecular traits'],['Archaea','prokaryotic domain with distinct membrane, wall, and molecular traits'],['Eukarya','domain whose cells contain nuclei'],['kingdom','broad group below domain'],['dichotomous key','paired-choice tool for identifying organisms']],
    ['Recall the nucleus test to separate Eukarya from prokaryotic domains.','Use wall chemistry and molecular evidence—not shape alone—to distinguish Bacteria from Archaea.','Classify eukaryotes using organization, nutrition, and cell-wall traits.','Follow each dichotomous-key choice from observed evidence and explain when data are insufficient.'],
    [['Unknown A','No nucleus; peptidoglycan wall present.','Classify in Bacteria.'],['Unknown B','No nucleus; no peptidoglycan; archaeal membrane lipids present.','Classify in Archaea.'],['Unknown C','Nucleus and chloroplasts; multicellular; cellulose wall.','Classify in Eukarya and a plant kingdom model.'],['Fungus clue','Nucleus, absorptive nutrition, and chitin wall.','The combined traits support fungi.'],['Protist boundary','Many diverse eukaryotes do not fit simple plant/animal/fungus categories.','Kingdom systems may vary and be revised.'],['Tree evidence','Archaea and Eukarya share some molecular features not shared with Bacteria.','Prokaryotic appearance does not mean identical ancestry.']]
  ),
  U05L06: p(
    'Classification traces living lineages backward. Origin-of-life research asks a different question: how nonliving chemistry could have produced systems capable of heredity and evolution.',
    'This lesson shows how science studies distant events using experiments, models, comparisons, and cautious claims.',
    'Next, the investigation integrates evolution evidence, mechanisms, classification, origin explanations, and hominid trends.',
    'origin',
    [['hypothesis','testable proposed explanation'],['abiotic synthesis','formation of organic molecules from nonliving chemical inputs'],['protocell','nonliving compartment model with some cell-like properties'],['vesicle','membrane-like compartment formed by lipids'],['evidence','observation or result relevant to a claim'],['inference','interpretation based on evidence']],
    ['Define the boundary between origin-of-life chemistry and biological evolution after heredity exists.','Read apparatus inputs, conditions, and measured products before stating a conclusion.','Compare competing settings such as surface pools, vents, meteorite delivery, and lipid compartments.','State what each result supports and what major steps remain unexplained.'],
    [['Miller–Urey model','Gases, water vapor, and electrical energy produce several organic molecules.','The result supports abiotic formation of building blocks under modeled conditions.'],['Overclaim','Amino acids are produced, but no living cell is formed.','The experiment does not recreate complete life.'],['Meteorite evidence','Organic molecules occur in some meteorites.','Space delivery is a possible source of ingredients, not proof of life origin.'],['Vent model','Mineral surfaces and chemical gradients can concentrate reactions.','The setting offers a mechanism to test.'],['Vesicles','Lipids spontaneously form bounded compartments in water.','Compartment formation can be modeled without claiming heredity.'],['Missing requirement','A protocell must eventually support information copying and evolution.','A membrane alone is insufficient.']]
  ),
  U05L07: p(
    'Lessons 1–6 developed evidence, selection, variation mechanisms, classification, domains, and origin-of-life boundaries.',
    'Evolutionary scientists integrate incomplete sources and communicate uncertainty rather than forcing one source to answer every question.',
    'Next, you will synthesize evidence, mechanisms, history, and scientific limits in a new mixed case.',
    'evolutionLab',
    [['convergence of evidence','agreement among independent evidence types'],['allele frequency','proportion of a gene’s copies represented by an allele'],['trend','overall direction across data'],['hominin','human-lineage member after divergence from the chimpanzee lineage'],['mosaic evolution','different traits changing at different rates'],['uncertainty','recognized limit in evidence or interpretation']],
    ['Analyze fossil, anatomy, DNA, and biogeography evidence for relationship claims.','Calculate selection or allele-frequency change and identify the supported mechanism.','Read a cladogram and three-domain model; revise a grouping when molecular evidence warrants it.','Evaluate origin evidence and graph hominin traits without treating evolution as a straight ladder.'],
    [['Converging evidence','Fossil timing, homologous bones, and DNA similarity support the same relationship.','Independent agreement strengthens the claim.'],['Selection data','A trait rises from 22% to 61% across generations while reproductive success differs.','The pattern supports selection under the measured pressure.'],['Cladogram','Taxa sharing the most recent node are closest in the model.','Tip order does not determine closeness.'],['Origin limit','Organic products support chemical plausibility but not complete living systems.','The conclusion must remain bounded.'],['Hominin trend','Average cranial capacity generally rises across later samples, with overlap and exceptions.','A trend does not create a single linear ancestor chain.'],['Mosaic pattern','Bipedal traits appear before the largest cranial capacities.','Traits can change at different times.']]
  ),
  U05L08: p(
    'The investigation combined evidence, mechanisms, relationships, origin boundaries, and hominin trends.',
    'A coherent evolutionary explanation separates evidence that change occurred from mechanisms that explain how populations changed.',
    'Unit 6 turns to present ecosystems: where organisms live, how populations interact, and how people affect those systems.',
    'synthesis5',
    [['historical evidence','records used to reconstruct past biological change'],['mechanism','process that produces change'],['relationship hypothesis','evidence-based proposal of common ancestry'],['classification','organization reflecting biological evidence and purpose'],['scientific boundary','limit on what a method can answer']],
    ['Identify whether a source addresses history, mechanism, relationship, or origin chemistry.','Combine fossils, anatomy, geography, and molecules only for supported claims.','Use population data to distinguish selection, drift, gene flow, and mutation.','Read classifications and trends as revisable models with explicit limits.'],
    [['Evidence','Fossils and DNA can support common ancestry.','They address history and relationship.'],['Mechanism','Differential reproduction changes trait frequency.','Natural selection explains population change.'],['Variation','Mutation creates alleles; recombination reshuffles; drift and gene flow alter frequencies.','Mechanisms have distinct evidence clues.'],['Classification','New DNA data can revise a tree.','Systems respond to evidence.'],['Origin','Chemical experiments test possible steps before biological evolution.','They do not prove one complete historical sequence.'],['Hominin synthesis','Multiple branching lineages show overlapping traits.','Human evolution is not a simple ladder.']]
  ),

  U06L01: p(
    'Unit 5 explained adaptation and tolerance. Ecology asks how environmental conditions determine where organisms can live now.',
    'Aquatic distribution affects fisheries, coral bleaching, harmful blooms, and water quality.',
    'Next, you will examine how ecosystems change across seasons, climate trends, and succession.',
    'aquatic',
    [['abiotic factor','nonliving environmental condition'],['salinity','concentration of dissolved salts'],['dissolved oxygen','oxygen gas available in water'],['photic zone','water depth receiving enough light for substantial photosynthesis'],['tolerance range','conditions within which an organism can survive or reproduce'],['upwelling','rise of deep nutrient-rich water']],
    ['Read the depth, light, temperature, salinity, and oxygen axes with units.','Compare each species’ tolerance range with zone conditions.','Use geography and water movement to explain nutrient patterns.','Support distribution with multiple factors and distinguish correlation from tested cause.'],
    [['Depth profile','Light falls from 100% at surface to 1% at 200 m.','Photosynthesis is restricted mainly to shallower water.'],['Dissolved oxygen','Cold surface water holds more oxygen than warm stagnant water in the dataset.','Temperature and mixing help explain distribution.'],['Estuary','Salinity varies from 3 to 25 ppt with tides and river flow.','Only tolerant organisms persist across the full range.'],['Phytoplankton','High light but low nutrients produces modest abundance offshore.','More than one resource can limit growth.'],['Upwelling','Deep nutrient-rich water reaches the sunny surface.','Nutrients plus light support high productivity.'],['Tolerance boundary','A species survives 10–20°C in the experiment.','The data do not establish survival outside the tested range.']]
  ),
  U06L02: p(
    'Aquatic conditions shape distribution. When conditions change over time, community composition also changes.',
    'Succession and climate data explain recovery after fire or storms and shifts in local species ranges.',
    'Next, you will quantify population change and carrying capacity.',
    'succession',
    [['succession','change in community composition over time'],['primary succession','community development where soil is initially absent'],['secondary succession','community recovery where soil remains'],['pioneer species','early colonizer that tolerates exposed conditions'],['disturbance','event that changes an ecosystem'],['climate trend','long-term directional pattern in climate data']],
    ['Identify the disturbance, timescale, and whether soil remains.','Sequence colonization and changing abundance without assuming a fixed final endpoint.','Separate repeating seasonal cycles from long-term directional trends.','Use before/after data to predict distribution change and state alternative explanations.'],
    [['Lava flow','New rock has no soil immediately after eruption.','Recovery begins as primary succession.'],['Wildfire','Vegetation burns but soil and seeds remain.','Secondary succession is supported.'],['Recovery table','Grass peaks early; shrubs rise later; tree cover rises over decades.','Different groups dominate at different stages.'],['Seasonal oxygen','Lake oxygen declines below the thermocline each summer and rises after fall mixing.','This is a repeating seasonal pattern.'],['Climate range','Average temperature rises while a cold-adapted species shifts upslope over 30 years.','The data support association; habitat change is an alternative to evaluate.'],['Endpoint boundary','Communities remain dynamic after recovery.','Succession is not guaranteed to end in one permanent climax.']]
  ),
  U06L03: p(
    'Ecosystem change alters resources and conditions. Population data reveal how groups respond.',
    'Population reasoning supports wildlife management, fisheries, disease tracking, and local conservation.',
    'Next, you will place populations inside food webs and trace energy transfer.',
    'population',
    [['population size','number of individuals in a defined area and time'],['immigration','movement into a population'],['emigration','movement out'],['carrying capacity','population size an environment can sustain under current conditions'],['density-dependent factor','effect that strengthens with crowding'],['density-independent factor','effect not caused by population density']],
    ['Define the population’s species, place, and time.','Calculate ΔN = births + immigration − deaths − emigration.','Graph population through time and estimate carrying capacity from long-term fluctuation, not one point.','Classify limiting factors and explain why carrying capacity can change.'],
    [['BIDE','80 births + 12 immigrants − 50 deaths − 7 emigrants = +35.','The population increases by 35.'],['Logistic graph','Growth slows and fluctuates near 600 individuals.','About 600 is a supported carrying-capacity estimate for that period.'],['Overshoot','Population rises above food-supported capacity, then declines.','Resource depletion can create delayed effects.'],['Disease','Transmission increases as individuals crowd.','This is density-dependent.'],['Hurricane','A storm affects populations regardless of crowding.','This is density-independent.'],['Changing K','Drought reduces available water and vegetation.','Carrying capacity can fall.']]
  ),
  U06L04: p(
    'Population changes affect predators, prey, competitors, and decomposers. Food webs represent those connections.',
    'Food-web reasoning helps explain fisheries, predator removal, ecosystem resilience, and why food chains are limited in length.',
    'Next, you will investigate how biodiversity loss and invasive species can disrupt these relationships.',
    'foodWeb',
    [['producer','organism that builds organic matter using an external energy source'],['consumer','organism that obtains energy by eating other organisms'],['decomposer','organism that breaks down dead matter and waste'],['trophic level','feeding position in an energy pathway'],['energy pyramid','model of decreasing usable energy across trophic levels'],['matter cycle','repeated movement of atoms through living and nonliving components']],
    ['Use the arrow key: arrows point from food to eater, showing energy transfer.','Trace several pathways and assign trophic roles that may differ by diet.','Calculate energy transfer and percent loss between levels.','Predict direct and indirect effects, then separate one-way energy flow from matter cycling.'],
    [['Food web arrow','Algae → snail means the snail obtains energy by eating algae.','The arrow follows energy to the consumer.'],['Energy pyramid','10,000 kJ in producers and 1,000 kJ in primary consumers is 10% transfer.','Most usable energy is not passed to the next level.'],['Decomposer','Fungi break down dead fish and release nutrients.','Matter returns to reservoirs while energy disperses.'],['Predator removal','Removing hawks increases rodents, which reduce seeds.','One change can create an indirect effect.'],['Omnivore','A bird eats seeds and insects.','Its trophic role depends on the specific pathway.'],['Matter/energy','Carbon atoms can cycle; energy eventually leaves as heat.','Matter and energy follow different system patterns.']]
  ),
  U06L05: p(
    'Food webs show why losing one species can affect many others. Biodiversity data measure those changes.',
    'Biodiversity supports ecosystem resilience and human needs; invasive species and habitat change can reduce it.',
    'Next, you will compare resource choices, costs, benefits, and sustainability.',
    'biodiversity',
    [['species richness','number of species present'],['evenness','similarity of abundances among species'],['invasive species','introduced species that causes ecological or economic harm'],['habitat fragmentation','division of habitat into smaller isolated pieces'],['resilience','ability of a system to resist or recover from disturbance'],['causal claim','statement that one factor produces an effect']],
    ['Calculate richness and compare abundance distribution before judging diversity.','Read spread maps and before/after/control data to identify patterns.','Trace a proposed mechanism through competition, predation, disease, or habitat change.','Evaluate alternative explanations and use cautious causal language when controls are missing.'],
    [['Richness','Site A has 8 species; Site B has 5.','A has greater species richness.'],['Evenness','At Site A one species makes up 90%; Site B has five similarly common species.','B may have greater evenness despite lower richness.'],['Invasion data','Invaded plots lose 40% native cover while comparable uninvaded plots lose 5%.','The comparison supports an invasion effect.'],['Spread map','Occurrences expand downstream each year.','Direction suggests dispersal with water flow.'],['Fragmentation','Small isolated patches support fewer interior-habitat species.','Edge effects and isolation offer mechanisms.'],['Causal limit','A hurricane and invader arrive in the same year.','Both drivers must be evaluated.']]
  ),
  U06L06: p(
    'Lesson 5 identified biodiversity pressures. Many pressures result from choices about energy, water, food, land, and materials.',
    'Sustainability decisions require real tradeoffs rather than labeling one option simply good or bad.',
    'Next, the investigation uses monitoring evidence to recommend an ecological action within constraints.',
    'sustainability',
    [['renewable resource','resource replenished on a human-relevant timescale when managed within its rate'],['nonrenewable resource','resource formed far more slowly than it is used'],['life-cycle impact','impact across extraction, production, use, and disposal'],['tradeoff','gain in one criterion accompanied by a cost in another'],['sustainability','meeting needs while maintaining long-term system capacity'],['mitigation','action that reduces a harmful impact']],
    ['Classify resources by replenishment timescale and rate, not by whether they seem natural.','Choose decision criteria such as emissions, land, water, reliability, and cost.','Compare values using common units and calculate percent change.','Recommend an option within stated constraints and disclose tradeoffs, uncertainty, and shifted impacts.'],
    [['Energy table','Solar has low operational emissions but larger land use; gas is dispatchable but emits more CO₂.','A decision must weight multiple criteria.'],['Renewal rate','Forest regrowth is 3% yearly while harvest is 7%.','Use exceeds modeled renewal and is not sustainable.'],['Household action','Electricity use falls from 900 to 720 kWh.','The reduction is 180 kWh, or 20%.'],['Life cycle','An electric device has manufacturing impacts even with low use-phase emissions.','Impacts can shift between stages.'],['Constraint','A hospital needs reliable power during outages.','A portfolio with storage or backup may meet the requirement better than one source alone.'],['Recommendation','Choose an option and state which criterion was prioritized.','Evidence-based decisions make values and tradeoffs visible.']]
  ),
  U06L07: p(
    'Lessons 1–6 connected aquatic conditions, succession, populations, food webs, biodiversity, and resource tradeoffs.',
    'Environmental analysts integrate imperfect evidence to recommend actions and monitoring—not merely describe one graph.',
    'Next, you will synthesize the entire ecology system and transfer it to a new watershed case.',
    'ecologyLab',
    [['baseline','measurement used for comparison before or without a change'],['indicator species','species whose condition provides information about environmental conditions'],['monitoring','repeated measurement through time or across sites'],['policy option','possible action evaluated with evidence and constraints'],['stakeholder','person or group affected by a decision'],['adaptive management','revising action as monitoring provides new evidence']],
    ['Inspect the monitoring map, variables, units, dates, and baseline.','Graph water and population data; connect abiotic change to tolerance and carrying capacity.','Trace effects through the food web and compare biodiversity before and after disturbance.','Evaluate resource and policy tradeoffs, then propose an evidence-based action and repeat-monitoring plan.'],
    [['Water quality','Downstream oxygen falls from 8.4 to 4.1 mg/L as temperature and nutrient levels rise.','The pattern can affect oxygen-sensitive species.'],['Population','Sensitive insect abundance falls while tolerant worms rise.','Community change corroborates water-quality evidence.'],['Food web','Fewer aquatic insects reduce food available to small fish.','Abiotic change can produce indirect trophic effects.'],['Biodiversity','Richness falls from 14 to 9 species at impacted sites.','Multiple indicators show ecological change.'],['Policy tradeoff','Buffer restoration costs more initially but reduces modeled runoff more than signs alone.','Cost and ecological benefit must both be considered.'],['Monitoring plan','Repeat matched upstream/downstream samples monthly with the same method.','Consistent replication tests whether action improves conditions.']]
  ),
  U06L08: p(
    'The Lesson 7 investigation combined multiple ecological data sources into one decision and monitoring plan.',
    'Environmental decisions require systems thinking: one statistic cannot represent distribution, populations, food webs, biodiversity, and human tradeoffs.',
    'You are now ready to transfer biology’s inquiry, systems, genetics, evolution, and ecology reasoning to real claims and future science courses.',
    'synthesis6',
    [['ecosystem','interacting organisms and physical environment'],['interdependence','mutual influence among system components'],['cascade','series of indirect effects following one change'],['resilience','capacity to resist or recover'],['evidence-based decision','choice justified with relevant data, criteria, and limits']],
    ['Define the ecosystem boundary and read abiotic conditions first.','Connect conditions to population change, carrying capacity, and food-web pathways.','Connect species changes to biodiversity and resilience.','Compare human actions and tradeoffs, then justify a monitored recommendation with uncertainty.'],
    [['Aquatic profile','Warm low-oxygen deep water excludes a sensitive fish.','Abiotic tolerance helps explain distribution.'],['Succession','Soil remaining after fire supports rapid secondary recovery.','History affects community change.'],['Population','Food decline lowers carrying capacity.','Resource limits alter population size.'],['Food web','Predator removal triggers prey increase and producer decline.','Indirect effects form a cascade.'],['Biodiversity','Invasion plus fragmentation reduces richness and evenness.','Multiple drivers can reduce resilience.'],['Decision','A recommendation compares ecological benefit, cost, feasibility, and monitoring.','Systems evidence supports adaptive management.']]
  ),
};

module.exports = profiles;
