import fs from 'node:fs';
const out='Refined Courses/WORLD HISTORY/Units/Unit 04/Moodle XML/WH_U04_L07_Quiz_MoodleXML.xml',F='Foundational',I='Interpretation',A='Application';
const q=[
[F,'What is nationalism?','Strong identification with a nation and belief that it should possess unity, power, or self-government',['Direct foreign control of a colony','A treaty granting extraterritoriality','A policy of unrestricted trade']],
[F,'What is Realpolitik?','Practical politics focused on power and achievable goals rather than ideology alone',['Government based only on moral ideals','A theory of racial hierarchy','A Chinese treaty-port system']],
[F,'What is imperialism?','Extension of a state’s political, economic, or military power over other peoples or territories',['The voluntary unification of equal states only','A refusal to participate in global trade','A policy ending national competition']],
[F,'What is a sphere of influence?','An area where an outside power has special privileges without complete formal control',['A territory directly governed as a colony','A unified nation-state','A port closed to every foreign trader']],
[F,'What is extraterritoriality?','An arrangement allowing foreigners to be governed by their own country’s laws in specified local contexts',['The unification of separate territories','The legal abolition of foreign trade','A nationalist military alliance']],
[I,'<p><strong>Bismarck, 1862:</strong> Major questions would be decided “not by speeches and majority decisions...but by iron and blood.”</p><p>Which method is emphasized?</p>','Power, military capacity, and practical state action',['Popular debate alone','Colonial resistance to opium','Missionary activity']],
[I,'<p><strong>Lin Zexu, 1839:</strong> “By what right do they then in return use the poisonous drug to injure the Chinese people?”</p><p>Which concern is most direct?</p>','The moral and sovereign harm caused by the opium trade',['Support for British extraterritoriality','A desire to surrender Hong Kong','German national unification']],
[I,'<p><strong>Treaty of Nanjing, 1842:</strong> Hong Kong was ceded to Britain “in perpetuity.”</p><p>What does this provision demonstrate?</p>','A territorial concession imposed after military defeat',['Voluntary Chinese colonization of Britain','Italian unification','The end of all foreign trade']],
[I,'<table border="1"><tr><th>Italy</th><th>Germany</th></tr><tr><td>Piedmont-Sardinia, Cavour, Garibaldi, Victor Emmanuel II</td><td>Prussia, Bismarck, economic and military power</td></tr><tr><td>Diplomacy, war, popular military action</td><td>Diplomacy and limited wars</td></tr></table><p>Which conclusion is supported?</p>','Nationalism interacted with leadership, state power, diplomacy, and warfare in both cases',['Popular desire alone unified both states','Neither process involved monarchy','Both followed identical leadership structures']],
[I,'<table border="1"><tr><th>Imperial motive</th><th>Enabling condition</th></tr><tr><td>Markets, raw materials, prestige, strategy</td><td>Steamships, weapons, communications, quinine</td></tr></table><p>Why is the distinction important?</p>','Technology increased capacity, while economic and political goals motivated expansion',['Technology was the only motive','Markets were an enabling machine','Prestige prevented conquest']],
[I,'<p><strong>Map description:</strong> European colonies covered large areas of Africa and Asia, while coastal China contained treaty ports and foreign spheres but remained under Qing rule.</p><p>What distinction does the map support?</p>','Direct colonial control differed from informal or limited foreign privilege',['China became a British colony','All influence areas were identical','Africa had no resistance']],
[I,'<p><strong>Simplified flow:</strong> Demand for Chinese goods → trade imbalance → British opium trade → Chinese suppression → war → unequal treaties.</p><p>Which event is an immediate trigger rather than an underlying motive?</p>','Chinese suppression of the opium trade',['British demand for tea and silk','Long-term commercial interest','Imperial competition']],
[I,'<p>A pro-imperial poster depicts Europeans as bringing civilization to supposedly inferior peoples.</p><p>What should a historian identify?</p>','A racial and cultural ideology used to justify domination',['Scientifically valid biological hierarchy','A neutral map of resources','Evidence that colonized peoples agreed']],
[I,'<p>A Chinese reform document advocates learning selected foreign military techniques while preserving Chinese institutions.</p><p>Which response does this illustrate?</p>','Selective adaptation and Self-Strengthening',['Complete passivity','Formal colonization of Europe','Rejection of every technology']],
[I,'<table border="1"><tr><th>Nationalism</th><th>Imperialism</th></tr><tr><td>Unity and self-determination claimed at home</td><td>Autonomy denied to pressured peoples abroad</td></tr></table><p>What historical tension is shown?</p>','States celebrating national unity could deny self-determination to others',['Nationalism always ended empire','Imperialism promoted equal sovereignty','The two forces never overlapped']],
[A,'Why is nationalism alone insufficient to explain German unification?','Prussian power, economic integration, Bismarck’s diplomacy, and wars also mattered',['Germany had no nationalist ideas','Only overseas colonies caused unification','Unification occurred without leadership']],
[A,'Which comparison between Italian and German unification is strongest?','Both combined nationalism with state leadership and conflict, but Piedmont-Sardinia and Prussia used different leaders and paths',['Both were led by Bismarck','Neither used diplomacy','Both abolished monarchy immediately']],
[A,'Why is it inaccurate to say imperialism happened because Europeans had better technology?','Technology enabled conquest, while economic, political, strategic, and ideological motives drove expansion',['Europeans lacked industrial technology','Technology had no military use','Motives existed only in China']],
[A,'Which evidence best supports Geographic Reasoning about imperialism in China?','A dated map showing treaty ports, Hong Kong, coastal access, and foreign spheres',['A list of Italian leaders','A factory wage table','A philosophical quotation with no place']],
[A,'Which statement best explains the Opium Wars?','They involved the illegal opium trade, Chinese sovereignty, British commercial interests, and imperial military power',['They were neutral free-trade disputes only','China invaded Britain to sell tea','They unified Germany']],
[A,'A student says China became a European colony. What is the best correction?','China remained formally sovereign but lost significant legal and economic autonomy through treaties and spheres',['China faced no foreign pressure','Britain annexed all Qing territory','Treaty ports strengthened complete Chinese control']],
[A,'Which question best evaluates Lin Zexu’s perspective?','How did his responsibility for Qing sovereignty and opium suppression shape his appeal?',['Was every British person identical?','What color was the document?','Does his letter explain Italian unity?']],
[A,'Which claim-evidence-reasoning statement is strongest?','Because the Treaty of Nanjing ceded Hong Kong and opened access after military defeat, British power reduced Qing sovereignty without colonizing all China',['China changed because treaties matter','Britain won because it was powerful','Nationalism and imperialism were identical']],
[A,'Which example best shows nationalism as divisive?','National claims could destabilize multiethnic Habsburg or Ottoman empires',['Italian territories formed one state','Britain sought markets abroad','China opened treaty ports']],
[A,'Which conclusion best connects nationalism and imperialism?','Nationalism could support unity at home while state rivalry and prestige encouraged domination abroad',['Nationalism always produced freedom','Imperialism eliminated national competition','The forces belonged to unrelated centuries']]
];
const pos=[1,3,0,2,1,2,0,3,1,2,3,0,2,1,3,0,2,1,3,0,2,3,1,0,2],esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');let xml='<?xml version="1.0" encoding="UTF-8"?>\n<quiz>\n',last='';q.forEach((x,n)=>{let[cat,p,c,w]=x;if(cat!==last){xml+=`<question type="category"><category><text>$course$/top/WH/U04/L07/${cat}</text></category></question>\n`;last=cat;}let ans=[...w];ans.splice(pos[n],0,c);xml+=`<question type="multichoice"><name><text>WH_U04_L07_${cat}_Q${String(n+1).padStart(2,'0')}</text></name><questiontext format="html"><text><![CDATA[${p}]]></text></questiontext><generalfeedback format="html"><text><![CDATA[Review the source, map, and cause-and-effect relationship.]]></text></generalfeedback><defaultgrade>1</defaultgrade><penalty>0.3333333</penalty><hidden>0</hidden><single>true</single><shuffleanswers>true</shuffleanswers><answernumbering>abc</answernumbering>${ans.map(v=>`<answer fraction="${v===c?100:0}"><text>${esc(v)}</text><feedback format="html"><text><![CDATA[${v===c?'Correct.':'Review the evidence and distinguish motivation, method, and consequence.'}]]></text></feedback></answer>`).join('')}</question>\n`;});xml+='</quiz>\n';fs.writeFileSync(out,xml,'utf8');console.log(`Wrote ${q.length} questions`);
