import fs from 'node:fs';

const out = 'Refined Courses/WORLD HISTORY/Units/Unit 04/Moodle XML/WH_U04_L01_Quiz_MoodleXML.xml';
const items = [
['Foundational','Which definition best describes absolutism?','A political model in which a monarch seeks to concentrate substantial governing authority in the crown',['A system in which every adult votes directly on laws','A monarchy without taxation or administrators','A government in which nobles always control the monarch']],
['Foundational','What did divine-right theory claim?','A monarch’s authority ultimately came from God',['Parliament created every monarch’s authority','Military victory automatically created legal rights','Royal authority came from universal elections']],
['Foundational','Which statement best defines constitutional monarchy in seventeenth-century England?','The monarch remained head of state but was limited by laws and political institutions',['The monarchy was abolished permanently','Every resident received equal voting rights','The monarch controlled Parliament without restriction']],
['Foundational','What was the Restoration of 1660?','The return of the English monarchy after the Commonwealth',['The creation of Versailles','The beginning of the English Civil War','The passage of the Petition of Right']],
['Foundational','Which institution gained stronger governing authority in England after 1689?','Parliament',['The French royal court','The papacy','Local guilds']],
['Interpretation','<p><strong>Source context:</strong> UK Parliament summarizes the Petition of Right (1628) as opposing taxation without parliamentary consent and arbitrary imprisonment.</p><p>Which inference is best supported?</p>','Parliament asserted that law should limit specific royal practices',['Parliament demanded the permanent abolition of monarchy','Charles I voluntarily transferred all authority to Parliament','The document established universal voting rights']],
['Interpretation','<p><strong>Source context:</strong> The English Bill of Rights (1689) declared that levying money for the Crown without a grant of Parliament was illegal.</p><p>What political limit does this provision establish?</p>','The monarch could not independently impose taxation for the Crown',['Parliament could not debate taxation','Local nobles alone controlled all revenue','England could no longer maintain any government']],
['Interpretation','<p><strong>Source context:</strong> The English Bill of Rights stated that keeping a standing army in peacetime without Parliament’s consent was against law.</p><p>Which category of power is directly limited?</p>','Military authority',['Religious toleration','Court architecture','Noble inheritance']],
['Interpretation','<table border="1"><tr><th>Date</th><th>Development</th></tr><tr><td>1628</td><td>Petition of Right</td></tr><tr><td>1642–1651</td><td>English Civil War</td></tr><tr><td>1660</td><td>Restoration</td></tr><tr><td>1688</td><td>Glorious Revolution</td></tr><tr><td>1689</td><td>English Bill of Rights</td></tr></table><p>Which conclusion best uses the chronology?</p>','Institutional limits on the English crown developed through a prolonged series of conflicts and settlements',['Constitutional monarchy appeared suddenly with no earlier conflict','The Restoration permanently ended disputes over authority','The Petition of Right was written after the Glorious Revolution']],
['Interpretation','<table border="1"><tr><th>Feature</th><th>Political use</th></tr><tr><td>Large ceremonial spaces</td><td>Displayed royal magnificence</td></tr><tr><td>Access to the king</td><td>Organized patronage and status</td></tr><tr><td>Court ritual</td><td>Structured noble competition</td></tr></table><p>What does this evidence suggest about Versailles?</p>','Architecture and ritual could help Louis XIV represent authority and manage elites',['Versailles proves the king faced no financial limits','The palace transferred taxation authority to Parliament','Court ritual eliminated the French nobility']],
['Interpretation','<p>A royal portrait shows Louis XIV in elaborate robes beside symbols of monarchy.</p><p>What is the most important source limitation?</p>','The portrait communicates an intended image of power but cannot prove how fully policies were enforced',['The portrait provides no evidence about political symbolism','The image proves Parliament controlled France','The portrait can determine exact tax revenue']],
['Interpretation','<table border="1"><tr><th>France under Louis XIV</th><th>England after 1689</th></tr><tr><td>Royal ministers and court centered on the crown</td><td>Parliament held a stronger institutional role</td></tr><tr><td>Standing army under royal direction</td><td>Standing army in peacetime required parliamentary consent</td></tr></table><p>Which comparison is best supported?</p>','Both were monarchies, but England placed stronger institutional checks on selected royal powers',['Only France had a monarch','England had universal democracy while France had no laws','Both systems gave identical authority to representative institutions']],
['Interpretation','<p>A historian writes: “Louis XIV’s government was highly centralized, yet tax privilege, local institutions, war costs, and administrative limits constrained the crown.”</p><p>Which interpretation is most accurate?</p>','Absolutism involved concentrated royal authority rather than perfectly unlimited control',['Louis XIV possessed no meaningful authority','French nobles elected Louis XIV','The English Bill of Rights governed France']],
['Interpretation','<table border="1"><tr><th>Document</th><th>Claim</th></tr><tr><td>Petition of Right</td><td>Challenges taxation without parliamentary consent and arbitrary imprisonment</td></tr><tr><td>English Bill of Rights</td><td>Limits suspension of laws, taxation, and standing armies without Parliament</td></tr></table><p>What continuity appears across the documents?</p>','Parliament repeatedly asserted that law should restrict independent royal action',['Both documents abolished Parliament','Both created universal suffrage','Both strengthened divine-right theory']],
['Interpretation','<p><strong>Map description:</strong> France and England were close European rivals near major sea routes; Spain, the Netherlands, and the Holy Roman Empire also competed for power.</p><p>Which inference best connects geography to political change?</p>','Interstate competition could increase pressure for taxation, armies, and centralized administration',['Geography made political institutions irrelevant','All neighboring states developed identical governments','Sea routes prevented rulers from building armies']],
['Application','Which comparison uses a valid common category?','France concentrated taxation authority in the crown, whereas Parliament gained a stronger role over taxation in England',['France built Versailles, while England experienced events','Louis XIV was French, whereas Parliament was an institution','England changed over time, while France had nobles']],
['Application','Why is “France was absolute and England was democratic” an inadequate conclusion?','It exaggerates French control and ignores restricted political participation in England',['It gives too much attention to source limitations','It correctly treats both systems as universal democracies','It proves that neither country had laws']],
['Application','Which factor best helps explain why English and French monarchy developed differently?','England’s prolonged conflicts between crown and Parliament strengthened representative institutions, while French rulers centralized authority through different institutions',['France had no religious or financial conflict','England had no monarch after 1660','Geography automatically dictated each constitution']],
['Application','A student argues that Versailles proves Louis XIV had unlimited power. Which revision is strongest?','Versailles shows royal symbolism and management of nobles, but other evidence is needed to judge financial and administrative limits',['Versailles proves unlimited power because it was large','The palace is irrelevant because visual evidence cannot be used','Versailles proves France was a constitutional monarchy']],
['Application','Which evidence would best corroborate a royal portrait’s message of concentrated authority?','A royal-government document describing appointments, administration, or military command',['A modern fictional story about a king','A map showing only European coastlines','A list of palace room colors']],
['Application','Which development represents the clearest change in English political authority by 1689?','Parliament gained stronger institutional control over taxation, laws, and military authority',['England ceased to be a monarchy','All social hierarchy disappeared','Political participation became universal']],
['Application','Which statement identifies both continuity and change in England?','Monarchy and restricted participation continued, while legal and parliamentary limits on the crown increased',['Nothing continued after 1689','Only the monarch changed names','Parliament disappeared while divine right expanded']],
['Application','A source was produced by Parliament during conflict with a monarch. Which question best evaluates perspective?','What political interests and grievances might Parliament emphasize in this document?',['Is every statement automatically false?','What color was the original paper?','Does the source prove France had the same institutions?']],
['Application','Which claim-evidence-reasoning statement is strongest?','Because the Bill of Rights restricted taxation and standing armies without Parliament, it demonstrates stronger institutional limits on the English crown',['England was constitutional because constitutional means better','Louis XIV was absolute because he was a king','The systems differed, but no evidence is necessary']],
['Application','Which conclusion best evaluates the labels “absolute” and “constitutional”?','They are useful starting categories, but historians must compare institutions, practices, and limits using evidence',['The labels provide complete proof by themselves','The labels mean both monarchies were modern democracies','The labels show that laws existed only in England']]
];
const positions=[1,3,0,2,1,2,0,3,1,2,3,0,2,1,3,0,2,1,3,0,2,3,1,0,2];
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
let xml='<?xml version="1.0" encoding="UTF-8"?>\n<quiz>\n';
let last='';
items.forEach((q,i)=>{const [cat,prompt,correct,wrong]=q;if(cat!==last){xml+=`<question type="category"><category><text>$course$/top/WH/U04/L01/${cat}</text></category></question>\n`;last=cat;} const answers=[...wrong];answers.splice(positions[i],0,correct);xml+=`<question type="multichoice"><name><text>WH_U04_L01_${cat}_Q${String(i+1).padStart(2,'0')}</text></name><questiontext format="html"><text><![CDATA[${prompt}]]></text></questiontext><generalfeedback format="html"><text><![CDATA[Review the cited lesson evidence and apply the stated historical-thinking skill.]]></text></generalfeedback><defaultgrade>1</defaultgrade><penalty>0.3333333</penalty><hidden>0</hidden><single>true</single><shuffleanswers>true</shuffleanswers><answernumbering>abc</answernumbering>${answers.map(a=>`<answer fraction="${a===correct?100:0}"><text>${esc(a)}</text><feedback format="html"><text><![CDATA[${a===correct?'Correct. This answer accurately connects the evidence to political authority.':'Review the lesson evidence and compare the same political category in both systems.'}]]></text></feedback></answer>`).join('')}</question>\n`;});
xml+='</quiz>\n';
fs.writeFileSync(out,xml,'utf8');
console.log(`Wrote ${items.length} questions to ${out}`);
