import fs from 'node:fs';
const out='Refined Courses/WORLD HISTORY/Units/Unit 04/Moodle XML/WH_U04_L03_Quiz_MoodleXML.xml';
const F='Foundational',I='Interpretation',A='Application';
const q=[
[F,'What is a revolution?','A major political or social change that challenges an established system',['A routine election within an unchanged system','A trade agreement between states','A hereditary transfer of office']],
[F,'What was the Ancien Régime?','The political and social order of France before the Revolution',['The American constitutional system','Napoleon’s final government','The British colonial assembly']],
[F,'What was the Estates-General?','A French representative assembly organized by the three traditional estates',['The American federal legislature','The Paris fortress-prison','The revolutionary court during the Terror']],
[F,'Why did the Bastille become historically significant?','Its capture became a symbol of popular challenge to royal authority',['It contained the entire French army','It wrote the Rights of Man','It ended the revolution immediately']],
[F,'What is a republic?','A government without a hereditary monarch as head of state',['A government ruled only by nobles','A colonial tax system','A church court']],
[I,'<p><strong>Declaration of Independence, 1776:</strong> Governments derive “their just powers from the consent of the governed.”</p><p>Which Enlightenment principle is most direct?</p>','Legitimate authority depends on popular consent',['Divine-right monarchy','Hereditary legal privilege','Mercantilism']],
[I,'<p><strong>Rights of Man, 1789:</strong> “The principle of all sovereignty resides essentially in the nation.”</p><p>Which claim does this support?</p>','Political authority comes from the nation rather than solely from a monarch',['Clergy possess all legal authority','Foreign rulers control French law','Social estates should remain unequal']],
[I,'<p><strong>Olympe de Gouges, 1791:</strong> “Woman is born free and remains equal to man in rights.”</p><p>What contradiction does this source expose?</p>','Revolutionary equality language did not automatically include women in equal political rights',['Women controlled the National Assembly','The revolution rejected all rights language','France had already achieved universal suffrage']],
[I,'<table border="1"><tr><th>American</th><th>French</th></tr><tr><td>1776 Declaration</td><td>1789 Estates-General and Bastille</td></tr><tr><td>1787 Constitution</td><td>1792 Republic</td></tr><tr><td>1791 Bill of Rights</td><td>1793–94 Terror</td></tr></table><p>Which conclusion best uses the timeline?</p>','Both produced political documents, but the French Revolution underwent more rapid radicalization',['The French republic began before the Declaration of Independence','Both followed identical sequences','The American Bill of Rights caused the Bastille']],
[I,'<p><strong>Map description:</strong> British North America lay across the Atlantic from Britain; France was a European monarchy near rival states and connected to Caribbean colonies.</p><p>Which geographic distinction matters most?</p>','The American struggle involved colonial separation across the Atlantic, while France experienced internal revolution with wider European pressures',['The Atlantic prevented ideas from circulating','France had no colonial connections','Geography made political grievances identical']],
[I,'<table border="1"><tr><th>Estate</th><th>Position</th></tr><tr><td>First</td><td>Clergy with corporate privileges</td></tr><tr><td>Second</td><td>Nobility with corporate privileges</td></tr><tr><td>Third</td><td>Most commoners, internally diverse, bearing unequal burdens</td></tr></table><p>Which grievance is best supported?</p>','Estate privilege and unequal taxation contributed to political conflict',['All estates possessed identical status','The Third Estate consisted only of peasants','France had no representative tradition']],
[I,'<table border="1"><tr><th>Idea</th><th>Grievance</th><th>Document</th></tr><tr><td>Natural rights</td><td>Imperial rule without accepted representation</td><td>Declaration of Independence</td></tr><tr><td>Popular sovereignty</td><td>Estate privilege and royal authority</td><td>Rights of Man</td></tr></table><p>What relationship does the chart show?</p>','Shared Enlightenment ideas were applied to different grievances and political settings',['Ideas alone created both revolutions','Both documents solved every inequality','The grievances were identical']],
[I,'<p><strong>Cahier context:</strong> In 1789 communities prepared grievance lists requesting changes such as fairer taxation, representative meetings, and protection from arbitrary rule.</p><p>What is the source most useful for studying?</p>','Reform demands circulating before and during the Estates-General',['Exact opinions of every French person','Military tactics at the Bastille','Napoleon’s later legal code']],
[I,'<table border="1"><tr><th>Ideal</th><th>Historical practice</th></tr><tr><td>Equality</td><td>Slavery and gender exclusion continued</td></tr><tr><td>Consent</td><td>Political participation remained restricted</td></tr></table><p>Which interpretation is strongest?</p>','Universal political language coexisted with exclusions in practice',['The declarations contained no ideals','Every group received equal rights immediately','Contradictions make the sources historically useless']],
[I,'<p>A political image celebrates the storming of the Bastille as a heroic popular victory.</p><p>What limitation should a historian note?</p>','The commemorative image emphasizes symbolic meaning but cannot by itself explain all causes of the Revolution',['Images cannot serve as historical evidence','The image proves the Bastille caused every later event','The image provides exact food-price data']],
[A,'Why is it inaccurate to say the Enlightenment alone caused both revolutions?','Ideas shaped arguments, but economic, political, social, and imperial conditions also produced conflict',['Enlightenment thinkers rejected rights','Both revolutions occurred before Enlightenment writing','Only military technology mattered']],
[A,'Which comparison is most accurate?','The American Revolution primarily sought colonial independence, while the French Revolution also attacked an internal monarchy and estate hierarchy',['Both revolutions sought separation from overseas empires','Neither changed political legitimacy','France retained its monarchy throughout']],
[A,'Which evidence best supports a similarity?','Both central declarations connected legitimate authority to rights and the people',['Only France experienced taxation disputes','Only America published political documents','Both immediately ended slavery']],
[A,'Which evidence best explains greater French radicalization?','Fiscal and food crises, internal social conflict, war, and struggles over monarchy intensified political instability',['The Bastille held a huge national army','France had no Enlightenment influence','All French groups agreed on policy']],
[A,'A student claims that the Declaration of Independence created universal equality. What is the strongest correction?','Its equality language was influential, but slavery, Indigenous exclusion, women’s exclusion, and restricted participation continued',['The declaration never mentioned equality','The declaration immediately ended colonial rule everywhere','Equality applied only to France']],
[A,'Which source pair best supports a comparison of revolutionary rights language?','The Declaration of Independence and the Declaration of the Rights of Man',['A map and an unrelated royal portrait','Two modern fictional novels','A crop list and a military uniform']],
[A,'Which question best contextualizes the Rights of Man?','How did France’s estate system, fiscal crisis, and political conflict shape its claims about rights and sovereignty?',['Is the document older than every American source?','Does one article prove every citizen agreed?','What color was the original paper?']],
[A,'Which claim-evidence-reasoning response is strongest?','Because the Rights of Man located sovereignty in the nation amid a crisis of monarchy and privilege, it challenged both royal authority and inherited legal hierarchy',['France changed because revolution means change','The Bastille mattered because it was famous','Both revolutions were identical because both used rights language']],
[A,'Which statement identifies cause and effect without oversimplifying?','Tax inequality, fiscal crisis, food pressure, political conflict, and Enlightenment arguments together weakened the Ancien Régime and encouraged revolutionary action',['One book directly caused every revolutionary event','The Bastille alone created the fiscal crisis','All French people acted for one reason']],
[A,'Which conclusion best explains different outcomes?','Similar ideas operated within different colonial, social, fiscal, and political contexts, producing different degrees and forms of change',['Political ideas always create identical governments','Geography alone determined every event','Neither revolution altered authority']]
];
const pos=[1,3,0,2,1,2,0,3,1,2,3,0,2,1,3,0,2,1,3,0,2,3,1,0,2]; const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;'); let xml='<?xml version="1.0" encoding="UTF-8"?>\n<quiz>\n',last=''; q.forEach((x,n)=>{let[cat,p,c,w]=x;if(cat!==last){xml+=`<question type="category"><category><text>$course$/top/WH/U04/L03/${cat}</text></category></question>\n`;last=cat;}let ans=[...w];ans.splice(pos[n],0,c);xml+=`<question type="multichoice"><name><text>WH_U04_L03_${cat}_Q${String(n+1).padStart(2,'0')}</text></name><questiontext format="html"><text><![CDATA[${p}]]></text></questiontext><generalfeedback format="html"><text><![CDATA[Review the source, context, and comparison category.]]></text></generalfeedback><defaultgrade>1</defaultgrade><penalty>0.3333333</penalty><hidden>0</hidden><single>true</single><shuffleanswers>true</shuffleanswers><answernumbering>abc</answernumbering>${ans.map(v=>`<answer fraction="${v===c?100:0}"><text>${esc(v)}</text><feedback format="html"><text><![CDATA[${v===c?'Correct.':'Review the evidence and explain the historical relationship.'}]]></text></feedback></answer>`).join('')}</question>\n`;}); xml+='</quiz>\n'; fs.writeFileSync(out,xml,'utf8'); console.log(`Wrote ${q.length} questions`);
