import fs from 'node:fs';
const out='Refined Courses/WORLD HISTORY/Units/Unit 04/Moodle XML/WH_U04_L05_Quiz_MoodleXML.xml',F='Foundational',I='Interpretation',A='Application';
const q=[
[F,'What is industrialization?','The development of machine-based manufacturing and industrial production',['A return to feudal farming','The legal abolition of factories','A political independence movement']],
[F,'What is the factory system?','Centralized production that concentrates workers and machinery in workplaces',['Home production controlled entirely by families','Farming on common land','Trade conducted only through ports']],
[F,'What is urbanization?','The growth of cities and the share of people living in urban areas',['The spread of rural cottage production','The reduction of transportation networks','The legal division of factory labor']],
[F,'What is capital?','Wealth or resources invested in production',['Coal used only for home heating','A city that serves as a government seat','Labor performed without wages']],
[F,'Which statement about James Watt is accurate?','He significantly improved existing steam-engine technology',['He invented the first steam engine in history','He created the factory system alone','He discovered coal in Britain']],
[I,'<table border="1"><tr><th>Map feature</th><th>Industrial use</th></tr><tr><td>Coal districts</td><td>Energy</td></tr><tr><td>Iron districts</td><td>Machinery and rails</td></tr><tr><td>Ports and waterways</td><td>Movement of inputs and goods</td></tr></table><p>Which inference is strongest?</p>','Resource location and transport connections could lower costs when combined with capital and technology',['Coal alone guaranteed industrialization','Ports made labor unnecessary','All industries had to locate in one city']],
[I,'<p><strong>Worker-source summary:</strong> Parliamentary inquiries recorded long hours, exhaustion, dangerous machines or mines, and punishment or wage loss.</p><p>What effect is documented?</p>','Severe risks and discipline in some early industrial workplaces',['Universal prosperity for every worker','The disappearance of child labor before factories','Complete government regulation']],
[I,'<p><strong>Employer perspective:</strong> An owner emphasizes productivity, regular employment, expanding markets, and the cost of regulation.</p><p>What limitation should a historian note?</p>','The owner may minimize worker hardship and prioritize business interests',['The source cannot reveal industrial arguments','All employer claims are automatically false','The source proves every worker agreed']],
[I,'<table border="1"><tr><th>Indicator</th><th>Early 1800s</th><th>Mid-1800s</th></tr><tr><td>Urban population share</td><td>Minority</td><td>Approximately half or more</td></tr><tr><td>Coal/textile output</td><td>Growing</td><td>Much larger</td></tr></table><p>Which trend is supported?</p>','Industrial expansion accompanied rapid urbanization and rising production',['Urban population declined sharply','Coal use ended by mid-century','Production remained unchanged']],
[I,'<table border="1"><tr><th>Cottage production</th><th>Factory production</th></tr><tr><td>Homes/small workshops</td><td>Centralized workplace</td></tr><tr><td>Household tools and flexible rhythms</td><td>Machines, supervision, fixed discipline</td></tr></table><p>What changed most directly?</p>','Employers gained greater control over machinery, location, and work time',['All wage labor disappeared','Production returned to farms','Workers owned every factory']],
[I,'<p><strong>Transport chain:</strong> Mine or cotton source → canal/rail/port → factory → market.</p><p>Why did infrastructure reinforce industrialization?</p>','It reduced movement costs and connected inputs, production, and consumers',['It eliminated the need for capital','It prevented markets from expanding','It replaced all factory machinery']],
[I,'<table border="1"><tr><th>Coal</th><th>Steam technology</th><th>Capital</th><th>Transport</th></tr><tr><td>Energy source</td><td>Converted energy to mechanical work</td><td>Funded equipment</td><td>Moved fuel and goods</td></tr></table><p>What does the table demonstrate?</p>','Causes interacted rather than operating independently',['One invention explains all change','Geography had no role','Capital mattered only after industrialization ended']],
[I,'<p>A textile-factory illustration shows rows of machines and workers in one large room.</p><p>Which claim can the image best support?</p>','Production and labor were centralized around machinery',['Every worker received the same wage','The factory had no hazards','Britain lacked cottage production']],
[I,'<p><strong>Global evidence:</strong> British textile mills processed imported cotton and sold goods through overseas markets connected to empire and slavery.</p><p>Which interpretation follows?</p>','British industrialization depended partly on global systems of raw materials, labor, and markets',['Industrialization was entirely internal','Cotton had no role in textiles','Empire prevented trade']],
[I,'<table border="1"><tr><th>Effect</th><th>Evidence</th></tr><tr><td>Urban growth</td><td>Crowding and housing pressure</td></tr><tr><td>Environment</td><td>Coal smoke and contaminated water</td></tr><tr><td>Labor</td><td>Long hours and hazardous machinery</td></tr></table><p>Which conclusion is strongest?</p>','Industrialization transformed society while producing serious social and environmental costs',['Every effect was beneficial','Only factory owners experienced change','Environmental effects began centuries later']],
[A,'Why is coal alone an inadequate explanation for British industrialization?','Coal became industrially powerful through interaction with capital, technology, labor, transport, and markets',['Britain had no coal','Coal was used only after 1900','Coal automatically creates factories everywhere']],
[A,'Which causal explanation best accounts for why Britain industrialized first?','Geographic resources, investment, trade, agriculture, labor, technology, institutions, and transport reinforced one another',['One inventor caused the entire process','Population growth alone built factories','British law prohibited investment']],
[A,'Which statement best distinguishes a cause from an effect?','Coal, capital, and transport helped enable industrialization; urban crowding and pollution were consequences',['Urban pollution caused Britain to discover coal','Factories were effects with no causes','All causes occurred after urbanization']],
[A,'Which evidence best supports Geographic Reasoning?','A resource map showing coal and iron near waterways, ports, and industrial cities',['A list of inventor birth dates','A royal portrait','A poem without place information']],
[A,'A student says women entered economic work for the first time in factories. What is the best correction?','Women worked before industrialization; factory and textile labor changed forms, locations, wages, and family economies',['Women never worked in factories','Only men participated in cottage industry','Industrialization ended domestic labor']],
[A,'Which claim best reflects the standard-of-living debate?','Early industrialization imposed severe hardship on many while rising output and later income/consumer changes complicate a single verdict',['Industrialization immediately improved life for all','Everyone became permanently poorer','Living conditions cannot be studied']],
[A,'Which source combination best corroborates early factory conditions?','Worker testimony, factory rules, medical or parliamentary reports, and employer records',['One fictional story alone','A coal map without labor evidence','A single modern opinion']],
[A,'Which continuity-and-change statement is strongest?','Women and children continued contributing to family economies, while factories changed schedules, supervision, and workplace hazards',['All family work disappeared','No work practices changed','Only aristocrats became wage workers']],
[A,'Which claim-evidence-reasoning response is strongest?','Because transport linked mines, ports, factories, and markets, infrastructure lowered costs and allowed industrial production to expand',['Transport mattered because railways are important','Coal caused everything by itself','Cities grew without any connection to industry']],
[A,'Which conclusion best connects industrialization to global history?','British factories were linked to overseas cotton, coerced labor, colonial markets, trade, and imperial power',['Britain produced every raw material domestically','Industrialization ended international trade','Empire had no economic relationship to industry']]
];
const pos=[1,3,0,2,1,2,0,3,1,2,3,0,2,1,3,0,2,1,3,0,2,3,1,0,2],esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');let xml='<?xml version="1.0" encoding="UTF-8"?>\n<quiz>\n',last='';q.forEach((x,n)=>{let[cat,p,c,w]=x;if(cat!==last){xml+=`<question type="category"><category><text>$course$/top/WH/U04/L05/${cat}</text></category></question>\n`;last=cat;}let ans=[...w];ans.splice(pos[n],0,c);xml+=`<question type="multichoice"><name><text>WH_U04_L05_${cat}_Q${String(n+1).padStart(2,'0')}</text></name><questiontext format="html"><text><![CDATA[${p}]]></text></questiontext><generalfeedback format="html"><text><![CDATA[Review the cause, evidence, and consequence identified in the lesson.]]></text></generalfeedback><defaultgrade>1</defaultgrade><penalty>0.3333333</penalty><hidden>0</hidden><single>true</single><shuffleanswers>true</shuffleanswers><answernumbering>abc</answernumbering>${ans.map(v=>`<answer fraction="${v===c?100:0}"><text>${esc(v)}</text><feedback format="html"><text><![CDATA[${v===c?'Correct.':'Review the evidence and connect it to the correct cause or consequence.'}]]></text></feedback></answer>`).join('')}</question>\n`;});xml+='</quiz>\n';fs.writeFileSync(out,xml,'utf8');console.log(`Wrote ${q.length} questions`);
