import fs from 'node:fs';
const out='Refined Courses/WORLD HISTORY/Units/Unit 04/Moodle XML/WH_U04_L04_Quiz_MoodleXML.xml',F='Foundational',I='Interpretation',A='Application';
const q=[
[F,'What is an independence movement?','An organized effort to end foreign political control',['A campaign to expand foreign rule','A hereditary change of monarch','A trade agreement without political change']],
[F,'Who were Creoles in colonial Spanish and Portuguese America?','People of European ancestry born in the Americas',['Officials born only in Spain or Portugal','All Indigenous political leaders','Enslaved Africans brought across the Atlantic']],
[F,'What is abolition?','The legal ending of slavery',['The creation of a monarchy','The restriction of colonial trade','The division of a colony into estates']],
[F,'Why is the Haitian Revolution historically distinctive?','It defeated colonial rule and slavery and created independent Haiti',['It preserved French slavery after independence','It was led only by European monarchs','It created a Portuguese monarchy']],
[F,'Which leader is associated with independence campaigns in Argentina, Chile, and Peru?','José de San Martín',['Miguel Hidalgo','Toussaint Louverture','Pedro I']],
[I,'<p><strong>Haitian Constitution, 1801:</strong> “There cannot exist slaves on this territory, servitude is therein forever abolished.”</p><p>Which goal is most direct?</p>','Abolition of slavery',['Restoration of plantation slavery','Continuation of French racial hierarchy','Creation of a Portuguese monarchy']],
[I,'<p><strong>Bolívar, Jamaica Letter, 1815:</strong> “We are neither Indians nor Europeans...”</p><p>What issue does the statement reveal?</p>','A distinct Spanish American identity shaped by colonial rule',['Support for permanent Spanish authority','Rejection of all republican government','A claim that colonial society had no hierarchy']],
[I,'<p><strong>Morelos, 1813:</strong> “Slavery shall be forever forbidden, as well as caste distinctions...”</p><p>Which broader grievance is expressed?</p>','Colonial social and racial inequality',['Lack of European monarchy in Mexico','Opposition to abolition','Desire to strengthen peninsular privilege']],
[I,'<table border="1"><tr><th>1776</th><th>1789</th><th>1791</th><th>1804</th><th>1810</th><th>1822</th></tr><tr><td>American Declaration</td><td>French Revolution</td><td>Haitian uprising</td><td>Haitian independence</td><td>Mexican uprising</td><td>Brazilian independence</td></tr></table><p>What does the chronology support?</p>','Revolutionary ideas and conflicts circulated across the Atlantic but developed in distinct local settings',['Every movement began at the same time','Brazilian independence caused the French Revolution','Haiti became independent after Brazil']],
[I,'<table border="1"><tr><th>Place</th><th>Outcome</th></tr><tr><td>Haiti</td><td>Independent state; slavery abolished</td></tr><tr><td>Brazil</td><td>Independent monarchy; slavery continued</td></tr></table><p>Which comparison is best supported?</p>','Political independence produced very different degrees of social change',['Both movements immediately created republics','Both preserved slavery','Brazil achieved greater abolitionist change']],
[I,'<p><strong>Map description:</strong> Haiti lies in the Caribbean; Mexico is in northern Latin America; Bolívar’s campaigns centered in northern South America; San Martín’s linked Argentina, Chile, and Peru; Brazil occupies eastern South America.</p><p>Which conclusion follows?</p>','Independence developed across multiple regions with different leaders and political paths',['Bolívar led every movement','All movements occurred in one colony','Geography made outcomes identical']],
[I,'<table border="1"><tr><th>Group</th><th>Typical colonial position</th></tr><tr><td>Peninsulares</td><td>Often held highest offices</td></tr><tr><td>Creoles</td><td>Could be wealthy but faced political limits</td></tr><tr><td>Indigenous, African-descended, and mixed-race populations</td><td>Experienced varied forms of labor exploitation and exclusion</td></tr></table><p>What cause is represented?</p>','Unequal colonial hierarchy contributed to grievances',['All groups held equal authority','Only foreign wars mattered','Colonial society lacked economic inequality']],
[I,'<p>A Creole leader’s memoir emphasizes elite constitutional goals but says little about enslaved or Indigenous participants.</p><p>What is the most important limitation?</p>','It may underrepresent non-elite goals and experiences',['It cannot reveal any elite political ideas','It proves non-elites did not participate','It provides exact evidence for Haiti']],
[I,'<table border="1"><tr><th>Long-term</th><th>Immediate crisis</th></tr><tr><td>Political exclusion, economic restrictions, hierarchy</td><td>Napoleon’s invasion of Spain and crisis of monarchy</td></tr></table><p>Which causal explanation is strongest?</p>','Long-term colonial grievances interacted with a European political crisis',['Napoleon alone created all grievances','Colonial hierarchy began after independence','Ideas had no connection to events']],
[I,'<p><strong>Secondary interpretation:</strong> Haiti’s enslaved majority attacked slavery and empire; many Spanish American movements relied heavily on Creole leadership; Brazil separated under a monarchy.</p><p>What does the interpretation emphasize?</p>','Shared independence goals did not produce identical social foundations or outcomes',['Every movement abolished slavery','All leaders held the same political beliefs','Latin American independence was one unified war']],
[A,'Why is it inaccurate to say Bolívar led all Latin American independence movements?','Haiti, Mexico, southern South America, and Brazil had distinct leaders and paths',['Bolívar ruled Portugal','No movement used military leadership','Only Mexico achieved independence']],
[A,'Which comparison best distinguishes Haiti from many Spanish American movements?','Haiti’s enslaved and free African-descended revolutionaries made abolition central, while Creole leadership was more prominent in many Spanish American movements',['Haiti preserved slavery while Spanish America abolished it everywhere','Both had identical participants','Haiti remained a French colony']],
[A,'Which evidence best supports the claim that independence did not guarantee equality?','Brazil retained monarchy and slavery, while hierarchy and unequal participation persisted elsewhere',['Every region ended colonial rule','Leaders published political documents','Movements occurred across a large area']],
[A,'Which cause-and-effect statement is strongest?','Napoleon’s invasion weakened Spanish monarchical authority, allowing long-standing colonial grievances to produce new local political movements',['Napoleon invented colonial hierarchy','Enlightenment books alone forced independence','Brazilian independence caused the Haitian uprising']],
[A,'A historian ranks Haiti as the most socially transformative movement. Which evidence is strongest?','It combined political independence with abolition of slavery and a direct challenge to colonial racial hierarchy',['It occurred before Brazil’s independence','It had famous leaders','It was located in the Caribbean']],
[A,'Which question best evaluates perspective in a Bolívar source?','How did Bolívar’s Creole background, audience, and concerns about political order shape his argument?',['Is every statement automatically false?','What color was the manuscript?','Does the source represent all enslaved people?']],
[A,'Which claim-evidence-reasoning response is strongest?','Because Brazil became independent under Pedro while monarchy and slavery continued, its political separation involved more social continuity than Haiti’s revolution',['Brazil changed because independence means change','Haiti was different because it was earlier','All movements were equal without comparison']],
[A,'Which example best represents a non-elite perspective?','The goals and participation of enslaved Haitians, Indigenous communities, free people of color, and Mexican peasants',['Only the titles of Creole leaders','A list of European monarchs','A trade table with no people']],
[A,'Why did Atlantic revolutionary ideas produce different results?','Local systems of slavery, hierarchy, leadership, economic grievance, and political crisis shaped how ideas were applied',['Ideas always create identical institutions','Geography prevented ideas from circulating','Every colony had the same population']],
[A,'Which conclusion best distinguishes political independence from social revolution?','Ending foreign rule changes sovereignty, but broader transformation requires changes to slavery, hierarchy, land, and participation',['Independence automatically ends inequality','Social revolution means only changing a flag','Political sovereignty has no historical importance']]
];
const pos=[1,3,0,2,1,2,0,3,1,2,3,0,2,1,3,0,2,1,3,0,2,3,1,0,2],esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');let xml='<?xml version="1.0" encoding="UTF-8"?>\n<quiz>\n',last='';q.forEach((x,n)=>{let[cat,p,c,w]=x;if(cat!==last){xml+=`<question type="category"><category><text>$course$/top/WH/U04/L04/${cat}</text></category></question>\n`;last=cat;}let ans=[...w];ans.splice(pos[n],0,c);xml+=`<question type="multichoice"><name><text>WH_U04_L04_${cat}_Q${String(n+1).padStart(2,'0')}</text></name><questiontext format="html"><text><![CDATA[${p}]]></text></questiontext><generalfeedback format="html"><text><![CDATA[Review the movement, source perspective, and comparison category.]]></text></generalfeedback><defaultgrade>1</defaultgrade><penalty>0.3333333</penalty><hidden>0</hidden><single>true</single><shuffleanswers>true</shuffleanswers><answernumbering>abc</answernumbering>${ans.map(v=>`<answer fraction="${v===c?100:0}"><text>${esc(v)}</text><feedback format="html"><text><![CDATA[${v===c?'Correct.':'Review the evidence and connect it directly to the movement and question.'}]]></text></feedback></answer>`).join('')}</question>\n`;});xml+='</quiz>\n';fs.writeFileSync(out,xml,'utf8');console.log(`Wrote ${q.length} questions`);
