import fs from 'node:fs';
const out='Refined Courses/WORLD HISTORY/Units/Unit 04/Moodle XML/WH_U04_L06_Quiz_MoodleXML.xml',F='Foundational',I='Interpretation',A='Application';
const q=[
[F,'What is capitalism?','An economic system based largely on private ownership, investment, markets, and profit',['A theory requiring all property to be hereditary','A labor law limiting child work','A system without wage labor or markets']],
[F,'What is a labor union?','An organization of workers pursuing shared workplace or economic goals',['A group of factory owners fixing prices','A government ministry controlling colonies','A court enforcing property inheritance']],
[F,'What is collective bargaining?','Negotiation between workers and employers over wages, hours, and conditions',['Competition among individual consumers','A revolutionary seizure of all property','A tax on imported machinery']],
[F,'In Marxist theory, who are the proletariat?','Wage workers who do not own major productive property',['Owners of productive capital','Hereditary aristocrats only','Government inspectors']],
[F,'What is reform?','Change intended to improve an existing system rather than completely replace it',['The abolition of every institution','A refusal to change any law','A theory of market pricing']],
[I,'<p><strong>Adam Smith, 1776:</strong> “The greatest improvement in the productive powers of labour...seem to have been the effects of the division of labour.”</p><p>Which claim is supported?</p>','Specialization can increase productive efficiency',['Competition always eliminates inequality','Government has no legitimate functions','Workers should abolish productive property']],
[I,'<p><strong>Marx and Engels, 1848:</strong> “The history of all hitherto existing society is the history of class struggles.”</p><p>Which analytical emphasis is most direct?</p>','Conflict among classes with different economic interests',['Harmony produced automatically by markets','The disappearance of wage labor','Gradual factory legislation']],
[I,'<p><strong>Worker-source summary:</strong> Petitions described long hours, unsafe factories, child labor, and weak individual bargaining power.</p><p>Which response follows most directly?</p>','Collective organization and labor protection',['Elimination of all public health laws','Stronger hereditary privilege','Expansion of colonial offices']],
[I,'<p><strong>Factory Act summary:</strong> Legislation gradually restricted some child labor and hours and created inspection requirements.</p><p>Where does this fall on the reform–revolution continuum?</p>','Incremental reform within existing institutions',['Fundamental abolition of the property system','Restoration of feudal labor','Complete rejection of government action']],
[I,'<table border="1"><tr><th>Perspective</th><th>Ownership</th><th>Change</th></tr><tr><td>Classical liberal capitalism</td><td>Private property</td><td>Markets and limited regulation</td></tr><tr><td>Broad socialism</td><td>Greater social/collective control; traditions vary</td><td>Cooperation, reform, public action, or other methods</td></tr><tr><td>Marxist communism</td><td>Collective ownership as theoretical goal</td><td>Revolutionary class transformation</td></tr></table><p>What does the matrix show?</p>','Socialism is broader than Marxist communism and includes varied methods',['All three perspectives are identical','Every socialist rejects reform','Capitalism means government never acts']],
[I,'<table border="1"><tr><th>Owners</th><th>Professionals</th><th>Skilled workers</th><th>Factory laborers</th></tr><tr><td>Invest capital</td><td>Provide specialized services</td><td>Possess trained skills</td><td>Depend largely on wages</td></tr></table><p>What limitation does this diagram expose in a simple two-class model?</p>','Industrial society contained multiple groups and positions',['No wage workers existed','Every professional owned a factory','Marx denied class conflict']],
[I,'<p><strong>Owner perspective:</strong> A manufacturer stresses investment risk, productivity, jobs, and competition while opposing work-hour rules.</p><p>Which limitation is most important?</p>','The owner may understate unequal bargaining power and worker hazards',['The source cannot show any market argument','Every claim is automatically false','The source represents all workers']],
[I,'<p><strong>Union statement:</strong> Workers demand shorter hours and safer machinery through collective action.</p><p>Which economic problem is being addressed?</p>','Power imbalance between individual workers and employers',['Lack of colonial territory','Decline of private investment everywhere','Absence of wage labor']],
[I,'<table border="1"><tr><th>Earlier</th><th>Later</th></tr><tr><td>Many unions restricted; limited factory law</td><td>Gradual union recognition and expanded labor/public-health regulation</td></tr></table><p>What trend is supported?</p>','Worker protection developed gradually through organization and political pressure',['Protections appeared immediately','Reform eliminated all inequality','Revolution replaced every institution']],
[I,'<p><strong>Secondary interpretation:</strong> Industrial societies mixed private markets, regulation, unions, public institutions, and social reforms.</p><p>Which conclusion follows?</p>','Real economies rarely matched pure ideological models exactly',['Capitalism and socialism are interchangeable','Regulation eliminates every market','Only one class existed']],
[A,'Why did industrialization generate competing economic theories?','Wealth creation, inequality, wage labor, unsafe conditions, and class change prompted different explanations and solutions',['Industrialization eliminated economic debate','All groups experienced identical outcomes','Factories ended private property']],
[A,'Which comparison between classical liberalism and socialism is strongest?','Classical liberals emphasized private property and markets, while socialists emphasized varied forms of collective responsibility and equality',['Both demanded identical revolutionary methods','Only socialism addressed production','Classical liberals rejected contracts']],
[A,'Why is it inaccurate to say capitalism means government does nothing?','Historical capitalist societies used laws, justice, defense, public works, taxation, and varying regulation',['Capitalism prohibits courts','Smith rejected all public works','Markets cannot exist with laws']],
[A,'Why are socialism and communism not interchangeable labels?','Socialism is a broad family of traditions; Marxist communism is a specific revolutionary theory',['Communism is a labor union','Socialism always requires one identical government','Neither addresses ownership']],
[A,'Which evidence best supports a gradual-reform argument?','Factory laws and union bargaining changed hours and conditions without replacing the whole property system',['The Communist Manifesto’s class-struggle theory','A demand to abolish every institution','A colonial independence declaration']],
[A,'Which question best evaluates the perspective of a worker petition?','How did workers’ conditions, goals, audience, and need for collective action shape the claims?',['Is every employer automatically dishonest?','What color was the paper?','Does one petition represent every worker?']],
[A,'Which claim-evidence-reasoning response is strongest?','Because Factory Acts restricted selected child labor and hours, reformers used government regulation to address industrial harm gradually',['Reform occurred because reform means improvement','Markets solved every problem instantly','All workers preferred revolution']],
[A,'A student says Marx described twentieth-century communist states. What is the best correction?','Marx wrote nineteenth-century industrial theory; later governments developed in different contexts',['Marx governed every later state','The Manifesto was written after 1950','Marx rejected class analysis']],
[A,'Which response most directly increases workers’ bargaining power while retaining private ownership?','Labor unions and collective bargaining',['Hereditary monarchy','Abolition of all markets','Colonial trade restriction']],
[A,'Which conclusion best compares reform and revolution?','Reform changes institutions through laws, unions, elections, or programs; revolution seeks fundamental structural replacement',['They are identical methods','Reform always rejects law','Revolution means any small regulation']]
];
const pos=[1,3,0,2,1,2,0,3,1,2,3,0,2,1,3,0,2,1,3,0,2,3,1,0,2],esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');let xml='<?xml version="1.0" encoding="UTF-8"?>\n<quiz>\n',last='';q.forEach((x,n)=>{let[cat,p,c,w]=x;if(cat!==last){xml+=`<question type="category"><category><text>$course$/top/WH/U04/L06/${cat}</text></category></question>\n`;last=cat;}let ans=[...w];ans.splice(pos[n],0,c);xml+=`<question type="multichoice"><name><text>WH_U04_L06_${cat}_Q${String(n+1).padStart(2,'0')}</text></name><questiontext format="html"><text><![CDATA[${p}]]></text></questiontext><generalfeedback format="html"><text><![CDATA[Review the economic perspective, source, and reform-versus-revolution distinction.]]></text></generalfeedback><defaultgrade>1</defaultgrade><penalty>0.3333333</penalty><hidden>0</hidden><single>true</single><shuffleanswers>true</shuffleanswers><answernumbering>abc</answernumbering>${ans.map(v=>`<answer fraction="${v===c?100:0}"><text>${esc(v)}</text><feedback format="html"><text><![CDATA[${v===c?'Correct.':'Review the evidence and compare the same economic category.'}]]></text></feedback></answer>`).join('')}</question>\n`;});xml+='</quiz>\n';fs.writeFileSync(out,xml,'utf8');console.log(`Wrote ${q.length} questions`);
