import fs from 'node:fs';

const out='Refined Courses/WORLD HISTORY/Units/Unit 04/Moodle XML/WH_U04_L02_Quiz_MoodleXML.xml';
const F='Foundational',I='Interpretation',A='Application';
const q=[
[F,'Which statement best defines the Enlightenment?','An intellectual movement that used reason to examine government, society, and human rights',['A campaign to restore feudal obligations','A movement that rejected scientific inquiry','A plan to strengthen divine-right monarchy']],
[F,'What are natural rights?','Rights people possess by nature rather than receive as gifts from a ruler',['Privileges reserved for hereditary nobles','Rules created only during wartime','Taxes approved by representative bodies']],
[F,'In Enlightenment political thought, what is a social contract?','An agreement in which people accept government in exchange for order or protection of rights',['A trade treaty between monarchs','A contract that permanently ends political disagreement','A law requiring every government to be democratic']],
[F,'What does popular sovereignty mean?','Legitimate political authority comes from the people',['Kings rule because God selected their dynasties','Judges hold all governing power','Nobles inherit authority over national law']],
[F,'What is separation of powers?','Dividing government authority among branches or institutions to limit abuse',['Giving all authority to one efficient ruler','Separating citizens by social class','Removing lawmaking from government']],
[I,'<p><strong>Source passage (modernized):</strong> Thomas Hobbes argued in <em>Leviathan</em> (1651) that without a common power capable of keeping order, people would live in continuing insecurity and conflict.</p><p>Which conclusion best represents Hobbes\'s reasoning?</p>','People may accept a powerful sovereign because security is a basic purpose of government',['People should abolish all government','Natural rights always require weak executive authority','Popular voting automatically ends conflict']],
[I,'<p><strong>Source passage (modernized):</strong> John Locke argued in the <em>Second Treatise of Government</em> (1689) that people form governments to protect life, liberty, and property, and may resist a government that violates its trust.</p><p>Which principle is most directly supported?</p>','Government depends on consent and must protect natural rights',['Rulers possess unlimited divine authority','Security requires citizens to surrender every right','Political liberty depends on hereditary privilege']],
[I,'<p><strong>Source passage (translated and modernized):</strong> Montesquieu wrote in <em>The Spirit of the Laws</em> (1748) that liberty is endangered when legislative, executive, and judicial powers are united in the same hands.</p><p>Which reform follows most directly?</p>','Divide authority among institutions able to check one another',['Place courts under a single absolute monarch','Eliminate written laws','Allow one branch to control every function']],
[I,'<p><strong>Source passage (translated and modernized):</strong> Rousseau argued in <em>The Social Contract</em> (1762) that legitimate law expresses the general will of citizens rather than the private will of a ruler.</p><p>Which concept is central to this claim?</p>','Popular sovereignty',['Divine right','Mercantilism','Hereditary privilege']],
[I,'<p><strong>Source context:</strong> Voltaire criticized religious persecution and arbitrary censorship and defended toleration and freedom of expression.</p><p>Which institution or practice would he most likely challenge?</p>','A government punishing people for dissenting religious or political views',['A legislature publicly debating laws','A court requiring evidence','A publisher comparing philosophical arguments']],
[I,'<table border="1" cellpadding="5"><tr><th>Thinker</th><th>Main concern</th><th>Proposed principle</th></tr><tr><td>Hobbes</td><td>Disorder and insecurity</td><td>Strong sovereign authority</td></tr><tr><td>Locke</td><td>Abuse of rights</td><td>Consent and right of resistance</td></tr></table><p>Which comparison is supported?</p>','Both used social-contract reasoning, but they reached different conclusions about the limits on authority',['Only Locke believed government had any purpose','Both defended identical forms of absolute monarchy','Hobbes based authority on hereditary privilege while Locke rejected government']],
[I,'<table border="1" cellpadding="5"><tr><th>Model</th><th>Source of authority</th><th>Limit on ruler</th></tr><tr><td>Divine right</td><td>God acting through hereditary monarchy</td><td>Primarily religious and customary duties</td></tr><tr><td>Popular sovereignty</td><td>The people</td><td>Consent, law, and accountable institutions</td></tr></table><p>What major change in political reasoning does the table show?</p>','Legitimacy shifted in Enlightenment argument from inherited sacred authority toward the people',['Every European state immediately became democratic','Religion disappeared from eighteenth-century society','Hereditary monarchy ended before Enlightenment writing began']],
[I,'<table border="1" cellpadding="5"><tr><th>Date</th><th>Work</th></tr><tr><td>1651</td><td>Hobbes, <em>Leviathan</em></td></tr><tr><td>1689</td><td>Locke, <em>Second Treatise</em></td></tr><tr><td>1748</td><td>Montesquieu, <em>The Spirit of the Laws</em></td></tr><tr><td>1762</td><td>Rousseau, <em>The Social Contract</em></td></tr></table><p>Which conclusion is best supported by the chronology?</p>','Enlightenment political debate developed across generations rather than appearing at one moment',['Rousseau directly caused Hobbes to publish','All four works responded to the same event','Montesquieu wrote before Locke']],
[I,'<p><strong>Historical situation:</strong> A salon brought writers, nobles, and educated elites together to discuss books and political ideas. Participation was influential but socially limited.</p><p>Which interpretation is strongest?</p>','Salons helped circulate ideas while showing that access to Enlightenment debate was unequal',['Salons gave every adult equal political power','Salons prevented printed works from circulating','Only monarchs attended salons']],
[I,'<table border="1" cellpadding="5"><tr><th>Enlightenment ideal</th><th>Eighteenth-century condition</th></tr><tr><td>Natural equality</td><td>Slavery and legal privilege continued</td></tr><tr><td>Reasoned public debate</td><td>Censorship continued in many states</td></tr><tr><td>Consent</td><td>Most people lacked political representation</td></tr></table><p>What does the evidence demonstrate?</p>','Enlightenment ideals could challenge society even when practice remained inconsistent',['Enlightenment ideas were never discussed','Every ruler immediately ended inequality','The ideals supported all existing privileges']],
[A,'A ruler claims that subjects owe obedience because the royal family was chosen by God. Which Enlightenment response most directly challenges this claim?','Legitimate authority depends on the people’s consent, not merely hereditary divine right',['Trade creates royal authority','A large palace proves legitimacy','Military rank produces natural rights']],
[A,'Which comparison between Hobbes and Locke is most accurate?','Both used a social contract, but Hobbes emphasized security and strong authority while Locke emphasized rights and limited government',['Hobbes defended popular sovereignty while Locke defended divine right','Both rejected government as unnecessary','Locke emphasized security while Hobbes supported a right of revolution']],
[A,'A constitution gives one branch power to write laws, another to enforce them, and courts power to interpret them. Which Enlightenment idea is being applied?','Montesquieu’s separation of powers',['Hobbes’s state of nature','Divine-right monarchy','Mercantilist regulation']],
[A,'Why does social-contract theory not automatically prove that a government is democratic?','Different thinkers described different agreements and different amounts of authority surrendered to government',['Every social contract requires universal suffrage','Hobbes rejected government entirely','The theory concerns only international trade']],
[A,'Which evidence best supports a claim that Enlightenment ideas challenged absolutism?','Locke’s argument that people may resist a government that violates their natural rights',['A royal portrait displaying expensive clothing','A list of eighteenth-century crops','A map of mountain ranges']],
[A,'A student says, “The Enlightenment created equality.” Which revision is most historically defensible?','Enlightenment arguments supplied language for equality, but slavery, gender exclusion, and legal privilege reveal a gap between ideals and practice',['The Enlightenment immediately created equal rights for everyone','Equality was never discussed by Enlightenment writers','All Enlightenment thinkers held identical views']],
[A,'Which question best evaluates the perspective of an Enlightenment author?','How might the author’s social position, audience, and political circumstances shape the argument?',['How many pages are in the modern textbook?','Is the oldest source automatically correct?','Does one quotation prove every person agreed?']],
[A,'Which claim-evidence-reasoning statement is strongest?','Because Locke tied government to protection of rights and consent, his argument provided a basis for challenging rulers who violated that trust',['Locke mattered because his ideas were important','All monarchies ended because philosophers wrote books','Natural rights and social contracts are vocabulary terms']],
[A,'Which example best shows continuity and change?','Hereditary monarchies continued, while Enlightenment writers increasingly justified authority through rights, consent, and reason',['All political traditions disappeared at once','No political ideas changed during the eighteenth century','Every country adopted the same constitution']],
[A,'A historian wants to corroborate the influence of Montesquieu’s ideas on a later constitution. Which evidence is most useful?','The constitution’s division of powers together with records showing its authors discussed Montesquieu',['A portrait of Montesquieu alone','A modern novel set in France','A list of monarchs with no constitutional evidence']]
];
const pos=[1,3,0,2,1,2,0,3,1,2,3,0,2,1,3,0,2,1,3,0,2,3,1,0,2];
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
let xml='<?xml version="1.0" encoding="UTF-8"?>\n<quiz>\n',last='';
q.forEach((x,n)=>{let [cat,prompt,correct,wrong]=x;if(cat!==last){xml+=`<question type="category"><category><text>$course$/top/WH/U04/L02/${cat}</text></category></question>\n`;last=cat;}let ans=[...wrong];ans.splice(pos[n],0,correct);xml+=`<question type="multichoice"><name><text>WH_U04_L02_${cat}_Q${String(n+1).padStart(2,'0')}</text></name><questiontext format="html"><text><![CDATA[${prompt}]]></text></questiontext><generalfeedback format="html"><text><![CDATA[Review the evidence and the Enlightenment principle used in the question.]]></text></generalfeedback><defaultgrade>1</defaultgrade><penalty>0.3333333</penalty><hidden>0</hidden><single>true</single><shuffleanswers>true</shuffleanswers><answernumbering>abc</answernumbering>${ans.map(v=>`<answer fraction="${v===correct?100:0}"><text>${esc(v)}</text><feedback format="html"><text><![CDATA[${v===correct?'Correct.':'Review the stated source or principle and connect it directly to the question.'}]]></text></feedback></answer>`).join('')}</question>\n`;});
xml+='</quiz>\n';fs.writeFileSync(out,xml,'utf8');console.log(`Wrote ${q.length} questions`);
